// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYSUFRgrZebj7KwNxVcq9P3yUUfFzrV4A',
    appId: '1:956440679907:web:57c0dbe736400276483cd6',
    messagingSenderId: '956440679907',
    projectId: 'nocrastinate-40021',
    authDomain: 'nocrastinate-40021.firebaseapp.com',
    storageBucket: 'nocrastinate-40021.firebasestorage.app',
    measurementId: 'G-5GBH3WPH3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhXq43rnqZ1KKkWsnErc4zIA7Jr0PXJs',
    appId: '1:956440679907:android:079b4d4ba0dde34a483cd6',
    messagingSenderId: '956440679907',
    projectId: 'nocrastinate-40021',
    storageBucket: 'nocrastinate-40021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqRJVijEinMxwY3rZ_Gm4CeD1Qd-WMXI',
    appId: '1:956440679907:ios:bff379fea791e793483cd6',
    messagingSenderId: '956440679907',
    projectId: 'nocrastinate-40021',
    storageBucket: 'nocrastinate-40021.firebasestorage.app',
    androidClientId: '956440679907-kfs6tkcv21pjll6keq1jtcivcqgaqik2.apps.googleusercontent.com',
    iosClientId: '956440679907-h4gvmhj5e5atciaqukvuk8790204re7u.apps.googleusercontent.com',
    iosBundleId: 'com.nocrastinate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeqRJVijEinMxwY3rZ_Gm4CeD1Qd-WMXI',
    appId: '1:956440679907:ios:b34c794b0c0795ab483cd6',
    messagingSenderId: '956440679907',
    projectId: 'nocrastinate-40021',
    storageBucket: 'nocrastinate-40021.firebasestorage.app',
    androidClientId: '956440679907-kfs6tkcv21pjll6keq1jtcivcqgaqik2.apps.googleusercontent.com',
    iosClientId: '956440679907-7cnkqgn4ljoo19vl1c23kgjgpc1leb26.apps.googleusercontent.com',
    iosBundleId: 'com.oneaimsolution.nocrastinate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYSUFRgrZebj7KwNxVcq9P3yUUfFzrV4A',
    appId: '1:956440679907:web:4df81bbdfcedf3ff483cd6',
    messagingSenderId: '956440679907',
    projectId: 'nocrastinate-40021',
    authDomain: 'nocrastinate-40021.firebaseapp.com',
    storageBucket: 'nocrastinate-40021.firebasestorage.app',
    measurementId: 'G-Y3MML1FK49',
  );

}