class Category {
  final String name;
  final List<String> tips;

  Category({
    required this.name,
    required this.tips,
  });
}

class TipData {
  static List<Category> getAllCategories() {
    return [
      Category(
        name: "Stress Management",
        tips: [
          "Practice abdominal breathing to calm your nervous system.",
          "Exercise regularly to release endorphins.",
          "Meditate to reduce your stress and improve your concentration.",
          "Listen to relaxing music to relax your mind.",
          "Maintain a healthy and balanced diet to sustain your energy.",
          "Get enough sleep to help your body regenerate.",
          "Practice mindfulness to live in the present moment.",
          "Learn to say no without guilt to reduce pressure from others.",
          "Practice dynamic relaxation to release your muscle tension.",
          "Identify the sources of your stress to better manage them.",
          "Use positive affirmations to strengthen your confidence.",
          "Take regular breaks to recharge yourself.",
          "Trust your intuition to make decisions.",
          "Learn to put difficult situations into perspective.",
          "Practice cardiac coherence to regulate your heart rate.",
          "Use visualization techniques to motivate yourself.",
          "Surround yourself with positive people to reduce your stress.",
          "Practice kindness towards yourself and others.",
          "Learn to manage your expectations to reduce your stress.",
          "Use books to learn how to manage your stress.",
          "Practice gratitude every day to balance your emotions.",
          "Learn to free yourself from negative thoughts.",
          "Use mindfulness exercises to calm yourself.",
          "Learn to focus on the present.",
          "Practice progressive muscle relaxation to relax your body.",
          "Learn to express your needs clearly.",
          "Plan your tasks to better manage your time.",
          "Learn to forgive yourself and move on.",
          "Use energizing breathing techniques to motivate yourself.",
          "Practice guided meditation to relax.",
          "Learn to focus on the positive aspects of your life.",
          "Use affirmations to boost your self-confidence.",
          "Practice mindfulness in your relationships.",
          "Learn to manage your emotions in professional situations.",
          "Use breathing techniques to calm your nervous system.",
          "Practice the 4A method: avoid, alter, accept, and adapt.",
          "Learn to free yourself from distractions to concentrate.",
          "Practice kindness towards others.",
          "Learn to manage your emotional boundaries.",
          "Use stress management techniques like walking.",
          "Practice mindfulness in your social interactions.",
          "Learn to express your emotions appropriately.",
          "Practice gratitude to balance your emotions.",
          "Learn to forgive yourself and let go of the past.",
        ],
      ),
      Category(
        name: "Social Connections and Relationships",
        tips: [
          "Participate in community activities to expand your social circle.",
          "Create opportunities to meet new people who share your interests.",
          "Practice active listening to improve the quality of your interactions.",
          "Join a club or association to meet new people.",
          "Host social events to strengthen bonds with friends and family.",
          "Check on your loved ones regularly.",
          "Show empathy to better understand others.",
          "Be authentic in your interactions to build strong relationships.",
          "Learn to say no to save your time and energy.",
          "Practice gratitude towards important people in your life.",
          "Listen without judgment to create a safe space for discussions.",
          "Create sharing moments with colleagues to improve the work atmosphere.",
          "Give sincere compliments to strengthen bonds.",
          "Participate in volunteer projects to meet people who share your values.",
          "Be present in interactions to show your interest.",
          "Use motivational words to encourage others.",
          "Create a discussion space to facilitate the exchange of ideas.",
          "Practice mindfulness to be more attentive to others.",
          "Engage in group activities to strengthen social bonds.",
          "Learn to manage conflicts to maintain healthy relationships.",
          "Be patient with others to improve communication.",
          "Host family dinners to strengthen family ties.",
          "Show respect for others' differences.",
          "Create social rituals to maintain regular contact.",
          "Use humor to lighten the atmosphere.",
          "Practice group meditation to strengthen bonds.",
          "Do compassion exercises to develop empathy.",
          "Be open to new experiences to enrich your relationships.",
          "Keep a gratitude journal to appreciate your relationships.",
          "Give symbolic gifts to show appreciation.",
          "Practice nonviolent communication to resolve conflicts.",
          "Organize outdoor outings to create sharing moments.",
          "Use communication tools to stay in touch with loved ones.",
          "Create a relaxation space to facilitate group relaxation.",
          "Engage in creative activities together to stimulate creativity.",
          "Practice gratitude towards colleagues to improve the work atmosphere.",
          "Be flexible to adapt your interactions to others' needs.",
          "Create mentorship opportunities to help others grow.",
          "Host cultural events to enrich your relationships.",
          "Use encouraging words to motivate others.",
          "Create a support group to help members overcome difficulties.",
          "Engage in wellness activities together to promote mental health.",
          "Practice guided meditation to improve concentration in groups.",
          "Be attentive to others' needs to strengthen bonds.",
          "Create culinary sharing moments to strengthen social bonds.",
          "Do visualization exercises to motivate others.",
          "Create a recognition space to value others contributions.",
        ],
      ),
      Category(
        name: "Resilience",
        tips: [
          "Recognize your emotions to better manage them.",
          "Practice mindfulness to stay present.",
          "Set realistic goals to maintain motivation.",
          "Create a support network to surround yourself with positive people.",
          "Learn to say no to protect your time and energy.",
          "Practice gratitude to appreciate each day.",
          "Do deep breathing exercises to calm your mind.",
          "Take care of your physical health to strengthen your resilience.",
          "Develop a positive attitude to face challenges.",
          "Learn from past experiences to improve your strategies.",
          "Create a relaxation space to recharge.",
          "Engage in creative activities to express your emotions.",
          "Use relaxation techniques to reduce stress.",
          "Practice meditation to improve your concentration.",
          "Set mini-goals to progress step by step.",
          "Recognize your strengths to boost your confidence.",
          "Keep a gratitude journal to appreciate each day.",
          "Practice mindfulness during meals to appreciate flavors.",
          "Take regular breaks to avoid fatigue.",
          "Use motivational words to encourage yourself.",
          "Create an action plan to overcome obstacles.",
          "Do visualization exercises to motivate yourself.",
          "Practice self-compassion to accept your mistakes.",
          "Surround yourself with positive people to enhance your well-being.",
          "Learn to manage conflicts to maintain healthy relationships.",
          "Create a sharing space to discuss your emotions.",
          "Do muscle strengthening exercises to improve your physical health.",
          "Practice mindful walking to reconnect with nature.",
          "Set long-term goals to maintain a global vision.",
          "Create a morning routine to start the day positively. Such as stretching, learn a new skill.",
          "Do alternate breathing exercises to balance your mood.",
          "Practice gratitude towards loved ones to strengthen bonds.",
          "Use essential oils to create a relaxing atmosphere.",
          "Create a creativity space to express your ideas.",
          "Reward yourself to celebrate your achievements.",
          "Do visualization exercises for success to motivate yourself.",
          "Use positive quotes to encourage yourself.",
          "Keep a wellness journal to track your progress.",
          "Do conscious breathing before bed to improve sleep.",
          "Create an outdoor relaxation space to recharge.",
          "Practice gratitude for small moments to appreciate each instant.",
          "Create a support group to surround yourself with positive people.",
          "Practice mindfulness in every moment to stay present and resilient.",
        ],
      ),
      Category(
        name: "Productivity and Focus",
        tips: [
          "Plan your days to stay focused on your goals.",
          "Align your tasks with long-term objectives.",
          "Prepare for the next day the evening before.",
          "Break down large projects into manageable tasks.",
          "Avoid multitasking to maintain concentration.",
          "Adopt Deep Work to work without distractions.",
          "Allow chaos sometimes to stimulate creativity.",
          "Eliminate distractions to improve productivity.",
          "Write an attention charter to remind yourself of priorities.",
          "Follow the 2-minute rule to complete small tasks.",
          "Delegate when necessary to free up time.",
          "Communicate effectively with your team.",
          "Follow the 10-minute rule for regular breaks.",
          "Use the Sandwich technique to make tasks more enjoyable.",
          "Batch similar tasks to optimize time.",
          "Eliminate non-essential tasks.",
          "Say no more often to protect your time.",
          "Automate tasks following the rule of three.",
          "Create themed days to organize your week.",
          "Be intentional in your daily actions.",
          "Optimize downtime for learning or relaxation.",
          "Don't keep more than 10 tabs open simultaneously.",
          "Create an organized and healthy workspace to improve concentration.",
          "Maintain an optimal ambient temperature to stay alert.",
          "Consider your chronotype when planning tasks.",
          "Get full nights of sleep to be well-rested.",
          "Use natural stimulants like coffee or green tea.",
          "Meditate daily to improve concentration.",
          "Take regular breaks to avoid fatigue.",
          "Always seek to improve your skills to stay motivated.",
          "Measure your productivity to adjust strategies.",
          "See things through to avoid abandonment.",
          "Don't seek shortcuts to maintain quality.",
          "Don't get stuck; take a break when needed.",
          "Don't seek perfection to avoid procrastination.",
          "Schedule concentration periods in your calendar.",
          "Implement meeting-free days to focus on deep work.",
          "Focus on one task at a time to avoid dispersion.",
          "Listen to relaxing music to improve concentration.",
          "Make your work sessions more engaging to avoid boredom.",
          "Link your daily activities to your personal goals.",
          "Visualize your goals to stay motivated.",
          "Use project management tools to organize tasks.",
          "Create an environment conducive to creativity to stimulate innovation.",
          "Don't hesitate to say yes to opportunities that align with your goals.",
          "Take 20 minutes naps in the middle of your work day.",
        ],
      ),
      Category(
        name: "Positive Thinking and Gratitude",
        tips: [
          "Start each day with a positive affirmation to motivate yourself.",
          "Practice gratitude by writing three things you appreciate each day.",
          "Make a list of your accomplishments to remind yourself of your successes.",
          "Surround yourself with positive people to strengthen your well-being.",
          "Practice mindfulness to be present and appreciate each moment.",
          "Use motivational words to encourage yourself.",
          "Create a morning routine to start the day with optimism.",
          "Do visualization exercises to motivate yourself and achieve your goals.",
          "Write gratitude letters to those who have a positive impact in your life.",
          "Practice meditation to calm your mind and cultivate positivity.",
          "Do deep breathing exercises to reduce stress and improve your mood.",
          "Take breaks to relax and appreciate small moments.",
          "Create a relaxation space at home to recharge.",
          "Engage in creative activities to express your positivity.",
          "Practice dance to release positive energy.",
          "Use essential oils to create a positive atmosphere.",
          "Practice mindfulness during meals to appreciate flavors.",
          "Take care of your physical health to improve your mental well-being.",
          "Practice gratitude with family to strengthen bonds.",
          "Keep a gratitude journal to track your progress.",
          "Do compassion exercises to develop empathy.",
          "Use positive quotes to motivate yourself.",
          "Practice mindful walking to reconnect with nature.",
          "Do visualization exercises for success to motivate yourself.",
          "Drink calming teas to calm your mind.",
          "Practice progressive relaxation to relax your muscles.",
          "Create an evening routine to end the day positively.",
          "Practice gratitude before bed to appreciate each day.",
          "Use words of encouragement to motivate yourself.",
          "Practice mindfulness in relationships to improve communication.",
          "Do conscious breathing exercises to reduce stress.",
          "Take vacations to recharge and appreciate life.",
          "Create a creativity space to express your positivity.",
          "Practice gratitude for small moments to appreciate each instant.",
          "Practice guided meditation to guide yourself towards positivity.",
          "Create a support group to surround yourself with positive people.",
          "Practice gratitude for relationships to strengthen bonds.",
          "Use herbal remedies to improve your well-being.",
          "Practice gratitude in nature to reconnect.",
          "Do visualization exercises for inner peace to calm yourself.",
          "Keep a wellness journal to track your progress.",
          "Do deep breathing exercises before bed to improve sleep.",
          "Use motivational words for success to encourage yourself.",
          "Practice mindfulness for creativity to stimulate innovation.",
          "Practice gratitude for opportunities to appreciate each chance.",
          "Create an outdoor relaxation space to recharge.",
          "Show compassion for others to develop empathy.",
          "Practice gratitude for every moment to appreciate life.",
        ],
      ),
      Category(
        name: "Mindfulness",
        tips: [
          "Breathe in for 4, out for 6.",
          "Notice 5 things you can see.",
          "Feel your feet on the ground.",
          "Listen to the sounds around you.",
          "Close your eyes for 10 sec.",
          "Stretch your arms up high.",
          "Say 'I am here' to yourself.",
          "Roll your shoulders gently.",
          "Picture a calm lake today.",
          "Hum a soft tune quietly.",
          "Ask: 'What's here right now?'",
          "Rest your hands in your lap.",
          "Count 5 slow exhales.",
          "Let thoughts drift like clouds.",
          "Smell something pleasant.",
          "Tell yourself: 'I'm at peace.'",
          "Focus on a single sound.",
          "Relax your jaw right now.",
          "Sit still for 30 seconds.",
          "Imagine a warm light inside.",
          "Drop your shoulders down.",
          "Breathe into your belly.",
          "Notice colors around you.",
          "Say 'Calm' with each breath.",
          "Feel your heartbeat slow.",
          "Rub your hands for warmth.",
          "Think of a quiet moment.",
          "Whisper 'Relax' to yourself.",
          "Tap your fingers softly.",
          "Picture waves lapping gently.",
          "Close your eyes and listen.",
          "Feel the chair beneath you.",
          "Look up at the sky briefly.",
          "Repeat: 'This moment is enough.'",
          "Sip a warm tea and savor the taste.",
          "Smile softly to unwind.",
          "Watch a leaf or cloud move.",
          "Shift focus to your breath.",
          "Imagine tension melting off.",
          "Press your palms together.",
          "Say 'Be here' and settle in.",
          "Feel the air as you breathe.",
          "Think of a soothing color.",
          "Wiggle your toes slowly.",
        ],
      ),
      Category(
        name: "Healthy Habits and Routines",
        tips: [
          "Put your phone on airplane mode at night to reduce distractions.",
          "Take a daily walk to improve your physical health.",
          "Practice 15 minutes of yoga each morning to relax.",
          "Keep a gratitude journal to appreciate each day.",
          "Drink herbal tea after meals to relax.",
          "Prepare your meals in advance to eat healthier.",
          "Eat a balanced breakfast to start the day well.",
          "Do gymnastics every day to strengthen your body.",
          "Consume protein based on your needs to support your health.",
          "Replace saturated fats with healthier fats to improve your diet.",
          "Meditate for 5 minutes after lunch to reduce stress.",
          "Stretch regularly to avoid muscle tension.",
          "Eat an apple every day to include fruits in your diet.",
          "Walk for 10 minutes daily while maintaining good posture to stay active.",
          "Take 5 minutes to do nothing and relax.",
          "Have half a plate of fruits and vegetables at lunch for a balanced diet.",
          "Add a new food to your shopping list each month to vary your diet.",
          "Drink 1.5 liters of water per day to stay hydrated.",
          "Smile voluntarily every day to improve your mood.",
          "Check your emails only 2-3 times a day to avoid distractions.",
          "Don't sleep with your phone to improve sleep quality. Leave it in another room.",
          "Buy an alarm clock instead of relying on your smartphone. And leave the phone in another room.",
          "Keep your workspace tidy to reduce stress.",
          "Engage in some form of exercise daily, even if it's just 20 minutes of walking to stay active.",
          "Create a vision board to stay motivated and focused on your goals.",
          "Learn to say no to save your time and energy.",
          "Take the stairs instead of the elevator to move more.",
          "Travel by bike or on foot for short trips.",
          "Do muscle strengthening exercises at home to improve your strength.",
          "Reduce sedentary time by taking breaks to walk.",
          "Prepare your exercise equipment in advance to facilitate your routine.",
          "Park your car far from the entrance to walk a bit more.",
          "Take a dance class for fun to release energy.",
          "Join a team sport to release energy, stay active and learn team play.",
          "Try a new activity each week to enrich yourself.",
          "Increase your vegetable intake to improve your health.",
          "Drink 6 to 10 glasses of water per day to stay hydrated.",
          "Practice relaxation techniques regularly to reduce stress.",
          "Choose a physical activity you enjoy to stay motivated.",
          "Aim for 150 minutes of physical activity per week to maintain good health.",
          "Establish a consistent sleep routine to improve sleep quality.",
          "Incorporate stretching into your day to maintain flexibility.",
          "Take cold showers to stimulate circulation.",
          "Read an enriching book each day to cultivate yourself.",
          "Discover a new neighborhood each week to avoid monotony.",
          "Practice mindful eating to improve your relationship with food.",
          "Go for a morning or evening walk to recharge.",
          "Ensure you stay hydrated throughout the day to maintain optimal hydration levels.",
          "Take a 20 min nap in the middle of the day if you feel it difficult to focus.",
          "Avoid eating processed foods or eating too much in the middle of the day. This way you avoid 'food coma' and productivity crash.",
          "Start your day with gymnastics and stretching, make it a habit. This will help awaken your body and feel sharp.",
          "Go to bed earlier to wake up earlier. You'll get much more done.",
          "Avoid drinking too much coffee. It's bad for blood pressure. Take a nap if you need to recharge.",
          "Go for a hot steam bath (hammam or sauna). It stimulates your immune system and blood flow.",
        ],
      ),
      Category(
        name: "Goal Setting and Achievement",
        tips: [
          "Use the SMART method to define specific, measurable, achievable, realistic, and time-bound goals.",
          "Set clear and precise goals to avoid ambiguity.",
          "Define measurement indicators to evaluate success.",
          "Ensure your goals are achievable to maintain motivation.",
          "Align your goals with your values to stay consistent.",
          "Create a calendar to prioritize goals and set deadlines.",
          "At work communicate your goals to your team to ensure understanding and engagement.",
          "Break down large goals into smaller ones to avoid spreading yourself too thin.",
          "Use dashboards to track progress.",
          "Celebrate your achievements to reinforce motivation.",
          "Learn from failures to adjust your strategies.",
          "Be flexible to adapt your goals to changes.",
          "Set both short-term and long-term goals to maintain a global vision.",
          "Use project management tools to organize tasks.",
          "Regularly review your goals to adjust your strategy.",
          "Create a detailed action plan for each goal.",
          "Identify potential obstacles to anticipate challenges.",
          "Mobilize necessary resources to support your goals.",
          "Be patient and persistent in the face of difficulties.",
          "Be creative to find innovative solutions.",
          "Use concrete examples to illustrate your goals.",
          "Create an environment conducive to success.",
          "Encourage collaboration to achieve common goals.",
          "Set motivating goals to stimulate engagement.",
          "At work, use rewards to motivate the team.",
          "Conduct regular assessments to evaluate progress.",
          "Be open to feedback to improve your strategies.",
          "Create a tracking system to measure results.",
          "Use data to make informed decisions.",
          "Set ambitious but achievable goals to stimulate growth.",
          "Create a contingency plan for unexpected events.",
          "Be adaptable to adjust your goals to changes.",
          "Use communication tools to maintain engagement.",
          "Create a supportive environment to encourage team members.",
          "Engage in reflection exercises to improve your strategy.",
          "Use success models to inspire your goals.",
          "Set goals aligned with your vision to maintain a clear direction.",
          "Create a reward system for achievements.",
          "Conduct risk analyses to anticipate potential challenges.",
          "Use time management tools to optimize productivity.",
          "Create a development plan to continuously improve your skills.",
          "Engage in visualization exercises to motivate yourself.",
          "Use motivational quotes to maintain engagement.",
          "Create a sharing space to discuss progress.",
          "Set goals for each area of your life to maintain balance.",
          "Use tracking apps to monitor progress.",
          "Conduct annual assessments to evaluate accomplishments.",
          "Create a mentorship system to support team members.",
          "Use success examples to inspire your team.",
          "Celebrate each milestone to maintain motivation and satisfaction.",
        ],
      ),
      Category(
        name: "Emotional Regulation",
        tips: [
          "Take a few minutes each day to practice conscious breathing.",
          "Identify your emotions to better understand them.",
          "Express your emotions in an appropriate manner.",
          "Use humor to lighten stressful situations.",
          "Practice meditation to strengthen your mindfulness.",
          "Keep an emotional journal to track your feelings.",
          "Understand the origin of your emotions to manage them better.",
          "Ask for help from trusted individuals.",
          "Learn to accept your emotions without judgment.",
          "Practice muscle relaxation to calm your nervous system.",
          "Engage in exercise to release physical tension.",
          "Use visualization to relax.",
          "Take time to recharge in nature.",
          "Learn to recognize your body's signals.",
          "Practice gratitude to balance your emotions.",
          "Use positive affirmations to boost your confidence.",
          "Learn to say no without guilt.",
          "Practice mindfulness in your daily activities.",
          "Take regular breaks to calm down.",
          "Understand that your emotions are temporary.",
          "Trust your intuition to make decisions.",
          "Learn to manage your expectations to reduce stress.",
          "Practice self-compassion.",
          "Use assertive communication techniques.",
          "Learn to put difficult situations into perspective.",
          "Take care of your sleep to regulate your emotions.",
          "Engage in creative activities to express your emotions.",
          "Learn to forgive yourself and let go of the past.",
          "Use reappraisal to transform negative emotions.",
          "Practice problem-solving to reduce stress.",
          "Learn to focus on the present.",
          "Use social support to feel less alone.",
          "Practice patience and understanding toward yourself.",
          "Learn to recognize your emotional limits.",
          "Use stress management techniques like walking.",
          "Practice mindfulness in social interactions.",
          "Learn to express your needs clearly.",
          "Use books to learn how to manage your emotions.",
          "Practice gratitude daily.",
          "Learn to release negative thoughts.",
          "Use mindfulness exercises to calm down.",
          "Practice compassion toward others.",
          "Learn to manage your emotions in professional situations.",
          "Use breathing techniques to calm your nervous system.",
          "Learn to focus on the positive aspects of your life.",
          "Use affirmations to boost your self-confidence.",
          "Practice mindfulness in your relationships.",
          "Learn to forgive yourself and move on.",
        ],
      ),
      Category(
        name: "CBT-Inspired Tips",
        tips: [
          "Identify your automatic thoughts to understand your emotions.",
          "Practice cognitive restructuring to modify negative thoughts.",
          "Learn to recognize cognitive distortions to improve your perception.",
          "Practice relaxation to reduce stress and anxiety.",
          "Do deep breathing exercises to calm your mind.",
          "Use gradual exposure to overcome phobias.",
          "Develop self-assertion to improve your relationships.",
          "Learn to manage anger by identifying its triggers.",
          "Practice mindfulness to be more present.",
          "Identify your cognitive patterns to modify them.",
          "Learn to say no without guilt.",
          "Do visualization exercises to motivate yourself.",
          "Keep a thought journal to track your progress.",
          "Practice meditation to improve your concentration.",
          "Use positive affirmations to boost your confidence.",
          "Learn to express your emotions constructively.",
          "Do problem-solving exercises to improve your adaptability.",
          "Practice gratitude to appreciate each day.",
          "Identify catastrophic thoughts to restructure them.",
          "Use assertive communication techniques to improve your relationships.",
          "Create an action plan to overcome obstacles.",
          "Practice mindfulness during meals to appreciate flavors.",
          "Practice progressive relaxation to relax your muscles.",
          "Learn to manage conflicts constructively.",
          "Use time management tools to optimize productivity.",
          "Create a relaxation space to recharge.",
          "Do alternate breathing exercises to balance your energy.",
          "Practice guided meditation to guide yourself towards relaxation.",
          "Use positive quotes to motivate yourself.",
          "Learn to recognize your emotions to manage them better.",
          "Keep a wellness journal to track your progress.",
          "Practice mindfulness in relationships to improve communication.",
          "Learn to develop empathy to improve your relationships.",
          "Do visualization exercises for success to motivate yourself.",
          "Practice mindfulness in every moment to stay present.",
          "Learn to manage intense emotions using gradual exposure.",
          "Create a sharing space to discuss your emotions.",
          "Do gratitude exercises for small moments to appreciate each instant.",
          "Create a support group to surround yourself with positive people.",
          "Learn to develop a positive attitude to face challenges.",
          "Practice mindfulness in nature to recharge.",
        ],
      ),
    ];
  }

  // Helper methods for easy access
  static List<String> getCategoryNames() {
    return getAllCategories().map((category) => category.name).toList();
  }

  static Category? getCategoryByName(String name) {
    try {
      return getAllCategories().firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  static List<String> getTipsByCategory(String categoryName) {
    final category = getCategoryByName(categoryName);
    return category?.tips ?? [];
  }

  static int getTotalTipsCount() {
    return getAllCategories()
        .map((category) => category.tips.length)
        .reduce((a, b) => a + b);
  }

  static String getRandomTip() {
    final allCategories = getAllCategories();
    final randomCategory = (allCategories..shuffle()).first;
    final randomTip = (randomCategory.tips..shuffle()).first;
    return randomTip;
  }

  // Additional helper methods for the new categories
  static List<Category> getWellnessCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Healthy Habits and Routines",
      "Emotional Regulation",
      "Stress Management",
      "Mindfulness"
    ].contains(category.name)).toList();
  }

  static List<Category> getPerformanceCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Productivity and Focus",
      "Goal Setting and Achievement",
      "Cognitive Behavioral Techniques"
    ].contains(category.name)).toList();
  }

  static List<Category> getSocialCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Social Connections and Relationships",
      "Positive Thinking and Gratitude"
    ].contains(category.name)).toList();
  }
}