

import 'TipsData.dart';

class TipDataFR {
  static List<Category> getAllCategories() {
    return [
      Category(
        name: "Gestion du stress",
        tips: [
          "Pratique la respiration abdominale pour calmer ton système nerveux.",
          "Fais de l'exercice régulièrement pour libérer de l'endorphine.",
          "Fais de la méditation pour réduire ton stress et améliorer ta concentration.",
          "Écoute de la musique apaisante pour détendre ton esprit.",
          "Maintient une alimentation saine et équilibrée pour maintenir ton énergie.",
          "Dort suffisamment pour aider ton corps à se régénérer.",
          "Pratique la pleine conscience pour vivre dans le présent.",
          "Apprends à dire non sans culpabilité pour réduire la pression des autres.",
          "Pratique la relaxation dynamique pour libérer tes tensions musculaires.",
          "Identifie les sources de ton stress pour mieux les gérer.",
          "Utilise des affirmations positives pour renforcer ta confiance.",
          "Prends des pauses régulières pour te ressourcer.",
          "Fais confiance à ton intuition pour prendre des décisions.",
          "Apprends à relativiser les situations difficiles.",
          "Pratique la cohérence cardiaque pour réguler ton rythme cardiaque.",
          "Utilise des techniques de visualisation pour te motiver.",
          "Entoure-toi de personnes positives pour réduire ton stress.",
          "Pratique la bienveillance envers toi-même et les autres.",
          "Apprends à gérer tes attentes pour réduire ton stress.",
          "Utilise des livres pour apprendre à gérer ton stress.",
          "Pratique la gratitude chaque jour pour équilibrer tes émotions.",
          "Apprends à te libérer des pensées négatives.",
          "Utilise des exercices de pleine conscience pour te calmer.",
          "Apprends à te concentrer sur le présent.",
          "Pratique la relaxation musculaire progressive pour détendre ton corps.",
          "Apprends à exprimer tes besoins de manière claire.",
          "Planifie tes tâches pour mieux gérer ton temps.",
          "Apprends à te pardonner et à passer à autre chose.",
          "Utilise des techniques de respiration dynamisante pour te motiver.",
          "Pratique la méditation guidée pour te détendre.",
          "Apprends à te concentrer sur les aspects positifs de ta vie.",
          "Utilise des affirmations pour renforcer ta confiance en toi.",
          "Pratique la pleine conscience dans tes relations.",
          "Apprends à gérer tes émotions en situation professionnelle.",
          "Utilise des techniques de respiration pour calmer ton système nerveux.",
          "Pratique la méthode des 4A : abstiens-toi, ajuste, accepte et adapte.",
          "Apprends à te libérer des distractions pour te concentrer.",
          "Pratique la bienveillance envers les autres.",
          "Apprends à gérer tes limites émotionnelles.",
          "Utilise des techniques de gestion du stress comme la marche.",
          "Pratique la pleine conscience dans tes interactions sociales.",
          "Apprends à exprimer tes émotions de manière appropriée.",
          "Pratique la gratitude pour équilibrer tes émotions.",
          "Apprends à te pardonner et à te libérer du passé."
        ]
      ),
      Category(
        name: "Définition d'objectifs et réalisations",
        tips: [
          "Utilise la méthode SMART pour définir des objectifs spécifiques, mesurables, atteignables, réalistes et temporellement définis.",
          "Fixe des objectifs clairs et précis pour éviter les ambiguïtés.",
          "Définis des indicateurs de mesure pour évaluer la réussite de tes objectifs.",
          "Assure-toi que tes objectifs sont réalisables pour maintenir ta motivation.",
          "Aligne tes objectifs avec tes valeurs pour rester cohérent.",
          "Crée un calendrier pour prioriser tes objectifs et fixer des échéances.",
          "Communique tes objectifs à ton équipe pour assurer la compréhension et l'engagement.",
          "Fais des mini-objectifs pour éviter de t'éparpiller.",
          "Utilise des tableaux de bord pour suivre tes progrès.",
          "Célèbre tes réalisations pour renforcer ta motivation.",
          "Apprends des échecs pour ajuster tes stratégies.",
          "Sois flexible pour adapter tes objectifs aux changements.",
          "Fixe des objectifs à court et long terme pour maintenir une vision globale.",
          "Utilise des outils de gestion de projet pour organiser tes tâches.",
          "Fais des révisions régulières de tes objectifs pour ajuster ta stratégie.",
          "Crée un plan d'action détaillé pour chaque objectif.",
          "Identifie les obstacles potentiels pour anticiper les défis.",
          "Mobilise des ressources nécessaires pour soutenir tes objectifs.",
          "Sois patient et persévérant face aux difficultés.",
          "Fais preuve de créativité pour trouver des solutions innovantes.",
          "Utilise des exemples concrets pour illustrer tes objectifs.",
          "Crée un environnement propice pour favoriser ta réussite.",
          "Encourage la collaboration pour atteindre des objectifs communs.",
          "Fixe des objectifs motivants pour stimuler ton engagement.",
          "Utilise des récompenses pour motiver ton équipe.",
          "Fais des bilans réguliers pour évaluer tes progrès.",
          "Sois ouvert aux critiques pour améliorer tes stratégies.",
          "Crée un système de suivi pour mesurer tes résultats.",
          "Utilise des données pour prendre des décisions éclairées.",
          "Fixe des objectifs ambitieux mais réalisables pour stimuler ta croissance.",
          "Crée un plan de contingence pour les imprévus.",
          "Fais preuve d'adaptabilité pour ajuster tes objectifs aux changements.",
          "Utilise des outils de communication pour maintenir l'engagement.",
          "Crée un environnement de soutien pour encourager les membres de ton équipe.",
          "Fais des exercices de réflexion pour améliorer ta stratégie.",
          "Utilise des modèles de réussite pour inspirer tes objectifs.",
          "Fixe des objectifs alignés avec ta vision pour maintenir une direction claire.",
          "Crée un système de récompense pour tes réalisations.",
          "Fais des analyses de risques pour anticiper les défis potentiels.",
          "Utilise des outils de gestion du temps pour optimiser ta productivité.",
          "Crée un plan de développement pour améliorer continuellement tes compétences.",
          "Fais des exercices de visualisation pour te motiver.",
          "Utilise des citations motivantes pour maintenir ton engagement.",
          "Crée un espace de partage pour discuter de tes progrès.",
          "Fixe des objectifs pour chaque domaine de ta vie pour maintenir un équilibre.",
          "Utilise des applications de suivi pour suivre tes progrès.",
          "Fais des bilans annuels pour évaluer tes réalisations.",
          "Crée un système de mentorat pour soutenir les membres de ton équipe.",
          "Utilise des exemples de réussite pour inspirer ton équipe.",
          "Célèbre chaque étape pour maintenir ta motivation et ta satisfaction."
        ]
      ),
      Category(
        name: "Résilience",
        tips: [
          "Reconnais tes émotions pour mieux les gérer.",
          "Pratique la pleine conscience pour rester présent.",
          "Fixe des objectifs réalistes pour maintenir ta motivation.",
          "Crée un réseau de soutien pour t'entourer de personnes positives.",
          "Apprends à dire non pour économiser ton temps et ton énergie.",
          "Pratique la gratitude pour apprécier chaque jour.",
          "Fais des exercices de respiration profonde pour calmer ton esprit.",
          "Prends soin de ta santé physique pour renforcer ta résilience.",
          "Développe une attitude positive pour affronter les défis.",
          "Apprends des expériences passées pour améliorer tes stratégies.",
          "Crée un espace de détente pour te ressourcer.",
          "Fais des activités créatives pour exprimer tes émotions.",
          "Utilise des techniques de relaxation pour réduire le stress.",
          "Pratique la méditation pour améliorer ta concentration.",
          "Fixe des mini-objectifs pour progresser étape par étape.",
          "Reconnais tes forces pour renforcer ta confiance.",
          "Crée un journal de gratitude pour apprécier chaque jour.",
          "Prends des pauses régulières pour éviter la fatigue.",
          "Utilise des mots de motivation pour t'encourager.",
          "Crée un plan d'action pour surmonter tes obstacles.",
          "Fais des exercices de visualisation pour te motiver.",
          "Pratique la compassion envers toi-même pour accepter tes erreurs.",
          "Entoure-toi de personnes positives pour renforcer ton bien-être.",
          "Apprends à gérer les conflits pour maintenir des relations saines.",
          "Crée un espace de partage pour discuter de tes émotions.",
          "Fais des exercices de renforcement musculaire pour améliorer ta santé physique.",
          "Pratique la marche consciente pour te reconnecter avec la nature.",
          "Fixe des objectifs à long terme pour maintenir une vision globale.",
          "Crée un rituel du matin pour commencer la journée positivement.",
          "Fais des exercices de respiration alternée pour équilibrer ton énergie.",
          "Pratique la gratitude envers tes proches pour renforcer les liens.",
          "Utilise des huiles essentielles pour créer une ambiance relaxante.",
          "Crée un espace de créativité pour exprimer tes idées.",
          "Récompense toi pour célébrer tes réalisations.",
          "Utilise des citations positives pour t'encourager.",
          "Crée un journal de bien-être pour suivre tes progrès.",
          "Fais des exercices de respiration consciente avant de dormir pour améliorer ton sommeil.",
          "Pratique la pleine conscience dans tes relations pour améliorer la communication.",
          "Utilise des outils de gestion du temps pour optimiser ta productivité.",
          "Crée un espace de détente extérieur pour te ressourcer.",
          "Fais des exercices de gratitude pour les petits moments pour apprécier chaque instant.",
          "Utilise des plantes médicinales pour soutenir ton système immunitaire.",
          "Pratique la pleine conscience dans chaque instant pour rester présent et résilient.",
          "Crée une routine matinale pour bien commencer la journée. Par exemple, fais de la gymnastique ou apprends une nouvelle compétence."
        ]
      ),
      Category(
        name: "Productivité et concentration",
        tips: [
          "Planifie tes journées pour rester concentré sur tes objectifs.",
          "Aligne tes tâches avec tes objectifs à long terme.",
          "Prépare-toi la veille pour le lendemain.",
          "Découpe tes gros projets en petites tâches gérables.",
          "Évite le multitâches pour maintenir la concentration.",
          "Adopte le Deep Work pour travailler sans distractions.",
          "Autorise le chaos parfois pour stimuler la créativité.",
          "Élimine les distractions pour améliorer la productivité.",
          "Rédige une charte d'attention pour te rappeler tes priorités.",
          "Respecte la règle des 2 min pour terminer les petites tâches.",
          "Délègue quand c'est nécessaire pour libérer du temps.",
          "Communique efficacement avec ton équipe.",
          "Suis la règle des 10 min pour prendre des pauses régulières.",
          "Batche tes tâches pour optimiser ton temps.",
          "Élimine les tâches non essentielles.",
          "Dis non plus souvent pour gagner ton temps.",
          "Crée des journées à thème pour organiser ta semaine.",
          "Sois intentionnel dans tes actions quotidiennes.",
          "Optimise tes temps morts pour apprendre ou te détendre.",
          "Ne garde pas plus de 10 onglets ouverts simultanément.",
          "Crée un espace de travail organisé et sain pour améliorer la concentration.",
          "Garde une température ambiante optimale pour rester concentré.",
          "Tiens compte de ton rythme circadien pour planifier tes tâches.",
          "Fais des nuits complètes pour être bien reposé.",
          "Prends des stimulants naturels comme le café ou le thé vert.",
          "Médite tous les jours pour améliorer ta concentration.",
          "Accorde-toi des pauses régulières pour éviter la fatigue.",
          "Cherche toujours à monter en compétence pour rester motivé.",
          "Mesure ta productivité pour ajuster tes stratégies.",
          "Va au bout des choses et n'abandonne pas.",
          "Ne cherche pas à prendre des raccourcis - priorité à la qualité.",
          "Ne t'acharne pas lorsque tu es bloqué ; fais une pause.",
          "Ne cherche pas la perfection pour éviter la procrastination.",
          "Utilise le chronomètre de l'appli pour travailler en cycles.",
          "Planifie des périodes de concentration dans ton calendrier.",
          "Instaure des journées sans réunion pour ne pas être distrait.",
          "Focalise-toi sur une tâche à la fois pour éviter la dispersion.",
          "Écoute de la musique apaisante pour améliorer ta concentration.",
          "Associe tes activités quotidiennes aux objectifs de l'entreprise.",
          "Visualise tes objectifs pour rester motivé.",
          "Utilise des outils de gestion de projet pour organiser tes tâches.",
          "Crée un environnement propice à la créativité pour stimuler l'innovation.",
          "N'hésite pas à dire oui aux opportunités qui correspondent à tes objectifs.",
          "Fais une sieste de 20 minutes dans ta journée."
        ]
      ),
      Category(
        name: "Pensées positives et gratitude",
        tips: [
          "Commence chaque jour avec une affirmation positive pour te motiver.",
          "Pratique la gratitude en écrivant trois choses que tu apprécies chaque jour.",
          "Fais une liste de tes réalisations pour te rappeler tes succès.",
          "Entoure-toi de personnes positives pour renforcer ton bien-être.",
          "Pratique la pleine conscience pour être présent et apprécier chaque instant.",
          "Utilise des mots de motivation pour t'encourager.",
          "Crée un rituel du matin pour commencer la journée avec optimisme.",
          "Fais des exercices de visualisation pour te motiver et atteindre tes objectifs.",
          "Écris des lettres de gratitude à ceux qui ont un impact positif dans ta vie.",
          "Pratique la méditation pour calmer ton esprit et cultiver la positivité.",
          "Fais des exercices de respiration profonde pour réduire le stress et améliorer ton humeur.",
          "Prends des pauses pour te détendre et apprécier les petits moments.",
          "Crée un espace de détente chez toi pour te ressourcer.",
          "Fais des activités créatives pour exprimer ta positivité.",
          "Pratique la danse pour libérer ton énergie positive.",
          "Utilise des huiles essentielles pour créer une ambiance positive.",
          "Fais des exercices de pleine conscience pendant les repas pour apprécier les saveurs.",
          "Prends soin de ta santé physique pour améliorer ton bien-être mental.",
          "Pratique la gratitude en famille pour renforcer les liens.",
          "Crée un journal de gratitude pour suivre tes progrès.",
          "Fais des exercices de compassion pour développer l'empathie.",
          "Utilise des citations positives pour te motiver.",
          "Pratique la marche consciente pour te reconnecter avec la nature.",
          "Fais des exercices de visualisation pour la réussite pour te motiver.",
          "Bois des tisanes relaxantes pour calmer ton esprit.",
          "Pratique la relaxation progressive pour détendre tes muscles.",
          "Crée un rituel du soir pour terminer la journée positivement.",
          "Fais des exercices de gratitude avant de dormir pour apprécier chaque jour.",
          "Utilise des mots d'encouragement pour te motiver.",
          "Pratique la pleine conscience dans tes relations pour améliorer la communication.",
          "Fais des exercices de respiration consciente pour réduire le stress.",
          "Prends des vacances pour te ressourcer et apprécier la vie.",
          "Crée un espace de créativité pour exprimer ta positivité.",
          "Fais des exercices de gratitude pour les petits moments pour apprécier chaque instant.",
          "Utilise des applications de motivation pour t'encourager.",
          "Pratique la méditation guidée pour te guider vers la positivité.",
          "Crée un groupe de soutien pour t'entourer de personnes positives.",
          "Utilise des plantes médicinales pour améliorer ton bien-être.",
          "Pratique la gratitude dans la nature pour te reconnecter.",
          "Fais des exercices de visualisation pour la paix intérieure pour te calmer.",
          "Crée un journal de bien-être pour suivre tes progrès.",
          "Fais des exercices de respiration profonde avant de dormir pour améliorer ton sommeil.",
          "Utilise des mots de motivation pour la réussite pour t'encourager.",
          "Pratique la pleine conscience pour la créativité pour stimuler l'innovation.",
          "Pratique la gratitude envers chaque opportunité pour apprécier chaque chance.",
          "Crée un espace de détente extérieur pour te ressourcer.",
          "Fais preuve de compassion pour les autres afin de développer l'empathie.",
          "Pratique la gratitude à chaque instant pour apprécier la vie et les choses simples."
        ]
      ),
      Category(
        name: "Pleine conscience",
        tips: [
          "Inspire pendant 4 secondes, expire pendant 6 secondes.",
          "Remarque 5 choses que tu peux voir.",
          "Sens tes pieds sur le sol.",
          "Écoute les sons qui t'entourent.",
          "Ferme les yeux pendant 10 secondes.",
          "Étire tes bras vers le haut.",
          "Dis à toi-même : « Je suis ici ».",
          "Roule doucement tes épaules.",
          "Imagine un lac calme avec le chant des oiseaux.",
          "Chante une mélodie douce en silence.",
          "Pose tes mains sur tes genoux et ressens la chaleur des mains.",
          "Compte 5 expirations lentes.",
          "Laisse tes pensées s'envoler comme des nuages.",
          "Prends quelque chose d'agréable au toucher.",
          "Dis à toi-même : « Je suis en paix ».",
          "Concentre-toi sur un son unique.",
          "Détends ta mâchoire maintenant.",
          "Reste assis sans bouger pendant 30 secondes.",
          "Imagine une lumière chaude à l'intérieur de toi.",
          "Laisse tomber tes épaules vers le bas.",
          "Remarque les couleurs autour de toi.",
          "Dis « Calme » à chaque respiration.",
          "Sens ton rythme cardiaque ralentir.",
          "Frotte tes mains pour les réchauffer.",
          "Pense à un moment calme.",
          "Chuchote « Détends-toi » à toi-même.",
          "Tapotte doucement tes doigts.",
          "Imagine des vagues se brisant doucement.",
          "Ferme les yeux et écoute.",
          "Sens la chaise sous toi.",
          "Lève les yeux vers le ciel.",
          "Répète : « Ce moment est parfait ».",
          "Bois un thé chaud et savoure son goût.",
          "Souris doucement pour te détendre.",
          "Regarde une feuille ou un nuage bouger.",
          "Déplace ton attention vers ta respiration.",
          "Imagine la tension fondre.",
          "Dirige ton attention sur l'air que tu inspire.",
          "Pense à une couleur apaisante.",
          "Remue lentement tes orteils."
        ]
      ),
      Category(
        name: "Habitudes saines et routines",
        tips: [
          "Mets ton téléphone en mode avion la nuit pour réduire les distractions.",
          "Fais une promenade quotidienne pour améliorer ta santé physique.",
          "Pratique 15 minutes de yoga chaque matin pour te détendre.",
          "Tiens un journal de gratitude pour apprécier chaque journée.",
          "Bois une tisane après les repas pour te relaxer.",
          "Prépare tes repas à l'avance pour manger plus sainement.",
          "Prends un petit-déjeuner équilibré pour bien commencer la journée.",
          "Fais de la gymnastique tous les jours pour renforcer ton corps.",
          "Consomme des protéines selon tes besoins pour soutenir ta santé.",
          "Remplace les graisses saturées par des graisses plus saines pour améliorer ton alimentation.",
          "Médite pendant 5 minutes après le déjeuner pour réduire le stress.",
          "Étire-toi régulièrement pour éviter les tensions musculaires.",
          "Mange une pomme chaque jour pour inclure des fruits dans ton alimentation.",
          "Marche 10 minutes par jour en maintenant une bonne posture pour rester actif.",
          "Prends 5 minutes pour ne rien faire et te détendre.",
          "Remplis la moitié de ton assiette de fruits et légumes au déjeuner pour une alimentation équilibrée.",
          "Ajoute un nouvel aliment à ta liste de courses chaque mois pour varier ton alimentation.",
          "Bois 1,5 litre d'eau par jour pour rester hydraté.",
          "Souris volontairement tous les jours pour améliorer ton humeur.",
          "Vérifie tes e-mails seulement 2 à 3 fois par jour pour éviter les distractions.",
          "Ne dors pas avec ton téléphone pour améliorer la qualité de ton sommeil. Laisse-le dans une autre pièce.",
          "Achète un réveil au lieu de compter sur ton smartphone. Et laisse le téléphone dans une autre pièce.",
          "Garde ton espace de travail rangé pour réduire le stress.",
          "Fais une forme d'exercice quotidien, même si ce n'est que 20 minutes de marche pour rester actif.",
          "Crée un tableau de vision pour rester motivé et concentré sur tes objectifs.",
          "Apprends à dire non pour économiser ton temps et ton énergie.",
          "Prends les escaliers au lieu de l'ascenseur pour bouger davantage.",
          "Déplace-toi à vélo ou à pied pour les courts trajets.",
          "Fais des exercices de renforcement musculaire à la maison pour améliorer ta force.",
          "Réduis le temps passé assis en prenant des pauses pour marcher.",
          "Prépare ton équipement d'exercice à l'avance pour faciliter ta routine.",
          "Gare ta voiture loin de l'entrée pour marcher un peu plus.",
          "Prends un cours de danse pour t'amuser et libérer de l'énergie.",
          "Rejoins un sport d'équipe pour libérer de l'énergie, rester actif et apprendre le travail d'équipe.",
          "Essaie une nouvelle activité chaque semaine pour t'enrichir.",
          "Augmente ta consommation de légumes pour améliorer ta santé.",
          "Bois entre 6 et 10 verres d'eau par jour pour rester hydraté.",
          "Pratique régulièrement des techniques de relaxation pour réduire le stress.",
          "Choisis une activité physique que tu aimes pour rester motivé.",
          "Vise 150 minutes d'activité physique par semaine pour maintenir une bonne santé.",
          "Établis une routine de sommeil régulière pour améliorer la qualité de ton sommeil.",
          "Intègre des étirements dans ta journée pour maintenir ta flexibilité.",
          "Prends des douches froides pour stimuler la circulation.",
          "Lis un livre enrichissant chaque jour pour te cultiver.",
          "Découvre un nouveau quartier chaque semaine pour éviter la monotonie.",
          "Pratique une alimentation consciente pour améliorer ta relation avec la nourriture.",
          "Fais une promenade le matin ou le soir pour te ressourcer.",
          "Assure-toi de rester hydraté tout au long de la journée pour maintenir un niveau d'hydratation optimal.",
          "Fais une sieste de 20 minutes en milieu de journée si tu as du mal à te concentrer.",
          "Évite de manger des aliments transformés ou trop copieux en milieu de journée. Ainsi, tu évites le « coma alimentaire » et la chute de productivité.",
          "Commence ta journée avec de la gymnastique et des étirements, fais-en une habitude. Cela aidera à réveiller ton corps et à te sentir alerte.",
          "Couche-toi plus tôt pour te lever plus tôt. Tu accompliras beaucoup plus.",
          "Évite de boire trop de café. C'est mauvais pour la tension artérielle. Fais une sieste si tu as besoin de te recharger.",
          "Prends un bain de vapeur chaud (hammam ou sauna). Ça stimule ton système immunitaire et ta circulation sanguine."
        ]
      ),
      Category(
        name: "Définition d'objectifs et réalisations",
        tips: [
          "Utilise la méthode SMART pour définir des objectifs spécifiques, mesurables, atteignables, réalistes et temporellement définis.",
          "Fixe des objectifs clairs et précis pour éviter les ambiguïtés.",
          "Définis des indicateurs de mesure pour évaluer la réussite de tes objectifs.",
          "Assure-toi que tes objectifs sont réalisables pour maintenir ta motivation.",
          "Aligne tes objectifs avec tes valeurs pour rester cohérent.",
          "Crée un calendrier pour prioriser tes objectifs et fixer des échéances.",
          "Communique tes objectifs à ton équipe pour assurer la compréhension et l'engagement.",
          "Fais des mini-objectifs pour éviter de t'éparpiller.",
          "Utilise des tableaux de bord pour suivre tes progrès.",
          "Célèbre tes réalisations pour renforcer ta motivation.",
          "Apprends des échecs pour ajuster tes stratégies.",
          "Sois flexible pour adapter tes objectifs aux changements.",
          "Fixe des objectifs à court et long terme pour maintenir une vision globale.",
          "Utilise des outils de gestion de projet pour organiser tes tâches.",
          "Fais des révisions régulières de tes objectifs pour ajuster ta stratégie.",
          "Crée un plan d'action détaillé pour chaque objectif.",
          "Identifie les obstacles potentiels pour anticiper les défis.",
          "Mobilise des ressources nécessaires pour soutenir tes objectifs.",
          "Sois patient et persévérant face aux difficultés.",
          "Fais preuve de créativité pour trouver des solutions innovantes.",
          "Utilise des exemples concrets pour illustrer tes objectifs.",
          "Crée un environnement propice pour favoriser ta réussite.",
          "Encourage la collaboration pour atteindre des objectifs communs.",
          "Fixe des objectifs motivants pour stimuler ton engagement.",
          "Utilise des récompenses pour motiver ton équipe.",
          "Fais des bilans réguliers pour évaluer tes progrès.",
          "Sois ouvert aux critiques pour améliorer tes stratégies.",
          "Crée un système de suivi pour mesurer tes résultats.",
          "Utilise des données pour prendre des décisions éclairées.",
          "Fixe des objectifs ambitieux mais réalisables pour stimuler ta croissance.",
          "Crée un plan de contingence pour les imprévus.",
          "Fais preuve d'adaptabilité pour ajuster tes objectifs aux changements.",
          "Utilise des outils de communication pour maintenir l'engagement.",
          "Crée un environnement de soutien pour encourager les membres de ton équipe.",
          "Fais des exercices de réflexion pour améliorer ta stratégie.",
          "Utilise des modèles de réussite pour inspirer tes objectifs.",
          "Fixe des objectifs alignés avec ta vision pour maintenir une direction claire.",
          "Crée un système de récompense pour tes réalisations.",
          "Fais des analyses de risques pour anticiper les défis potentiels.",
          "Utilise des outils de gestion du temps pour optimiser ta productivité.",
          "Crée un plan de développement pour améliorer continuellement tes compétences.",
          "Fais des exercices de visualisation pour te motiver.",
          "Utilise des citations motivantes pour maintenir ton engagement.",
          "Crée un espace de partage pour discuter de tes progrès.",
          "Fixe des objectifs pour chaque domaine de ta vie pour maintenir un équilibre.",
          "Utilise des applications de suivi pour suivre tes progrès.",
          "Fais des bilans annuels pour évaluer tes réalisations.",
          "Crée un système de mentorat pour soutenir les membres de ton équipe.",
          "Utilise des exemples de réussite pour inspirer ton équipe.",
          "Célèbre chaque étape pour maintenir ta motivation et ta satisfaction."
        ]
      ),
      Category(
        name: "Régulation émotionnelle",
        tips: [
          "Prends quelques minutes chaque jour pour pratiquer la respiration consciente.",
          "Identifie tes émotions pour mieux les comprendre.",
          "Exprime tes émotions de manière appropriée.",
          "Utilise l'humour pour alléger les situations stressantes.",
          "Pratique la méditation pour renforcer ta pleine conscience.",
          "Tiens un journal émotionnel pour suivre tes sentiments.",
          "Comprends l'origine de tes émotions pour mieux les gérer.",
          "Demande de l'aide à des personnes de confiance.",
          "Apprends à accepter tes émotions sans les juger.",
          "Pratique la relaxation musculaire pour calmer ton système nerveux.",
          "Fais de l'exercice pour libérer les tensions physiques.",
          "Utilise la visualisation pour te détendre.",
          "Prends du temps pour te ressourcer en nature.",
          "Apprends à reconnaître les signaux de ton corps.",
          "Pratique la gratitude pour équilibrer tes émotions.",
          "Utilise des affirmations positives pour renforcer ta confiance.",
          "Apprends à dire non sans culpabilité.",
          "Pratique la pleine conscience dans tes activités quotidiennes.",
          "Prends des pauses régulières pour te calmer.",
          "Comprends que tes émotions sont temporaires.",
          "Fais confiance à ton intuition pour prendre des décisions.",
          "Apprends à gérer tes attentes pour réduire le stress.",
          "Pratique la bienveillance envers toi-même.",
          "Utilise des techniques de communication assertive.",
          "Apprends à relativiser les situations difficiles.",
          "Prends soin de ton sommeil pour réguler tes émotions.",
          "Pratique des activités créatives pour exprimer tes émotions.",
          "Apprends à te pardonner et à te libérer du passé.",
          "Utilise la réévaluation pour transformer tes émotions négatives.",
          "Pratique la résolution de problèmes pour réduire le stress.",
          "Apprends à te concentrer sur le présent.",
          "Utilise le soutien social pour te sentir moins seul.",
          "Pratique la patience et la compréhension envers toi-même.",
          "Apprends à reconnaître tes limites émotionnelles.",
          "Utilise des techniques de gestion du stress comme la marche.",
          "Pratique la pleine conscience dans tes interactions sociales.",
          "Apprends à exprimer tes besoins de manière claire.",
          "Utilise des livres pour apprendre à gérer tes émotions.",
          "Pratique la gratitude chaque jour.",
          "Apprends à te libérer des pensées négatives.",
          "Utilise des exercices de pleine conscience pour te calmer.",
          "Pratique la bienveillance envers les autres.",
          "Apprends à gérer tes émotions en situation professionnelle.",
          "Utilise des techniques de respiration pour calmer ton système nerveux.",
          "Apprends à te concentrer sur les aspects positifs de la vie.",
          "Utilise des affirmations pour renforcer ta confiance en toi.",
          "Pratique la pleine conscience dans tes relations.",
          "Apprends à pardonner et à passer à autre chose."
        ]
      ),
      Category(
        name: "Conseils inspirés de la TCC",
        tips: [
          "Identifie tes pensées automatiques pour comprendre tes émotions.",
          "Pratique la restructuration cognitive pour modifier tes pensées négatives.",
          "Apprends à reconnaître les distorsions cognitives pour améliorer ta perception.",
          "Pratique la relaxation pour réduire ton stress et ton anxiété.",
          "Fais des exercices de respiration profonde pour calmer ton esprit.",
          "Utilise l'exposition graduée pour surmonter tes phobies.",
          "Développe l'affirmation de toi pour améliorer tes relations.",
          "Apprends à gérer ta colère en identifiant ses déclencheurs.",
          "Pratique la pleine conscience pour être plus présent.",
          "Identifie tes schémas cognitifs pour les modifier.",
          "Utilise des techniques de gestion du stress pour réduire ton anxiété.",
          "Apprends à dire non sans culpabilité.",
          "Fais des exercices de visualisation pour te motiver.",
          "Crée un journal de pensées pour suivre tes progrès.",
          "Pratique la méditation pour améliorer ta concentration.",
          "Utilise des affirmations positives pour renforcer ta confiance.",
          "Apprends à exprimer tes émotions de manière constructive.",
          "Fais des exercices de résolution de problèmes et de logique pour améliorer ton adaptabilité.",
          "Pratique la gratitude pour apprécier chaque jour.",
          "Identifie tes pensées catastrophiques pour les restructurer.",
          "Utilise des techniques de communication assertive pour améliorer tes relations.",
          "Crée un plan d'action pour surmonter tes obstacles.",
          "Fais des exercices de pleine conscience pendant les repas pour apprécier les saveurs.",
          "Pratique la relaxation progressive pour détendre tes muscles.",
          "Apprends à gérer les conflits de manière constructive.",
          "Utilise des outils de gestion du temps pour optimiser ta productivité, comme le chronomètre dans l'appli.",
          "Crée un espace de détente pour te ressourcer.",
          "Fais des exercices de respiration alternée pour équilibrer ton énergie.",
          "Pratique la méditation guidée pour te guider vers la relaxation.",
          "Utilise des citations positives pour te motiver.",
          "Apprends à reconnaître tes émotions pour mieux les gérer.",
          "Crée un journal de bien-être pour suivre tes progrès.",
          "Pratique la pleine conscience dans tes relations pour améliorer la communication.",
          "Apprends à développer l'empathie pour améliorer tes relations.",
          "Pratique la pleine conscience dans chaque instant pour rester présent.",
          "Apprends à gérer les émotions intenses en utilisant l'exposition graduée.",
          "Crée un espace de partage pour discuter de tes émotions.",
          "Fais des exercices de gratitude pour les petits moments pour apprécier chaque instant.",
          "Crée un groupe de soutien pour t'entourer de personnes positives.",
          "Apprends à développer une attitude positive pour affronter les défis.",
          "Fais des exercices de pleine conscience dans la nature pour te ressourcer."
        ]
      ),
    ];
  }

  // Helper methods for easy access
  static List<String> getCategoryNames() {
    return getAllCategories().map((category) => category.name).toList();
  }

  static Category? getCategoryByName(String name) {
    try {
      return getAllCategories().firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  static List<String> getTipsByCategory(String categoryName) {
    final category = getCategoryByName(categoryName);
    return category?.tips ?? [];
  }

  static int getTotalTipsCount() {
    return getAllCategories()
        .map((category) => category.tips.length)
        .reduce((a, b) => a + b);
  }

  static String getRandomTip() {
    final allCategories = getAllCategories();
    final randomCategory = (allCategories..shuffle()).first;
    final randomTip = (randomCategory.tips..shuffle()).first;
    return randomTip;
  }

  // Additional helper methods for the new categories
  static List<Category> getWellnessCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Healthy Habits and Routines",
      "Emotional Regulation",
      "Stress Management",
      "Mindfulness"
    ].contains(category.name)).toList();
  }

  static List<Category> getPerformanceCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Productivity and Focus",
      "Goal Setting and Achievement",
      "Cognitive Behavioral Techniques"
    ].contains(category.name)).toList();
  }

  static List<Category> getSocialCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Social Connections and Relationships",
      "Positive Thinking and Gratitude"
    ].contains(category.name)).toList();
  }
}