

import 'TipsData.dart';

class TipDataES {
  static List<Category> getAllCategories() {
    return [
      Category(
        name: "Manejo del Estrés",
        tips: [
          "Practica la respiración abdominal para calmar tu sistema nervioso.",
          "Haz ejercicio regularmente para liberar endorfinas.",
          "Medita para reducir tu estrés y mejorar tu concentración.",
          "Escucha música relajante para relajar tu mente.",
          "Mantén una dieta saludable y equilibrada para sostener tu energía.",
          "Duerme lo suficiente para ayudar a tu cuerpo a regenerarse.",
          "Practica la atención plena para vivir en el momento presente.",
          "Aprende a decir no sin culpa para reducir la presión de los demás.",
          "Practica la relajación dinámica para liberar la tensión muscular.",
          "Identifica las fuentes de tu estrés para gestionarlas mejor.",
          "Usa afirmaciones positivas para fortalecer tu confianza.",
          "Toma descansos regulares para recargarte.",
          "Confía en tu intuición para tomar decisiones.",
          "Aprende a poner las situaciones difíciles en perspectiva.",
          "Practica la coherencia cardíaca para regular tu ritmo cardíaco.",
          "Usa técnicas de visualización para motivarte.",
          "Rodéate de personas positivas para reducir tu estrés.",
          "Practica la amabilidad contigo mismo y con los demás.",
          "Aprende a manejar tus expectativas para reducir tu estrés.",
          "Usa libros para aprender a manejar tu estrés.",
          "Practica la gratitud cada día para equilibrar tus emociones.",
          "Aprende a liberarte de los pensamientos negativos.",
          "Usa ejercicios de atención plena para calmarte.",
          "Aprende a concentrarte en el presente.",
          "Practica la relajación muscular progresiva para relajar tu cuerpo.",
          "Aprende a expresar tus necesidades claramente.",
          "Planifica tus tareas para gestionar mejor tu tiempo.",
          "Aprende a perdonarte y seguir adelante.",
          "Usa técnicas de respiración energizante para motivarte.",
          "Practica la meditación guiada para relajarte.",
          "Aprende a enfocarte en los aspectos positivos de tu vida.",
          "Usa afirmaciones para aumentar tu confianza en ti mismo.",
          "Practica la atención plena en tus relaciones.",
          "Aprende a manejar tus emociones en situaciones profesionales.",
          "Usa técnicas de respiración para calmar tu sistema nervioso.",
          "Practica el método de las 4A: evita, altera, acepta y adapta.",
          "Aprende a liberarte de las distracciones para concentrarte.",
          "Practica la amabilidad hacia los demás.",
          "Aprende a manejar tus límites emocionales.",
          "Usa técnicas de manejo del estrés como caminar.",
          "Practica la atención plena en tus interacciones sociales.",
          "Aprende a expresar tus emociones de manera apropiada.",
          "Practica la gratitud para equilibrar tus emociones.",
          "Aprende a perdonarte y dejar ir el pasado."
        ],
      ),
      Category(
        name: "Conexiones Sociales y Relaciones",
        tips: [
          "Participa en actividades comunitarias para ampliar tu círculo social.",
          "Busca oportunidades para conocer personas que compartan tus intereses.",
          "Practica la escucha activa para mejorar la calidad de tus interacciones.",
          "Únete a un club o asociación para conocer gente nueva.",
          "Organiza encuentros sociales para fortalecer lazos con amigos y familia.",
          "Mantente en contacto con tus seres queridos regularmente.",
          "Muestra empatía para entender mejor a los demás.",
          "Sé auténtico en tus relaciones para construir vínculos fuertes.",
          "Aprende a decir \"no\" para gestionar mejor tu tiempo y energía.",
          "Practica la gratitud con las personas importantes en tu vida.",
          "Escucha sin juzgar para crear un espacio seguro de diálogo.",
          "Fomenta momentos de compartir con colegas para mejorar el ambiente laboral.",
          "Haz cumplidos sinceros para fortalecer conexiones.",
          "Participa en proyectos de voluntariado para conocer personas con tus valores.",
          "Muestra presencia en tus interacciones para demostrar interés.",
          "Usa palabras motivadoras para inspirar a otros.",
          "Crea espacios de discusión para facilitar el intercambio de ideas.",
          "Practica la atención plena para ser más consciente de los demás.",
          "Involúcrate en actividades grupales para fortalecer lazos sociales.",
          "Aprende a gestionar conflictos para mantener relaciones sanas.",
          "Sé paciente con los demás para mejorar la comunicación.",
          "Organiza cenas familiares para reforzar los vínculos.",
          "Respeta las diferencias de los demás.",
          "Establece rituales sociales para mantener contacto regular.",
          "Utiliza el humor para aligerar el ambiente.",
          "Practica meditación grupal para fortalecer conexiones.",
          "Haz ejercicios de compasión para desarrollar empatía.",
          "Mantente abierto a nuevas experiencias para enriquecer tus relaciones.",
          "Lleva un diario de gratitud para valorar tus vínculos personales.",
          "Haz regalos simbólicos para mostrar aprecio.",
          "Practica comunicación no violenta para resolver conflictos.",
          "Organiza salidas al aire libre para crear momentos de conexión.",
          "Usa herramientas digitales para mantener el contacto con seres queridos.",
          "Crea un espacio de relajación compartido para grupos.",
          "Realiza actividades creativas en equipo para estimular la innovación.",
          "Expresa gratitud hacia tus colegas para mejorar el ambiente de trabajo.",
          "Sé flexible para adaptarte a las necesidades de los demás.",
          "Crea oportunidades de mentoría para ayudar a otros a crecer.",
          "Organiza eventos culturales para enriquecer tus relaciones.",
          "Emplea palabras de aliento para motivar a tu círculo.",
          "Forma un grupo de apoyo para superar dificultades juntos.",
          "Practica actividades de bienestar en grupo para cuidar la salud mental.",
          "Guía meditaciones grupales para mejorar la concentración colectiva.",
          "Presta atención a las necesidades ajenas para profundizar las conexiones.",
          "Organiza encuentros gastronómicos para fortalecer lazos sociales.",
          "Haz visualizaciones guiadas para inspirar a otros.",
          "Crea un espacio de reconocimiento para valorar las contribuciones ajenas."
        ],
      ),
      Category(
        name: "Resiliencia",
        tips: [
          "Reconoce tus emociones para poder manejarlas mejor.",
          "Practica la atención plena para mantenerte presente.",
          "Establece metas realistas para conservar la motivación.",
          "Crea una red de apoyo para rodearte de personas positivas.",
          "Aprende a decir no para proteger tu tiempo y energía.",
          "Practica la gratitud para valorar cada día.",
          "Realiza ejercicios de respiración profunda para calmar la mente.",
          "Cuida tu salud física para fortalecer tu resiliencia.",
          "Desarrolla una actitud positiva para enfrentar desafíos.",
          "Aprende de experiencias pasadas para mejorar tus estrategias.",
          "Crea un espacio de relajación para recargar energías.",
          "Participa en actividades creativas para expresar emociones.",
          "Usa técnicas de relajación para reducir el estrés.",
          "Practica meditación para mejorar tu concentración.",
          "Establece mini-objetivos para avanzar paso a paso.",
          "Reconoce tus fortalezas para aumentar tu confianza.",
          "Mantén un diario de gratitud para apreciar cada día.",
          "Practica comer con atención plena para saborear los alimentos.",
          "Toma descansos regulares para evitar el agotamiento.",
          "Usa palabras motivadoras para animarte.",
          "Crea un plan de acción para superar obstáculos.",
          "Realiza ejercicios de visualización para motivarte.",
          "Practica la autocompasión para aceptar tus errores.",
          "Rodéate de personas positivas para mejorar tu bienestar.",
          "Aprende a gestionar conflictos para mantener relaciones sanas.",
          "Crea un espacio de diálogo para compartir emociones.",
          "Haz ejercicios de fortalecimiento muscular para mejorar tu salud física.",
          "Practica caminatas conscientes para poder conectarte de nuevo con la naturaleza.",
          "Establece metas a largo plazo para mantener una visión global.",
          "Crea una rutina matutina para empezar el día positivamente (como estirarte o aprender algo nuevo).",
          "Practica respiración alterna para equilibrar tu estado de ánimo.",
          "Muestra gratitud hacia tus seres queridos para fortalecer vínculos.",
          "Usa aceites esenciales para crear un ambiente relajante.",
          "Crea un espacio creativo para expresar tus ideas.",
          "Prémiate a ti mismo para celebrar tus logros.",
          "Visualiza el éxito para mantenerte motivado.",
          "Usa frases positivas para animarte.",
          "Lleva un diario de bienestar para registrar tu progreso.",
          "Practica respiración consciente antes de dormir para mejorar el sueño.",
          "Crea un espacio de relajación al aire libre para recargarte.",
          "Agradece los pequeños momentos para valorar cada instante.",
          "Forma un grupo de apoyo para rodearte de personas positivas.",
          "Practica la atención plena en cada momento para mantenerte presente y resiliente."
        ],
      ),
      Category(
        name: "Productividad y Concentración",
        tips: [
          "Planifica tus días para mantener el enfoque en tus objetivos.",
          "Alinea tus tareas con los objetivos a largo plazo.",
          "Prepárate para el día siguiente la noche anterior.",
          "Divide los grandes proyectos en tareas manejables.",
          "Evita la multitarea para mantener la concentración.",
          "Adopta el trabajo profundo (Deep Work) para trabajar sin distracciones.",
          "Permite el caos en ocasiones para estimular la creatividad.",
          "Elimina las distracciones para mejorar la productividad.",
          "Escribe una carta de atención para recordarte las prioridades.",
          "Sigue la regla de los 2 minutos para completar tareas pequeñas.",
          "Delegar cuando sea necesario para liberar tiempo.",
          "Comunícate eficazmente con tu equipo.",
          "Sigue la regla de los 10 minutos para tomar descansos regulares.",
          "Usa la técnica del sándwich para hacer las tareas más agradables.",
          "Agrupa tareas similares para optimizar el tiempo.",
          "Elimina las tareas no esenciales.",
          "Di no más a menudo para proteger tu tiempo.",
          "Automatiza tareas siguiendo la regla de tres.",
          "Crea días temáticos para organizar tu semana.",
          "Sé intencional en tus acciones diarias.",
          "Optimiza el tiempo libre para aprender o relajarte.",
          "No mantengas más de 10 pestañas abiertas simultáneamente.",
          "Crea un espacio de trabajo organizado y saludable para mejorar la concentración.",
          "Mantén una temperatura ambiental óptima para estar alerta.",
          "Considera tu cronotipo al planificar tareas.",
          "Duerme noches completas para estar bien descansado.",
          "Usa estimulantes naturales como café o té verde.",
          "Medita diariamente para mejorar la concentración.",
          "Toma descansos regulares para evitar la fatiga.",
          "Busca siempre mejorar tus habilidades para mantener la motivación.",
          "Mide tu productividad para ajustar estrategias.",
          "Lleva las cosas hasta el final para evitar abandonos.",
          "No busques atajos para mantener la calidad.",
          "No te quedes atascado; toma un descanso cuando sea necesario.",
          "No busques la perfección para evitar la procrastinación.",
          "Programa períodos de concentración en tu calendario.",
          "Implementa días sin reuniones para enfocarte en el trabajo profundo.",
          "Concéntrate en una tarea a la vez para evitar la dispersión.",
          "Escucha música relajante para mejorar la concentración.",
          "Haz tus sesiones de trabajo más atractivas para evitar el aburrimiento.",
          "Vincula tus actividades diarias con tus metas personales.",
          "Visualiza tus objetivos para mantener la motivación.",
          "Usa herramientas de gestión de proyectos para organizar tareas.",
          "Crea un ambiente propicio para la creatividad para estimular la innovación.",
          "No dudes en decir sí a oportunidades que se alineen con tus objetivos.",
          "Toma siestas de 20 minutos en medio de tu jornada laboral."
        ],
      ),
      Category(
        name: "Pensamiento Positivo y Gratitud",
        tips: [
          "Empieza cada día con una afirmación positiva para motivarte.",
          "Practica la gratitud escribiendo tres cosas que aprecias cada día.",
          "Haz una lista de tus logros para recordar tus éxitos.",
          "Rodéate de personas positivas para fortalecer tu bienestar.",
          "Practica la atención plena para estar presente y valorar cada momento.",
          "Usa palabras motivadoras para animarte.",
          "Crea una rutina matutina para empezar el día con optimismo.",
          "Haz ejercicios de visualización para motivarte y alcanzar tus metas.",
          "Escribe cartas de agradecimiento a quienes impactan positivamente en tu vida.",
          "Practica la meditación para calmar la mente y cultivar positividad.",
          "Realiza ejercicios de respiración profunda para reducir el estrés y mejorar tu estado de ánimo.",
          "Toma descansos para relajarte y apreciar los pequeños momentos.",
          "Crea un espacio de relajación en casa para recargar energías.",
          "Participa en actividades creativas para expresar tu positividad.",
          "Baila para liberar energía positiva.",
          "Usa aceites esenciales para crear un ambiente positivo.",
          "Practica la atención plena al comer para saborear los alimentos.",
          "Cuida tu salud física para mejorar tu bienestar mental.",
          "Practica la gratitud en familia para fortalecer vínculos.",
          "Lleva un diario de gratitud para registrar tu progreso.",
          "Haz ejercicios de compasión para desarrollar la empatía.",
          "Usa frases positivas para motivarte.",
          "Practica caminatas conscientes para conectarte de nuevo con la naturaleza.",
          "Visualiza el éxito para mantenerte motivado.",
          "Toma infusiones relajantes para calmar la mente.",
          "Practica la relajación progresiva para soltar tensiones musculares.",
          "Crea una rutina nocturna para terminar el día con positividad.",
          "Practica la gratitud antes de dormir para valorar cada día.",
          "Usa palabras de aliento para motivarte.",
          "Practica la atención plena en las relaciones para mejorar la comunicación.",
          "Realiza ejercicios de respiración consciente para reducir el estrés.",
          "Toma vacaciones para recargar energías y apreciar la vida.",
          "Crea un espacio creativo para expresar tu positividad.",
          "Practica la gratitud por los pequeños momentos para valorar cada instante.",
          "Haz meditaciones guiadas para encaminarte hacia la positividad.",
          "Crea un grupo de apoyo para rodearte de personas positivas.",
          "Practica la gratitud en tus relaciones para fortalecer vínculos.",
          "Usa remedios herbales para mejorar tu bienestar.",
          "Practica la gratitud en la naturaleza para volver a conectarte.",
          "Visualiza la paz interior para calmarte.",
          "Lleva un diario de bienestar para monitorear tu progreso.",
          "Haz respiraciones profundas antes de dormir para mejorar el sueño.",
          "Usa palabras motivadoras de éxito para inspirarte.",
          "Practica la atención plena para estimular la creatividad.",
          "Agradece las oportunidades para valorar cada posibilidad.",
          "Crea un espacio de relajación al aire libre para recargarte.",
          "Muestra compasión hacia los demás para cultivar empatía.",
          "Practica la gratitud en cada momento para apreciar la vida."
        ],
      ),
      Category(
        name: "Atención Plena",
        tips: [
          "Respira hondo durante 4 segundos, exhala por 6.",
          "Observa 5 cosas que puedas ver.",
          "Siente tus pies en el suelo.",
          "Escucha los sonidos a tu alrededor.",
          "Cierra los ojos por 10 segundos.",
          "Estira los brazos hacia arriba.",
          "Di 'Estoy aquí' para ti mismo.",
          "Gira los hombros suavemente.",
          "Imagina un lago tranquilo hoy.",
          "Tararea una melodía suave.",
          "Pregunta: '¿Qué hay aquí ahora?'",
          "Descansa tus manos en tu regazo.",
          "Cuenta 5 exhalaciones lentas.",
          "Deja que los pensamientos floten como nubes.",
          "Huele algo agradable.",
          "Dite a ti mismo: 'Estoy en paz.'",
          "Concéntrate en un solo sonido.",
          "Relaja tu mandíbula ahora mismo.",
          "Siéntate quieto por 30 segundos.",
          "Imagina una luz cálida dentro de ti.",
          "Baja los hombros.",
          "Respira hacia tu vientre.",
          "Observa los colores a tu alrededor.",
          "Di 'Calma' con cada respiración.",
          "Siente cómo tu corazón late más lento.",
          "Frota tus manos para calentarlas.",
          "Piensa en un momento de tranquilidad.",
          "Susurra 'Relájate' a ti mismo.",
          "Golpea tus dedos suavemente.",
          "Imagina olas meciéndose con calma.",
          "Cierra los ojos y escucha.",
          "Siente la silla debajo de ti.",
          "Mira brevemente hacia el cielo.",
          "Repite: 'Este momento es suficiente.'",
          "Toma un sorbo de té caliente y saborea su sabor.",
          "Sonríe suavemente para relajarte.",
          "Observa cómo se mueve una hoja o una nube.",
          "Cambia tu atención a tu respiración.",
          "Imagina que la tensión se derrite.",
          "Junta las palmas de tus manos.",
          "Di 'Estoy presente' y acomódate.",
          "Siente el aire al respirar.",
          "Piensa en un color relajante.",
          "Mueve los dedos de los pies lentamente."
        ],
      ),
      Category(
        name: "Hábitos y Rutinas Saludablest",
        tips: [
          "Pon tu teléfono en modo avión por la noche para evitar distracciones.",
          "Camina a diario para mejorar tu salud física.",
          "Practica 15 minutos de yoga cada mañana para relajarte.",
          "Lleva un diario de gratitud para apreciar cada día.",
          "Toma infusiones después de comer para relajarte.",
          "Prepara tus comidas con antelación para comer más sano.",
          "Desayuna de forma equilibrada para empezar bien el día.",
          "Haz ejercicios diarios para fortalecer tu cuerpo.",
          "Consume proteínas según tus necesidades para cuidar tu salud.",
          "Sustituye las grasas saturadas por grasas más saludables.",
          "Medita 5 minutos después de comer para reducir el estrés.",
          "Estírate con frecuencia para evitar tensiones musculares.",
          "Come una manzana al día para incluir fruta en tu dieta.",
          "Camina 10 minutos al día con buena postura para mantenerte activo.",
          "Tómate 5 minutos para no hacer nada y relajarte.",
          "Llena la mitad de tu plato con frutas y verduras en cada comida.",
          "Añade un alimento nuevo a tu lista de compras cada mes.",
          "Bebe 1.5 litros de agua al día para mantenerte hidratado.",
          "Sonríe voluntariamente cada día para mejorar tu ánimo.",
          "Revisa tu correo solo 2-3 veces al día para evitar distracciones.",
          "No duermas con el teléfono: déjalo en otra habitación para dormir mejor.",
          "Usa un despertador tradicional en lugar del móvil y guárdalo lejos de la cama.",
          "Mantén tu espacio de trabajo ordenado para reducir el estrés.",
          "Haz ejercicio diario, aunque sean solo 20 minutos de caminata.",
          "Crea un tablero de visión para mantener la motivación y el enfoque.",
          "Aprende a decir \"no\" para gestionar mejor tu tiempo y energía.",
          "Usa las escaleras en lugar del ascensor para moverte más.",
          "Desplázate en bici o a pie en trayectos cortos.",
          "Haz ejercicios de fuerza en casa para mejorar tu condición física.",
          "Reduce el sedentarismo con pausas para caminar.",
          "Prepara tu equipo de ejercicio con antelación para facilitar la rutina.",
          "Aparca más lejos de la entrada para caminar un poco más.",
          "Apúntate a clases de baile para divertirte y liberar energía.",
          "Únete a un deporte de equipo para socializar y mantenerte activo.",
          "Prueba una actividad nueva cada semana para enriquecerte.",
          "Aumenta tu consumo de verduras para mejorar tu salud.",
          "Bebe entre 6 y 10 vasos de agua al día.",
          "Practica técnicas de relajación con regularidad.",
          "Elige una actividad física que disfrutes para mantener la motivación.",
          "Realiza 150 minutos de ejercicio a la semana.",
          "Establece una rutina de sueño constante.",
          "Incorpora estiramientos en tu día a día.",
          "Date duchas frías para estimular la circulación.",
          "Lee un libro enriquecedor cada día.",
          "Descubre un barrio nuevo cada semana.",
          "Practica la alimentación consciente.",
          "Sal a caminar por la mañana o noche para recargar energías.",
          "Mantente hidratado durante todo el día.",
          "Toma una siesta de 20 minutos si te cuesta concentrarte.",
          "Evita los ultraprocesados y comidas pesadas al mediodía para prevenir el bajón energético.",
          "Empieza el día con estiramientos y ejercicio para activar el cuerpo.",
          "Acuéstate más temprano para despertar con más energía.",
          "Modera el consumo de café. Si necesitas energía, prueba una siesta corta.",
          "Date un baño de vapor (hammam o sauna) para estimular la circulación y el sistema inmunológico."
        ],
      ),
      Category(
        name: "Establecimiento y Logro de Metas",
        tips: [
          "Utiliza el método SMART para definir objetivos específicos, medibles, alcanzables, realistas y con plazos determinados.",
          "Establece metas claras y precisas para evitar ambigüedades.",
          "Define indicadores de medición para evaluar el éxito.",
          "Asegúrate de que tus metas sean alcanzables para mantener la motivación.",
          "Alinea tus objetivos con tus valores para mantener la coherencia.",
          "Crea un calendario para priorizar metas y establecer plazos.",
          "En el trabajo, comunica tus objetivos al equipo para garantizar comprensión y compromiso.",
          "Divide metas grandes en objetivos más pequeños para evitar una sobrecarga.",
          "Utiliza tableros de control para hacer un seguimiento del progreso.",
          "Celebra tus logros para reforzar la motivación.",
          "Aprende de los fracasos para ajustar tus estrategias.",
          "Mantén la flexibilidad para adaptar tus metas a los cambios.",
          "Establece metas a corto y largo plazo para mantener una visión global.",
          "Usa herramientas de gestión de proyectos para organizar tareas.",
          "Revisa regularmente tus objetivos para ajustar tu estrategia.",
          "Crea un plan de acción detallado para cada meta.",
          "Identifica obstáculos potenciales para anticipar desafíos.",
          "Moviliza los recursos necesarios para apoyar tus objetivos.",
          "Sé paciente y persistente ante las dificultades.",
          "Sé creativo para encontrar soluciones innovadoras.",
          "Usa ejemplos concretos para ilustrar tus metas.",
          "Crea un ambiente propicio para el éxito.",
          "Fomenta la colaboración para alcanzar objetivos comunes.",
          "Establece metas motivadoras para estimular el compromiso.",
          "En el trabajo, utiliza recompensas para motivar al equipo.",
          "Realiza evaluaciones periódicas para medir el progreso.",
          "Mantente abierto a comentarios para mejorar tus estrategias.",
          "Crea un sistema de seguimiento para medir resultados.",
          "Usa datos para tomar decisiones informadas.",
          "Establece metas ambiciosas pero alcanzables para estimular el crecimiento.",
          "Crea un plan de contingencia para eventos inesperados.",
          "Sé adaptable para ajustar tus metas a los cambios.",
          "Utiliza herramientas de comunicación para mantener el compromiso.",
          "Crea un ambiente de apoyo para animar a los miembros del equipo.",
          "Realiza ejercicios de reflexión para mejorar tu estrategia.",
          "Usa modelos de éxito para inspirar tus metas.",
          "Establece objetivos alineados con tu visión para mantener una dirección clara.",
          "Crea un sistema de recompensas por logros.",
          "Realiza análisis de riesgos para anticipar posibles desafíos.",
          "Usa herramientas de gestión del tiempo para optimizar la productividad.",
          "Crea un plan de desarrollo para mejorar continuamente tus habilidades.",
          "Realiza ejercicios de visualización para motivarte.",
          "Usa frases motivacionales para mantener el compromiso.",
          "Crea un espacio de intercambio para discutir el progreso.",
          "Establece metas para cada área de tu vida para mantener el equilibrio.",
          "Usa aplicaciones de seguimiento para monitorear el progreso.",
          "Realiza evaluaciones anuales para valorar los logros.",
          "Crea un sistema de mentoría para apoyar a los miembros del equipo.",
          "Usa ejemplos de éxito para inspirar a tu equipo.",
          "Celebra cada hito para mantener la motivación y satisfacción."
        ],
      ),
      Category(
        name: "Regulación Emocional",
        tips: [
          "Dedica unos minutos al día a practicar la respiración consciente.",
          "Identifica tus emociones para comprenderlas mejor.",
          "Expresa tus emociones de manera adecuada.",
          "Usa el humor para aliviar situaciones estresantes.",
          "Practica la meditación para fortalecer tu atención plena.",
          "Lleva un diario emocional para registrar tus sentimientos.",
          "Comprende el origen de tus emociones para gestionarlas mejor.",
          "Pide ayuda a personas de confianza.",
          "Aprende a aceptar tus emociones sin juzgarlas.",
          "Practica la relajación muscular para calmar tu sistema nervioso.",
          "Realiza ejercicio para liberar la tensión física.",
          "Usa la visualización para relajarte.",
          "Tómate tiempo para recargar energías en la naturaleza.",
          "Aprende a reconocer las señales de tu cuerpo.",
          "Practica la gratitud para equilibrar tus emociones.",
          "Usa afirmaciones positivas para aumentar tu confianza.",
          "Aprende a decir no sin sentir culpa.",
          "Practica la atención plena en tus actividades diarias.",
          "Toma descansos regulares para calmarte.",
          "Comprende que tus emociones son temporales.",
          "Confía en tu intuición para tomar decisiones.",
          "Aprende a gestionar tus expectativas para reducir el estrés.",
          "Practica la autocompasión.",
          "Usa técnicas de comunicación asertiva.",
          "Aprende a poner en perspectiva las situaciones difíciles.",
          "Cuida tu sueño para regular tus emociones.",
          "Participa en actividades creativas para expresar tus emociones.",
          "Aprende a perdonarte y dejar ir el pasado.",
          "Usa la revaluación para transformar emociones negativas.",
          "Practica la resolución de problemas para reducir el estrés.",
          "Aprende a enfocarte en el presente.",
          "Usa el apoyo social para sentirte menos solo.",
          "Practica la paciencia y la comprensión hacia ti mismo.",
          "Aprende a reconocer tus límites emocionales.",
          "Usa técnicas de manejo del estrés como caminar.",
          "Practica la atención plena en las interacciones sociales.",
          "Aprende a expresar tus necesidades claramente.",
          "Usa libros para aprender a gestionar tus emociones.",
          "Practica la gratitud diariamente.",
          "Aprende a liberar pensamientos negativos.",
          "Usa ejercicios de atención plena para calmarte.",
          "Practica la compasión hacia los demás.",
          "Aprende a gestionar tus emociones en situaciones profesionales.",
          "Usa técnicas de respiración para calmar tu sistema nervioso.",
          "Aprende a enfocarte en los aspectos positivos de tu vida.",
          "Usa afirmaciones para aumentar tu autoconfianza.",
          "Practica la atención plena en tus relaciones.",
          "Aprende a perdonarte y seguir adelante."
        ],
      ),
      Category(
        name: "CBT-Inspired Tips",
        tips: [
          "Identifica tus pensamientos automáticos para comprender tus emociones.",
          "Practica la reestructuración cognitiva para modificar los pensamientos negativos.",
          "Aprende a reconocer distorsiones cognitivas para mejorar tu percepción.",
          "Practica la relajación para reducir el estrés y la ansiedad.",
          "Realiza ejercicios de respiración profunda para calmar tu mente.",
          "Usa la exposición gradual para superar fobias.",
          "Desarrolla la asertividad para mejorar tus relaciones.",
          "Aprende a manejar la ira identificando sus detonantes.",
          "Practica la atención plena para estar más presente.",
          "Identifica tus patrones cognitivos para poder modificarlos.",
          "Aprende a decir \"no\" sin sentir culpa.",
          "Realiza ejercicios de visualización para motivarte.",
          "Lleva un diario de pensamientos para monitorear tu progreso.",
          "Practica meditación para mejorar tu concentración.",
          "Usa afirmaciones positivas para aumentar tu confianza.",
          "Aprende a expresar tus emociones de manera constructiva.",
          "Realiza ejercicios de resolución de problemas para mejorar tu adaptabilidad.",
          "Practica la gratitud para poder apreciar cada día.",
          "Identifica pensamientos catastróficos para reestructurarlos.",
          "Usa técnicas de comunicación asertiva para mejorar tus relaciones.",
          "Crea un plan de acción para superar obstáculos.",
          "Practica la alimentación consciente para saborear los alimentos.",
          "Realiza relajación progresiva para distender tus músculos.",
          "Aprende a manejar conflictos de una manera constructiva.",
          "Usa herramientas de gestión del tiempo para optimizar tu productividad.",
          "Crea un espacio de relajación para recargar energías.",
          "Practica la respiración alterna para equilibrar tu energía.",
          "Realiza meditaciones guiadas para alcanzar la relajación.",
          "Usa frases positivas para motivarte.",
          "Aprende a reconocer tus emociones para gestionarlas mejor.",
          "Lleva un diario de bienestar para registrar tu evolución.",
          "Practica la atención plena en las relaciones para mejorar la comunicación.",
          "Desarrolla empatía para enriquecer tus vínculos.",
          "Visualiza el éxito para mantener tu motivación.",
          "Practica la conciencia plena en cada momento para permanecer presente.",
          "Aprende a manejar emociones intensas usando una exposición gradual.",
          "Crea espacios de diálogo para compartir emociones.",
          "Practica ejercicios de gratitud por pequeños momentos.",
          "Forma grupos de apoyo con personas positivas.",
          "Cultiva una actitud positiva para enfrentar desafíos.",
          "Practica la conexión consciente con la naturaleza para renovarte."
        ],
      ),
    ];
  }

  // Helper methods for easy access
  static List<String> getCategoryNames() {
    return getAllCategories().map((category) => category.name).toList();
  }

  static Category? getCategoryByName(String name) {
    try {
      return getAllCategories().firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  static List<String> getTipsByCategory(String categoryName) {
    final category = getCategoryByName(categoryName);
    return category?.tips ?? [];
  }

  static int getTotalTipsCount() {
    return getAllCategories()
        .map((category) => category.tips.length)
        .reduce((a, b) => a + b);
  }

  static String getRandomTip() {
    final allCategories = getAllCategories();
    final randomCategory = (allCategories..shuffle()).first;
    final randomTip = (randomCategory.tips..shuffle()).first;
    return randomTip;
  }

  // Additional helper methods for the new categories
  static List<Category> getWellnessCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Healthy Habits and Routines",
      "Emotional Regulation",
      "Stress Management",
      "Mindfulness"
    ].contains(category.name)).toList();
  }

  static List<Category> getPerformanceCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Productivity and Focus",
      "Goal Setting and Achievement",
      "Cognitive Behavioral Techniques"
    ].contains(category.name)).toList();
  }

  static List<Category> getSocialCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Social Connections and Relationships",
      "Positive Thinking and Gratitude"
    ].contains(category.name)).toList();
  }
}