
import 'TipsData.dart';

class TipDataDE {
  static List<Category> getAllCategories() {
    return [
      Category(
        name: "Emotionale Regulierung",
        tips: [
          "Üben Sie die Bauchatmung, um das Nervensystem zu beruhigen.",
          "Machen Sie regelmäßig Sport, um Endorphine freizusetzen.",
          "Meditieren Sie, um Stress abzubauen und die Konzentration zu verbessern.",
          "Hören Sie beruhigende Musik, um den Geist zu entspannen.",
          "Ernähren Sie sich ausgewogen, um Ihre Energie aufrechtzuerhalten.",
          "Sorgen Sie für ausreichend Schlaf, damit sich der Körper erholen kann.",
          "Üben Sie Achtsamkeit, um in der Gegenwart zu leben.",
          "Lernen Sie, ohne Schuldgefühle „Neinzu sagen, um Druck abzubauen.",
          "Üben Sie dynamische Entspannung, um Muskelverspannungen zu lösen.",
          "Erkennen Sie Stressquellen, um sie besser zu bewältigen.",
          "Verwenden Sie positive Affirmationen, um Ihr Selbstvertrauen zu stärken.",
          "Machen Sie regelmäßig Pausen, um sich zu erholen.",
          "Vertrauen Sie auf Ihre Intuition, wenn Sie Entscheidungen treffen.",
          "Lernen Sie, schwierige Situationen ins rechte Licht zu rücken.",
          "Üben Sie Herzkohärenz, um Ihre Herzfrequenz zu regulieren.",
          "Nutzen Sie Visualisierungstechniken, um sich zu motivieren.",
          "Umgeben Sie sich mit positiven Menschen, um Stress abzubauen.",
          "Üben Sie Selbstmitgefühl für sich und andere.",
          "Lernen Sie, mit Ihren Erwartungen umzugehen, um Stress zu reduzieren.",
          "Nutzen Sie Bücher, um zu lernen, wie Sie Stress bewältigen können.",
          "Üben Sie täglich Dankbarkeit, um Ihre Gefühle auszugleichen.",
          "Lernen Sie, negative Gedanken loszulassen.",
          "Nutzen Sie Achtsamkeitsübungen, um sich zu beruhigen.",
          "Bringen Sie Ihre Bedürfnisse klar zum Ausdruck.",
          "Planen Sie Ihre Aufgaben immer im Voraus, um Ihre Zeit besser einteilen zu können.",
          "Lernen Sie, sich zu verzeihen und weiterzumachen.",
          "Nutzen Sie energiespendende Atemtechniken, um sich zu motivieren.",
          "Konzentrieren Sie sich auf die positiven Aspekte Ihres Lebens.",
          "Nutzen Sie Affirmationen, um Ihr Selbstvertrauen zu stärken.",
          "Verwenden Sie Atemtechniken, um Ihr Nervensystem zu beruhigen.",
          "Üben Sie sich in der Methode: Verzicht, Anpassung, Akzeptanz und Anpassung.",
          "Lernen Sie, sich von Ablenkungen zu lösen, um sich zu konzentrieren.",
          "Üben Sie sich in Mitgefühl für andere.",
          "Lernen Sie, mit Ihren emotionalen Grenzen umzugehen.",
          "Üben Sie Achtsamkeit in sozialen Interaktionen.",
          "Haben Sie keine Angst, Ihre Gefühle angemessen auszudrücken.",
          "Üben Sie sich in Dankbarkeit, um Ihre Gefühle auszugleichen.",
          "Lernen Sie, sich selbst zu verzeihen und die Vergangenheit loszulassen."
          ]
      ),
      Category(
        name: "Soziale Bindungen und Beziehungen",
        tips: [
          "Nehmen Sie an sozialen Aktivitäten teil, um Ihren sozialen Kreis zu erweitern.",
          "Schaffen Sie Gelegenheiten, neue Menschen kennen zu lernen, die Ihre Interessen teilen.",
          "Üben Sie aktives Zuhören, um die Qualität Ihrer Kommunikation zu verbessern.",
          "Treten Sie einem Club oder einer Vereinigung bei, um Menschen zu treffen.",
          "Organisieren Sie gesellschaftliche Veranstaltungen, um die Beziehungen zu Freunden und Familie zu stärken.",
          "Schauen Sie regelmäßig nach, wie es Ihren Angehörigen geht.",
          "Zeigen Sie Einfühlungsvermögen, um andere besser zu verstehen.",
          "Seien Sie in Ihrer Kommunikation aufrichtig, um starke Beziehungen aufzubauen.",
          "Lernen Sie, nein zu sagen, um Zeit und Energie zu sparen.",
          "Üben Sie sich in Dankbarkeit gegenüber den wichtigen Menschen in Ihrem Leben.",
          "Hören Sie zu, ohne zu urteilen, um einen sicheren Raum für Diskussionen zu schaffen.",
          "Schaffen Sie Momente des Austauschs mit Kollegen, um das Arbeitsumfeld zu verbessern.",
          "Machen Sie aufrichtige Komplimente, um Beziehungen zu stärken.",
          "Nehmen Sie an Freiwilligenprojekten teil, um Menschen mit gleichen Werten zu treffen.",
          "Seien Sie in Gesprächen präsent, um Ihr Interesse zu zeigen.",
          "Verwenden Sie motivierende Worte, um andere zu ermutigen.",
          "Schaffen Sie einen Raum für Diskussionen, um den Austausch von Ideen zu erleichtern.",
          "Üben Sie sich in Achtsamkeit, um mehr Rücksicht auf andere zu nehmen.",
          "Nehmen Sie an Gruppenaktivitäten teil, um soziale Bindungen zu stärken.",
          "Lernen Sie, mit Konflikten umzugehen, um gesunde Beziehungen zu pflegen.",
          "Seien Sie geduldig mit anderen, um die Kommunikation zu verbessern.",
          "Essen Sie mit der Familie zu Abend, um die Familienbande zu stärken.",
          "Respektieren Sie die Unterschiede der anderen.",
          "Schaffen Sie soziale Rituale, um den regelmäßigen Kontakt aufrechtzuerhalten.",
          "Verwenden Sie Humor, um die Atmosphäre aufzulockern.",
          "Üben Sie Gruppenmeditation, um den Zusammenhalt zu stärken.",
          "Machen Sie Mitgefühlsübungen, um Empathie zu entwickeln.",
          "Seien Sie offen für neue Erfahrungen, um Ihre Beziehungen zu bereichern.",
          "Führen Sie ein Dankbarkeitstagebuch, um Ihre Beziehungen zu würdigen.",
          "Machen Sie symbolische Geschenke, um Ihre Wertschätzung zu zeigen.",
          "Üben Sie gewaltfreie Kommunikation, um Konflikte zu lösen.",
          "Organisieren Sie gemeinsame Ausflüge, um Momente des Austauschs zu schaffen.",
          "Nutzen Sie Kommunikationsmittel, um mit geliebten Menschen in Kontakt zu bleiben.",
          "Schaffen Sie einen Entspannungsraum, um die Entspannung in der Gruppe zu fördern.",
          "Gemeinsame kreative Aktivitäten, um die Kreativität zu fördern.",
          "Üben Sie sich in Dankbarkeit gegenüber Kollegen, um das Arbeitsklima zu verbessern.",
          "Seien Sie flexibel, um Ihre Kommunikation an die Bedürfnisse anderer anzupassen.",
          "Schaffen Sie Mentoring-Möglichkeiten, um anderen zu helfen, sich zu entwickeln.",
          "Veranstalten Sie kulturelle Events, um Beziehungen zu bereichern.",
          "Verwenden Sie ermutigende Worte, um andere zu motivieren.",
          "Bilden Sie eine Selbsthilfegruppe, um den Teilnehmern bei der Bewältigung von Herausforderungen zu helfen.",
          "Nehmen Sie gemeinsam an Wellness-Aktivitäten teil, um die geistige Gesundheit zu erhalten.",
          "Üben Sie geführte Meditationen, um die Konzentration in Gruppen zu verbessern.",
          "Achten Sie auf die Bedürfnisse anderer, um Beziehungen zu stärken.",
          "Schaffen Sie kulinarische Momente des Austauschs, um soziale Bindungen zu stärken.",
          "Machen Sie Visualisierungsübungen, um andere zu motivieren.",
          "Schaffen Sie einen Raum der Anerkennung, um die Beiträge der anderen zu würdigen."
        ]
      ),
      Category(
        name: "Widerstandsfähigkeit",
        tips: [
          "Erkennen Sie Ihre Emotionen, um besser mit ihnen umgehen zu können.",
          "Üben Sie Achtsamkeit, um in der Gegenwart zu bleiben.",
          "Setzen Sie sich realistische Ziele, um motiviert zu bleiben.",
          "Bauen Sie ein Unterstützungsnetzwerk auf, um sich mit positiven Menschen zu umgeben.",
          "Lernen Sie, „nein zu sagen, um Ihre Zeit und Energie zu schützen.",
          "Üben Sie sich in Dankbarkeit, um jeden Tag zu schätzen.",
          "Machen Sie tiefe Atemübungen, um Ihren Geist zu beruhigen.",
          "Achten Sie auf Ihre körperliche Gesundheit, um Ihre Widerstandsfähigkeit zu stärken.",
          "Entwickeln Sie eine positive Einstellung, um Herausforderungen zu meistern.",
          "Lernen Sie aus vergangenen Erfahrungen, um Ihre Strategien zu verbessern.",
          "Schaffen Sie sich einen Raum der Entspannung, um sich zu verjüngen.",
          "Werden Sie kreativ, um Ihre Gefühle auszudrücken.",
          "Wenden Sie Entspannungstechniken an, um Stress abzubauen.",
          "Üben Sie Meditation, um Ihre Konzentration zu verbessern.",
          "Setzen Sie sich kleine Ziele, um Schritt für Schritt voranzukommen.",
          "Erkennen Sie Ihre Stärken, um Ihr Selbstvertrauen zu stärken.",
          "Führen Sie ein Tagebuch der Dankbarkeit, um jeden Tag zu würdigen.",
          "Üben Sie sich beim Essen in Achtsamkeit, um die Aromen zu genießen.",
          "Machen Sie regelmäßig Pausen, um Müdigkeit zu vermeiden.",
          "Verwenden Sie motivierende Worte, um sich selbst zu ermutigen.",
          "Erstellen Sie einen Aktionsplan, um Hindernisse zu überwinden.",
          "Machen Sie Visualisierungsübungen, um sich zu motivieren.",
          "Üben Sie Selbstmitgefühl, um Ihre Fehler zu akzeptieren.",
          "Umgeben Sie sich mit positiven Menschen, um Ihr Wohlbefinden zu steigern.",
          "Lernen Sie, Konflikte zu bewältigen, um gesunde Beziehungen zu pflegen.",
          "Schaffen Sie einen gemeinsamen Raum, um über Ihre Gefühle zu sprechen.",
          "Machen Sie Übungen zur Muskelstärkung, um Ihre körperliche Gesundheit zu verbessern.",
          "Gehen Sie achtsam spazieren, um sich wieder mit der Natur zu verbinden.",
          "Setzen Sie sich langfristige Ziele, um das große Ganze im Auge zu behalten.",
          "Schaffen Sie eine Morgenroutine, um den Tag positiv zu beginnen. Dehnen Sie sich zum Beispiel oder lernen Sie eine neue Fähigkeit.",
          "Machen Sie Wechselatemübungen, um Ihre Stimmung auszugleichen.",
          "Üben Sie Dankbarkeit gegenüber geliebten Menschen, um die Bindung zu stärken.",
          "Verwenden Sie ätherische Öle, um eine entspannende Atmosphäre zu schaffen.",
          "Schaffen Sie Raum für Kreativität, um Ihre Ideen auszudrücken.",
          "Belohnen Sie sich, um Ihre Erfolge zu feiern.",
          "Machen Sie Übungen zur Erfolgsvisualisierung, um sich zu motivieren.",
          "Verwenden Sie positive Zitate, um sich selbst zu ermutigen.",
          "Führen Sie ein Wohlfühl-Tagebuch, um Ihre Fortschritte zu verfolgen.",
          "Führen Sie vor dem Schlafengehen achtsame Atemübungen durch, um Ihren Schlaf zu verbessern.",
          "Schaffen Sie einen offenen Raum zur Entspannung, um sich zu verjüngen.",
          "Üben Sie sich in Dankbarkeit für kleine Momente, um jeden Augenblick zu schätzen.",
          "Gründen Sie eine Selbsthilfegruppe, um sich mit positiven Menschen zu umgeben.",
          "Üben Sie sich in jedem Moment in Achtsamkeit, um präsent und beständig zu bleiben."
          ]
      ),
      Category(
        name: "Produktivität und Konzentration",
        tips: [
          "Planen Sie Ihre Tage, damit Sie sich auf Ihre Ziele konzentrieren können.",
          "Richten Sie Ihre Aufgaben an Ihren langfristigen Zielen aus.",
          "Bereiten Sie sich schon am Abend auf den nächsten Tag vor.",
          "Unterteilen Sie große Projekte in überschaubare Aufgaben.",
          "Vermeiden Sie Multitasking, um konzentriert zu bleiben.",
          "Arbeiten Sie in der Tiefe, um ohne Ablenkung zu arbeiten.",
          "Lassen Sie gelegentliches Chaos zu, um die Kreativität zu fördern.",
          "Beseitigen Sie Ablenkungen, um die Produktivität zu steigern.",
          "Schreiben Sie eine Aufmerksamkeitscharta, um sich selbst daran zu erinnern, Prioritäten zu setzen.",
          "Befolgen Sie die 2-Minuten-Regel, um kleine Aufgaben zu erledigen.",
          "Delegieren Sie, wenn nötig, um Zeit freizumachen.",
          "Kommunizieren Sie effektiv mit Ihrem Team.",
          "Halten Sie die 10-Minuten-Regel für regelmäßige Pausen ein.",
          "Verwenden Sie die „Sandwich-Technik, um Aufgaben angenehmer zu gestalten.",
          "Gruppieren Sie ähnliche Aufgaben, um die Zeit zu optimieren.",
          "Eliminieren Sie unwichtige Aufgaben.",
          "Sagen Sie öfter „Nein, um Ihre Zeit zu schützen.",
      "Automatisieren Sie Aufgaben nach dem Dreisatz.",
          "Legen Sie Thementage fest, um Ihre Woche zu organisieren.",
          "Gehen Sie bei Ihren täglichen Handlungen bewusst vor.",
          "Optimieren Sie Ausfallzeiten zum Lernen oder Ausruhen.",
          "Halten Sie nicht mehr als 10 Tabs gleichzeitig offen.",
          "Schaffen Sie einen organisierten und gesunden Arbeitsplatz, um die Konzentration zu verbessern.",
          "Halten Sie eine optimale Lufttemperatur ein, um wach zu bleiben.",
          "Berücksichtigen Sie Ihren Chronotyp bei der Planung von Aufgaben.",
          "Sorgen Sie für ausreichend Schlaf, um ausgeruht zu bleiben.",
          "Verwenden Sie natürliche Stimulanzien wie Kaffee oder grünen Tee.",
          "Meditieren Sie täglich, um Ihre Konzentration zu verbessern.",
          "Machen Sie regelmäßig Pausen, um Müdigkeit zu vermeiden.",
          "Streben Sie stets danach, Ihre Fähigkeiten zu verbessern, um motiviert zu bleiben.",
          "Messen Sie Ihre Produktivität, um Ihre Strategien anzupassen.",
          "Ziehen Sie die Dinge bis zum Ende durch, um sich nicht zu verzetteln.",
          "Suchen Sie nicht nach Abkürzungen, um die Qualität zu erhalten.",
          "Bleiben Sie nicht stecken; machen Sie bei Bedarf eine Pause.",
          "Streben Sie nicht nach Perfektion, um Prokrastination zu vermeiden.",
          "Planen Sie Zeiten der Konzentration in Ihrem Kalender ein.",
          "Führen Sie besprechungsfreie Tage ein, um sich auf die eigentliche Arbeit zu konzentrieren.",
          "Konzentrieren Sie sich auf eine Aufgabe zur gleichen Zeit, um eine Streuung zu vermeiden.",
          "Hören Sie entspannende Musik, um sich besser konzentrieren zu können.",
          "Gestalten Sie Ihre Arbeitssitzungen ansprechender, um Langeweile zu vermeiden.",
          "Verknüpfen Sie Ihre täglichen Aktivitäten mit Ihren persönlichen Zielen.",
          "Visualisieren Sie Ihre Ziele, um motiviert zu bleiben.",
          "Nutzen Sie Projektmanagement-Tools, um Ihre Aufgaben zu organisieren.",
          "Schaffen Sie ein kreativitätsförderndes Umfeld, um Innovationen zu fördern.",
          "Scheuen Sie sich nicht, Gelegenheiten wahrzunehmen, die mit Ihren Zielen übereinstimmen.",
          "Legen Sie mitten im Arbeitstag 20-minütige Schlafpausen ein."
          ]
      ),
      Category(
        name: "Positives Denken und Dankbarkeit",
        tips: [
          "Beginnen Sie jeden Tag mit einer positiven Affirmation, um sich zu motivieren.",
          "Üben Sie sich in Dankbarkeit, indem Sie jeden Tag drei Dinge aufschreiben, die Sie schätzen.",
          "Machen Sie eine Liste Ihrer Leistungen, um sich an Ihre Erfolge zu erinnern.",
          "Umgeben Sie sich mit positiven Menschen, um Ihr Wohlbefinden zu steigern.",
          "Üben Sie sich in Achtsamkeit, um präsent zu sein und jeden Moment zu schätzen.",
          "Verwenden Sie motivierende Worte, um sich selbst zu ermutigen.",
          "Entwickeln Sie eine Morgenroutine, um den Tag mit Optimismus zu beginnen.",
          "Machen Sie Visualisierungsübungen, um sich zu motivieren und Ziele zu erreichen.",
          "Schreiben Sie Dankesbriefe an diejenigen, die einen positiven Einfluss auf Ihr Leben haben.",
          "Praktizieren Sie Meditation, um Ihren Geist zu beruhigen und Positivität zu kultivieren.",
          "Machen Sie tiefe Atemübungen, um Stress abzubauen und Ihre Stimmung zu verbessern.",
          "Legen Sie Pausen ein, um sich zu entspannen und die kleinen Momente zu schätzen.",
          "Schaffen Sie sich zu Hause einen Entspannungsraum, um sich zu verjüngen.",
          "Beschäftigen Sie sich mit kreativen Aktivitäten, um Ihre Positivität auszudrücken.",
          "Tanzen Sie, um positive Energie freizusetzen.",
          "Verwenden Sie ätherische Öle, um eine positive Atmosphäre zu schaffen.",
          "Üben Sie sich beim Essen in Achtsamkeit, um die Aromen zu genießen.",
          "Kümmern Sie sich um Ihre körperliche Gesundheit, um Ihr geistiges Wohlbefinden zu verbessern.",
          "Üben Sie Dankbarkeit mit Ihrer Familie, um die Bindungen zu stärken.",
          "Führen Sie ein Tagebuch der Dankbarkeit, um Ihre Fortschritte zu verfolgen.",
          "Machen Sie Mitgefühlsübungen, um Empathie zu entwickeln.",
          "Verwenden Sie positive Zitate, um sich zu motivieren.",
          "Gehen Sie achtsam spazieren, um sich wieder mit der Natur zu verbinden.",
          "Machen Sie Übungen zur Erfolgsvisualisierung, um sich zu motivieren.",
          "Trinken Sie beruhigende Tees, um den Geist zu beruhigen.",
          "Praktizieren Sie progressive Entspannung, um Ihre Muskeln zu entspannen.",
          "Entwickeln Sie eine Abendroutine, um den Tag positiv zu beenden.",
          "Üben Sie sich vor dem Schlafengehen in Dankbarkeit, um jeden Tag zu würdigen.",
          "Verwenden Sie ermutigende Worte, um sich zu motivieren.",
          "Üben Sie Achtsamkeit in Beziehungen, um die Kommunikation zu verbessern.",
          "Machen Sie achtsame Atemübungen, um Stress abzubauen.",
          "Machen Sie Urlaub, um sich zu verjüngen und das Leben zu schätzen.",
          "Schaffen Sie Raum für Kreativität, um Ihre Positivität auszudrücken.",
          "Üben Sie sich in Dankbarkeit für kleine Momente, um jeden Augenblick zu schätzen.",
          "Üben Sie geführte Meditationen, um sich selbst in die Positivität zu führen.",
          "Gründen Sie eine Selbsthilfegruppe, um sich mit positiven Menschen zu umgeben.",
          "Üben Sie sich in Dankbarkeit für Beziehungen, um Verbindungen zu stärken.",
          "Verwenden Sie pflanzliche Heilmittel, um Ihr Wohlbefinden zu verbessern.",
          "Üben Sie sich in der Natur in Dankbarkeit, um wieder in Kontakt zu kommen.",
          "Machen Sie Visualisierungsübungen für inneren Frieden, um sich zu beruhigen.",
          "Führen Sie ein Wohlfühl-Tagebuch, um Ihre Fortschritte zu verfolgen.",
          "Machen Sie vor dem Schlafengehen tiefe Atemübungen, um besser zu schlafen.",
          "Verwenden Sie motivierende Worte für den Erfolg, um sich selbst zu ermutigen.",
          "Üben Sie Achtsamkeit für Kreativität, um Innovationen zu fördern.",
          "Üben Sie Dankbarkeit für Gelegenheiten, um jede Chance zu schätzen.",
          "Schaffen Sie sich einen offenen Raum zur Entspannung, um sich zu verjüngen.",
          "Zeigen Sie Mitgefühl für andere, um Empathie zu entwickeln.",
          "Üben Sie Dankbarkeit für jeden Moment, um das Leben zu schätzen."
        ]
      ),
      Category(
        name: "Bewusstseinsbildung",
        tips: [
          "Bei 4 einatmen, bei 6 ausatmen.",
          "Nimm fünf Dinge wahr, die du siehst.",
          "Spüre deine Füße auf dem Boden.",
          "Hören Sie auf die Geräusche um Sie herum.",
          "Schließe deine Augen für 10 Sekunden.",
          "Ziehen Sie die Arme hoch.",
          "Sagen Sie zu sich selbst: „Ich bin hier",
          "Rollen Sie sanft mit den Schultern.",
          "Stellen Sie sich heute einen ruhigen See vor.",
          "Singen Sie eine leise Melodie.",
          "Fragen Sie: 'Was ist jetzt gerade hier?'",
          "Legen Sie Ihre Hände auf Ihre Knie.",
          "Zählen Sie fünf langsame Ausatmungen.",
          "Lass deine Gedanken wie Wolken schweben.",
          "Riechen Sie an etwas Schönem.",
          "Sagen Sie zu sich selbst: 'Ich bin in Frieden.'",
          "Konzentrieren Sie sich auf ein Geräusch.",
          "Entspannen Sie jetzt Ihren Kiefer.",
          "Sitze 30 Sekunden lang still.",
          "Stellen Sie sich ein warmes Licht im Inneren vor.",
          "Halten Sie die Schultern unten.",
          "Atme in deinen Bauch.",
          "Streichen Sie die Farben um sich herum.",
          "Sagen Sie bei jedem Atemzug 'Ruhe'.",
          "Spüren Sie, wie sich Ihr Herzschlag verlangsamt.",
          "Reiben Sie Ihre Hände, um Wärme zu bekommen.",
          "Denken Sie an einen ruhigen Moment.",
          "Flüstern Sie sich zu: 'Entspannen Sie sich'.",
          "Klopfen Sie sanft mit den Fingern.",
          "Stellen Sie sich vor, wie die Wellen sanft plätschern.",
          "Schließen Sie die Augen und lauschen Sie.",
          "Fühle den Stuhl unter dir.",
          "Schauen Sie einen Moment lang in den Himmel.",
          "Wiederholen Sie: 'Dieser Moment ist genug'.",
          "Trinke warmen Tee und genieße den Geschmack.",
          "Lächle sanft, um dich zu entspannen.",
          "Beobachte, wie sich ein Blatt oder eine Wolke bewegt.",
          "Richten Sie Ihre Aufmerksamkeit auf Ihre Atmung.",
          "Stellen Sie sich vor, wie die Spannung wegschmilzt.",
          "Drücken Sie Ihre Handflächen aneinander.",
          "Sagen Sie 'Sei hier' und seien Sie still.",
          "Spüren Sie die Luft beim Atmen.",
          "Denken Sie an eine beruhigende Farbe.",
          "Wackeln Sie langsam mit den Zehen."
          ]
      ),
      Category(
        name: "Gesunde Gewohnheiten und Routinen",
        tips: [
          "Schalten Sie Ihr Telefon nachts auf Flugmodus, um Ablenkungen zu vermeiden.",
          "Gehen Sie jeden Tag spazieren, um Ihre körperliche Gesundheit zu verbessern.",
          "Machen Sie jeden Morgen 15 Minuten Yoga, um sich zu entspannen.",
          "Führen Sie ein Tagebuch der Dankbarkeit, um jeden Tag zu würdigen.",
          "Trinken Sie nach den Mahlzeiten Kräutertee, um sich zu entspannen.",
          "Bereiten Sie Mahlzeiten im Voraus vor, um gesünder zu essen.",
          "Essen Sie ein ausgewogenes Frühstück, um gut in den Tag zu starten.",
          "Machen Sie jeden Tag Übungen, um Ihren Körper zu stärken.",
          "Nehmen Sie Eiweiß entsprechend Ihrem Bedarf zu sich, um gesund zu bleiben.",
          "Ersetzen Sie gesättigte Fette durch gesündere Fette, um Ihre Ernährung zu verbessern.",
          "Meditieren Sie nach dem Mittagessen 5 Minuten lang, um Stress abzubauen.",
          "Dehnen Sie sich regelmäßig, um Muskelverspannungen zu vermeiden.",
          "Essen Sie jeden Tag einen Apfel, um Obst in Ihre Ernährung einzubauen.",
          "Gehen Sie täglich 10 Minuten spazieren und achten Sie dabei auf eine gute Körperhaltung, um aktiv zu bleiben.",
          "Nehmen Sie sich 5 Minuten Zeit zum Nichtstun und Entspannen.",
          "Füllen Sie zum Mittagessen die Hälfte Ihres Tellers mit Obst und Gemüse, um eine ausgewogene Mahlzeit zu erhalten.",
          "Nehmen Sie jeden Monat ein neues Lebensmittel auf Ihre Einkaufsliste, um Ihre Ernährung zu variieren.",
          "Trinken Sie 1,5 Liter Wasser pro Tag, um hydriert zu bleiben.",
          "Улыбайся добровольно каждый день, чтобы улучшить настроение.",
          "Checken Sie Ihre E-Mails nur 2-3 Mal pro Tag, um Ablenkungen zu vermeiden.",
          "Schlafen Sie nicht mit Ihrem Telefon, um die Schlafqualität zu verbessern. Lassen Sie es in einem anderen Raum liegen.",
          "Kaufen Sie einen Wecker, anstatt sich auf Ihr Smartphone zu verlassen. Und lassen Sie Ihr Telefon in einem anderen Raum liegen.",
          "Halten Sie Ihren Arbeitsplatz aufgeräumt, um Stress zu reduzieren.",
          "Bewegen Sie sich jeden Tag in irgendeiner Form, und sei es nur ein 20-minütiger Spaziergang, um aktiv zu bleiben.",
          "Erstellen Sie eine Visualisierungstafel, um motiviert zu bleiben und sich auf Ihre Ziele zu konzentrieren.",
          "Lernen Sie, „nein zu sagen, um Zeit und Energie zu sparen.",
      "Nehmen Sie die Treppe statt den Aufzug, um sich mehr zu bewegen.",
          "Fahren Sie mit dem Fahrrad oder gehen Sie für kurze Strecken zu Fuß.",
          "Machen Sie zu Hause Übungen zur Muskelstärkung, um Ihre Kraft zu verbessern.",
          "Verringern Sie das Sitzen, indem Sie Pausen zum Gehen einlegen.",
          "Bereiten Sie Ihre Fitnessgeräte im Voraus vor, um die Routine zu erleichtern.",
          "Parken Sie Ihr Auto weit weg vom Eingang, um mehr zu Fuß gehen zu können.",
          "Melden Sie sich für einen Tanzkurs an, der Spaß macht und Energie freisetzt.",
          "Nehmen Sie an einer Mannschaftssportart teil, um Energie freizusetzen, aktiv zu bleiben und Teamgeist zu lernen.",
          "Probieren Sie jede Woche eine neue Aktivität aus, um sich zu bereichern.",
          "Steigern Sie Ihren Gemüsekonsum, um Ihre Gesundheit zu verbessern.",
          "Trinken Sie 6 bis 10 Gläser Wasser pro Tag, um hydriert zu bleiben.",
          "Üben Sie regelmäßig Entspannungstechniken, um Stress abzubauen.",
          "Wählen Sie eine körperliche Aktivität, die Ihnen Spaß macht, um motiviert zu bleiben.",
          "Streben Sie 150 Minuten körperliche Aktivität pro Woche an, um eine gute Gesundheit zu erhalten.",
          "Führen Sie einen regelmäßigen Schlafrhythmus ein, um die Qualität Ihres Schlafs zu verbessern.",
          "Bauen Sie Dehnübungen in Ihren Tag ein, um beweglich zu bleiben.",
          "Duschen Sie kalt, um den Blutkreislauf anzuregen.",
          "Lesen Sie jeden Tag ein bereicherndes Buch, um sich weiterzuentwickeln.",
          "Erkunden Sie jede Woche eine neue Gegend, um Monotonie zu vermeiden.",
          "Üben Sie sich im achtsamen Essen, um Ihr Verhältnis zum Essen zu verbessern.",
          "Machen Sie einen Morgen- oder Abendspaziergang, um sich zu verjüngen.",
          "Achten Sie darauf, dass Sie den ganzen Tag über ausreichend Flüssigkeit zu sich nehmen, um einen optimalen Flüssigkeitshaushalt aufrechtzuerhalten.",
          "Machen Sie mitten am Tag ein 20-minütiges Nickerchen, wenn es Ihnen schwerfällt, sich zu konzentrieren.",
          "Vermeiden Sie verarbeitete Lebensmittel oder übermäßiges Essen in der Mitte des Tages. Auf diese Weise vermeiden Sie „Essenskomas und Produktivitätseinbrüche.",
      "Beginnen Sie Ihren Tag mit Übungen und Dehnübungen, machen Sie es sich zur Gewohnheit. Dadurch wird Ihr Körper wach und Sie fühlen sich munterer.",
          "Gehen Sie früher ins Bett, damit Sie früher aufwachen können. So haben Sie mehr Zeit, um mehr zu erledigen.",
          "Vermeiden Sie es, zu viel Kaffee zu trinken. Er ist schlecht für Ihren Blutdruck. Machen Sie ein Nickerchen, wenn Sie Ihre Energie wieder auftanken müssen.",
          "Gehen Sie in ein heißes Dampfbad. Das regt das Immunsystem und die Durchblutung an."
          ]
      ),
      Category(
        name: "Zielsetzung und Zielerreichung",
        tips: [
          "Verwenden Sie die SMART-Methode, um spezifische, messbare, erreichbare, realistische und zeitgebundene Ziele zu setzen.",
          "Setzen Sie klare und präzise Ziele, um Unklarheiten zu vermeiden.",
          "Definieren Sie Messgrößen, um den Erfolg zu messen.",
          "Stellen Sie sicher, dass Ihre Ziele erreichbar sind, um motiviert zu bleiben.",
          "Bringen Sie Ihre Ziele mit Ihren Werten in Einklang, um konsistent zu bleiben.",
          "Erstellen Sie einen Kalender, um Ihre Ziele zu priorisieren und Fristen festzulegen.",
          "Kommunizieren Sie bei der Arbeit Ihre Ziele mit Ihrem Team, um Verständnis und Engagement sicherzustellen.",
          "Teilen Sie große Ziele in kleinere Ziele auf, damit Sie sich nicht selbst überfordern.",
          "Verwenden Sie Dashboards, um den Fortschritt zu verfolgen.",
          "Feiern Sie Ihre Erfolge, um die Motivation zu steigern.",
          "Lernen Sie aus Misserfolgen, um Ihre Strategien anzupassen.",
          "Seien Sie flexibel, um Ihre Ziele an Veränderungen anzupassen.",
          "Setzen Sie sich sowohl kurzfristige als auch langfristige Ziele, um das große Ganze im Blick zu behalten.",
          "Nutzen Sie Projektmanagement-Tools, um Ihre Aufgaben zu organisieren.",
          "Überprüfen Sie Ihre Ziele regelmäßig, um Ihre Strategie anzupassen.",
          "Создай подробный план действий для каждой цели.",
          "Potenzielle Hindernisse erkennen, um Herausforderungen vorzubeugen.",
          "Mobilisieren Sie die notwendigen Ressourcen, um Ihre Ziele zu erreichen.",
          "Seien Sie geduldig und ausdauernd, wenn Sie auf Schwierigkeiten stoßen.",
          "Seien Sie kreativ, um innovative Lösungen zu finden.",
          "Nutzen Sie Fallstudien zur Veranschaulichung Ihrer Ziele.",
          "Schaffen Sie ein Umfeld, das den Erfolg begünstigt.",
          "Ermutigen Sie zur Zusammenarbeit, um gemeinsame Ziele zu erreichen.",
          "Setzen Sie motivierende Ziele, um das Engagement zu fördern.",
          "Setzen Sie bei der Arbeit Belohnungen ein, um Ihr Team zu motivieren.",
          "Führen Sie regelmäßige Bewertungen durch, um die Fortschritte zu verfolgen.",
          "Seien Sie offen für Feedback, um Ihre Strategien zu verbessern.",
          "Schaffen Sie ein Nachverfolgungssystem, um die Ergebnisse zu messen.",
          "Nutzen Sie Daten, um fundierte Entscheidungen zu treffen.",
          "Setzen Sie sich ehrgeizige, aber erreichbare Ziele, um das Wachstum voranzutreiben.",
          "Erstellen Sie einen Notfallplan.",
          "Seien Sie anpassungsfähig und passen Sie Ihre Ziele an Veränderungen an.",
          "Nutzen Sie Kommunikationsmittel, um Ihr Engagement aufrechtzuerhalten.",
          "Schaffen Sie eine unterstützende Umgebung, um Teammitglieder zu inspirieren.",
          "Führen Sie Reflexionsübungen durch, um Ihre Strategie zu verbessern.",
          "Nutzen Sie Erfolgsmodelle, um Ihre Ziele zu inspirieren.",
          "Setzen Sie sich Ziele, die mit Ihrer Vision übereinstimmen, um eine klare Richtung beizubehalten.",
          "Schaffen Sie ein Belohnungssystem für Erfolge.",
          "Führen Sie Risikoanalysen durch, um potenzielle Herausforderungen zu antizipieren.",
          "Nutzen Sie Instrumente des Zeitmanagements, um Ihre Produktivität zu optimieren.",
          "Erstellen Sie einen Entwicklungsplan, um Ihre Fähigkeiten kontinuierlich zu verbessern.",
          "Führen Sie Visualisierungsübungen durch, um sich zu motivieren.",
          "Verwenden Sie motivierende Zitate, um sich zu motivieren.",
          "Schaffen Sie einen Raum zum Austausch, um Fortschritte zu besprechen.",
          "Setzen Sie sich Ziele für jeden Bereich Ihres Lebens, um das Gleichgewicht zu halten.",
          "Verwenden Sie Tracking-Apps, um Ihre Fortschritte zu überwachen.",
          "Führen Sie jährliche Bewertungen durch, um Ihre Leistungen zu analysieren.",
          "Schaffen Sie ein Mentorensystem, um Teammitglieder zu unterstützen.",
          "Nutzen Sie Erfolgsgeschichten, um Ihr Team zu inspirieren.",
          "Feiern Sie jeden Meilenstein, um sie motiviert und zufrieden zu halten."
        ]
      ),
      Category(
        name: "Emotionale Regulierung",
        tips: [
          "Nehmen Sie sich jeden Tag ein paar Minuten Zeit, um achtsam zu atmen.",
          "Identifizieren Sie Ihre Gefühle, um sie besser zu verstehen.",
          "Drücken Sie Ihre Gefühle auf angemessene Weise aus.",
          "Verwenden Sie Humor, um stressige Situationen zu erleichtern.",
          "Üben Sie Meditation, um Ihre Achtsamkeit zu stärken.",
          "Führen Sie ein Gefühlstagebuch, um Ihre Gefühle im Auge zu behalten.",
          "Verstehen Sie die Ursprünge Ihrer Emotionen, um besser mit ihnen umgehen zu können.",
          "Bitten Sie vertrauenswürdige Menschen um Hilfe.",
          "Lernen Sie, Ihre Gefühle zu akzeptieren, ohne sie zu bewerten.",
          "Üben Sie Muskelentspannung, um Ihr Nervensystem zu beruhigen.",
          "Führen Sie körperliche Übungen durch, um körperliche Spannungen abzubauen.",
          "Nutzen Sie Visualisierung zur Entspannung.",
          "Nehmen Sie sich Zeit, um sich in der Natur zu erholen.",
          "Lernen Sie, die Signale Ihres Körpers zu erkennen.",
          "Üben Sie sich in Dankbarkeit, um Emotionen auszugleichen.",
          "Nutzen Sie positive Affirmationen, um Ihr Selbstvertrauen zu stärken.",
          "Lernen Sie, ohne Schuldgefühle „Nein zu sagen.",
          "Üben Sie Achtsamkeit bei Ihren täglichen Aktivitäten.",
          "Machen Sie regelmäßig Pausen, um sich zu beruhigen.",
          "Erkennen Sie, dass Ihre Emotionen vorübergehend sind.",
          "Vertrauen Sie auf Ihre Intuition, wenn Sie Entscheidungen treffen.",
          "Lernen Sie, mit Erwartungen umzugehen, um Stress zu reduzieren.",
          "Üben Sie sich in Selbstmitgefühl.",
          "Selbstbewusste Kommunikationstechniken anwenden.",
          "Lernen Sie, schwierige Situationen ins rechte Licht zu rücken.",
          "Achten Sie auf Ihren Schlaf, um Ihre Emotionen zu regulieren.",
          "Beschäftigen Sie sich mit kreativen Aktivitäten, um Ihre Gefühle auszudrücken.",
          "Lernen Sie, sich selbst zu verzeihen und die Vergangenheit loszulassen.",
          "Nutzen Sie die Aufarbeitung, um negative Emotionen zu transformieren.",
          "Üben Sie sich im Problemlösen, um Stress abzubauen.",
          "Lernen Sie, sich auf die Gegenwart zu konzentrieren.",
          "Nutzen Sie soziale Unterstützung, damit Sie sich nicht einsam fühlen.",
          "Üben Sie sich in Geduld und Verständnis mit sich selbst.",
          "Lernen Sie, Ihre emotionalen Grenzen zu erkennen.",
          "Wenden Sie Stressbewältigungstechniken an, z. B. Gehen.",
          "Üben Sie sich in Achtsamkeit bei sozialen Interaktionen.",
          "Lernen Sie, Ihre Bedürfnisse klar zu äußern.",
          "Nutzen Sie Bücher, um zu lernen, wie Sie mit Ihren Emotionen umgehen können.",
          "Üben Sie sich täglich in Dankbarkeit.",
          "Lernen Sie, negative Gedanken loszulassen.",
          "Nutzen Sie Achtsamkeitsübungen, um sich zu beruhigen.",
          "Üben Sie Mitgefühl für andere.",
          "Lernen Sie, Ihre Emotionen in beruflichen Situationen zu kontrollieren.",
          "Verwenden Sie Atemtechniken, um Ihr Nervensystem zu beruhigen.",
          "Lernen Sie, sich auf die positiven Aspekte Ihres Lebens zu konzentrieren.",
          "Verwenden Sie Affirmationen, um Ihr Selbstvertrauen zu stärken.",
          "Üben Sie Achtsamkeit in Beziehungen.",
          "Lernen Sie, sich selbst zu verzeihen und weiterzugehen."
          ]
      ),
      Category(
        name: "Von KVT inspirierte Tipps",
        tips: [
          "Identifizieren Sie Ihre automatischen Gedanken, um Ihre Gefühle zu verstehen.",
          "Üben Sie die kognitive Umstrukturierung, um negative Gedanken zu ändern.",
          "Lernen Sie, kognitive Verzerrungen zu erkennen, um Ihre Wahrnehmung zu verbessern.",
          "Üben Sie sich in Entspannung, um Stress und Ängste abzubauen.",
          "Machen Sie tiefe Atemübungen, um den Geist zu beruhigen.",
          "Nutzen Sie die schrittweise Exposition, um Phobien zu überwinden.",
          "Entwickeln Sie Selbstbejahung, um Ihre Beziehungen zu verbessern.",
          "Lernen Sie, mit Wut umzugehen, indem Sie ihre Auslöser erkennen.",
          "Üben Sie Achtsamkeit, um präsenter zu sein.",
          "Erkennen Sie Ihre kognitiven Muster, um sie zu ändern.",
          "Lernen Sie, ohne Schuldgefühle „Nein zu sagen.",
          "Machen Sie Visualisierungsübungen, um sich zu motivieren.",
          "Führen Sie ein Gedankentagebuch, um Ihre Fortschritte zu verfolgen.",
          "Üben Sie Meditation, um Ihre Konzentration zu verbessern.",
          "Verwenden Sie positive Affirmationen, um Ihr Selbstvertrauen zu stärken.",
          "Lernen Sie, Ihre Gefühle auf konstruktive Weise auszudrücken.",
          "Machen Sie Problemlösungsübungen, um Ihre Anpassungsfähigkeit zu verbessern.",
          "Üben Sie sich in Dankbarkeit, um jeden Tag zu schätzen.",
          "Erkennen Sie katastrophale Gedanken, um sie neu zu ordnen.",
          "Verwenden Sie durchsetzungsfähige Kommunikationstechniken, um Beziehungen zu verbessern.",
          "Erstellen Sie einen Aktionsplan, um Hindernisse zu überwinden.",
          "Üben Sie Achtsamkeit beim Essen, um den Geschmack zu genießen.",
          "Üben Sie progressive Entspannung, um Ihre Muskeln zu entspannen.",
          "Lernen Sie, mit Konflikten konstruktiv umzugehen.",
          "Nutzen Sie Instrumente des Zeitmanagements, um Ihre Produktivität zu optimieren.",
          "Schaffen Sie sich einen Entspannungsraum, um sich zu verjüngen.",
          "Machen Sie Wechselatmungsübungen, um die Energie auszugleichen.",
          "Üben Sie eine geführte Meditation, um sich selbst zur Entspannung zu führen.",
          "Verwenden Sie positive Zitate, um sich zu motivieren.",
          "Lernen Sie, Ihre Emotionen zu erkennen, um besser mit ihnen umgehen zu können.",
          "Führen Sie ein Wohlfühltagebuch, um Ihre Fortschritte zu verfolgen.",
          "Üben Sie Achtsamkeit in Beziehungen, um die Kommunikation zu verbessern.",
          "Lernen Sie, Empathie zu entwickeln, um Beziehungen zu verbessern.",
          "Machen Sie Übungen zur Erfolgsvisualisierung, um sich zu motivieren.",
          "Üben Sie Achtsamkeit in jedem Moment, um präsent zu bleiben.",
          "Lernen Sie, mit starken Emotionen umzugehen, indem Sie sich ihnen schrittweise aussetzen.",
          "Schaffen Sie einen Raum, in dem Sie über Ihre Gefühle sprechen können.",
          "Machen Sie Dankbarkeitsübungen für kleine Momente, um jeden Augenblick zu schätzen.",
          "Gründen Sie eine Selbsthilfegruppe, um sich mit positiven Menschen zu umgeben.",
          "Lernen Sie, eine positive Einstellung zu entwickeln, um Herausforderungen zu meistern.",
          "Üben Sie Achtsamkeit in der Natur, um sich zu regenerieren."
          ]
      ),
    ];
  }

  // Helper methods for easy access
  static List<String> getCategoryNames() {
    return getAllCategories().map((category) => category.name).toList();
  }

  static Category? getCategoryByName(String name) {
    try {
      return getAllCategories().firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  static List<String> getTipsByCategory(String categoryName) {
    final category = getCategoryByName(categoryName);
    return category?.tips ?? [];
  }

  static int getTotalTipsCount() {
    return getAllCategories()
        .map((category) => category.tips.length)
        .reduce((a, b) => a + b);
  }

  static String getRandomTip() {
    final allCategories = getAllCategories();
    final randomCategory = (allCategories..shuffle()).first;
    final randomTip = (randomCategory.tips..shuffle()).first;
    return randomTip;
  }

  // Additional helper methods for the new categories
  static List<Category> getWellnessCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Healthy Habits and Routines",
      "Emotional Regulation",
      "Stress Management",
      "Mindfulness"
    ].contains(category.name)).toList();
  }

  static List<Category> getPerformanceCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Productivity and Focus",
      "Goal Setting and Achievement",
      "Cognitive Behavioral Techniques"
    ].contains(category.name)).toList();
  }

  static List<Category> getSocialCategories() {
    final categories = getAllCategories();
    return categories.where((category) => [
      "Social Connections and Relationships",
      "Positive Thinking and Gratitude"
    ].contains(category.name)).toList();
  }
}