class Category {
  final String name;
  final List<String> affirmation;

  Category({
    required this.name,
    required this.affirmation,
  });
}

class AffirmationData {
  static List<Category> getAllCategories() {
    return [
      Category(
        name: "Strength and Resilience",
        affirmation: [
          "I am stronger than any challenge I face.",
          "My resilience carries me through tough times.",
          "I rise above obstacles with ease.",
          "My inner strength is unbreakable.",
          "I am built to endure and thrive.",
          "I grow stronger with every step.",
          "My courage shines in every moment.",
          "I bounce back from anything life brings.",
          "I am a warrior of resilience and hope.",
          "My strength flows from deep within.",
          "I face difficulties with fearless grace.",
          "I am tough, capable, and steady.",
          "My spirit is resilient and bold.",
          "I overcome setbacks with confidence.",
          "I am rooted in unshakable strength.",
          "My power grows through every trial.",
          "I stand tall no matter the storm.",
          "I am resilient in mind and heart.",
          "My strength is my shield and my light.",
          "I adapt and conquer all challenges.",
          "I am a pillar of enduring courage.",
          "My resilience lifts me higher every day.",
          "I face life with unwavering strength.",
          "I am tougher than I ever imagined.",
          "My spirit bends but never breaks.",
          "I rise stronger after every fall.",
          "I am fueled by grit and determination.",
          "My strength empowers me to keep going.",
          "I am unshaken by life's ups and downs.",
          "My resilience is my superpower.",
          "I stand firm in my own power.",
          "I overcome with grace and might.",
          "I am a force of unbreakable will.",
          "My strength shines through adversity.",
          "I am built to weather any storm.",
          "I grow through every challenge I meet.",
          "My resilience is my steady anchor.",
          "I am bold, strong, and unstoppable.",
          "My inner fire fuels my endurance.",
          "I face the world with fearless strength.",
          "I am renewed by my own resilience.",
          "My power lies in my ability to rise.",
          "I am a rock of strength and calm.",
          "I conquer doubt with my steady heart.",
          "My resilience builds my brighter future.",
          "I am strong enough for anything.",
          "My courage defines who I am.",
          "I thrive through life's toughest moments.",
          "My strength is limitless and true.",
          "I am a pillar of strength, unshakeable in the face of change.",
          "Courage flows through me with every breath.",
          "With each challenge, I become stronger and more resilient.",
          "I choose to act with courage, even when fear whispers in my ear.",
          "My heart is a reservoir of courage, and today, I draw from its depths.",
          "I am capable of navigating through the storm.",
          "I am stronger than my challenges.",
          "I am capable of overcoming all obstacles.",
          "I have the inner strength needed to face anything.",
          "I easily find solutions to my problems.",
          "I am capable of growing and learning from my difficulties.",
          "I am worthy of happiness and success.",
          "I create the life I desire.",
          "I achieve my dreams, no matter the obstacles.",
          "I find inner peace even in difficult times.",
          "I face my fears and overcome them.",
          "I find beauty in small things, even in difficult times.",
          "I find joy every day.",
          "I take care of myself during difficult periods.",
          "I remain calm and centered in chaos.",
          "I forgive myself and give myself a second chance.",
          "I am capable of getting back up, no matter how many times I fall.",
          "I face uncertainty with courage.",
          "I remain true to myself, even in difficult times.",
          "I stay focused on my goals, no matter the circumstances.",
          "I remain optimistic, even when things seem impossible.",
          "I am patient and believe in myself.",
          "I am determined and courageous.",
          "I am strong and resilient.",
          "I am capable of staying positive and believing in a better future.",
          "I am grateful, even in difficult times.",
          "I am open and accept change.",
          "I face my fears with courage, no matter what happens around me.",
          "I am confident, I believe in my abilities.",
          "I am capable of giving love, even in difficult times.",
          "I possess the concentration and clarity needed to face any situation.",
          "Each challenge I face sharpens my mind and strengthens my determination.",
          "My thoughts are powerful, constructive, and aligned with my goals.",
          "I trust my intuition and intelligence to guide me toward good decisions.",
          "Each day that passes strengthens my mental strength.",
          "I trust my intuition and inner wisdom to guide me in every decision.",
          "I believe in my abilities and recognize the strength within me.",
          "Each challenge I face is an opportunity to deepen my self-confidence.",
          "I honor my feelings and trust the journey I am on.",
          "Each day that passes reinforces my self-confidence.",
          "I am resilient and ready to face whatever comes my way.",
          "I am the master of my destiny, and I create a future full of successes.",
          "Through perseverance, I will reach unsuspected heights.",
          "My positive attitude opens the way to success and fulfillment.",
          "My path is illuminated by confidence, I walk with assurance toward success."
        ],
      ),
      Category(
        name: "Rest and Renewal",
        affirmation: [
          "I allow myself to rest deeply and fully.",
          "My body renews itself with every breath.",
          "I am at peace when I rest.",
          "Sleep comes to me easily and naturally.",
          "I release the day and embrace calm rest.",
          "My mind unwinds with gentle ease.",
          "I am restored by the power of rest.",
          "Every moment of rest heals me.",
          "I surrender to peaceful, renewing sleep.",
          "My energy is replenished as I rest.",
          "I deserve time to recharge and relax.",
          "My body knows how to restore itself.",
          "I drift into rest with a quiet heart.",
          "Sleep wraps me in a warm embrace.",
          "I let go and trust in renewal.",
          "My rest is deep and rejuvenating.",
          "I wake up refreshed and full of life.",
          "I honor my need for restful moments.",
          "My spirit is renewed with every pause.",
          "I release tension and welcome peace.",
          "My rest is a gift to myself.",
          "I let go of stress and sink into rest.",
          "I am relaxed and at ease today.",
          "I wake up feeling whole and rested.",
          "My mind finds calm in quiet moments.",
          "Sleep renews my strength each night.",
          "I am at peace with slowing down.",
          "My rest brings me clarity and calm.",
          "I allow myself to unwind completely.",
          "My energy returns with every restful breath.",
          "Rest is my path to inner renewal.",
          "I let go of the day and rest easy.",
          "My body heals as I relax deeply.",
          "I am restored by the calm of night.",
          "Rest fills me with gentle strength.",
          "I drift into a peaceful, healing sleep.",
          "My renewal begins with every rest.",
          "I allow myself to rest without guilt.",
          "I am capable of rejuvenating through rest.",
          "I choose to take care of my body and mind.",
          "I am worthy of regular breaks to recharge.",
          "Rest is essential to my health and well-being.",
          "I release pressures and find inner peace.",
          "I am capable of creating a restful space in my daily life.",
          "I allow myself to slow down and appreciate each moment.",
          "I am at peace with my need for rest.",
          "I feel revitalized after each rest period.",
          "I choose to prioritize my emotional well-being.",
          "I am capable of recharging through meditation and relaxation.",
          "I am surrounded by calmness and serenity.",
          "I am grateful for every moment of silence.",
          "I am capable of renewing my energy through rest.",
          "I feel light and free after each break.",
          "I am in harmony with my natural rhythm.",
          "I choose to focus on the present.",
          "I am capable of creating a routine that favors rest.",
          "I am worthy of taking care of myself.",
          "I am capable of releasing physical and mental tension.",
          "I am surrounded by love and support in my rest.",
          "I am grateful for every moment of relaxation.",
          "I am capable of recharging through nature.",
          "I choose to live in simplicity and peace.",
          "I am at peace with my past and future.",
          "I am capable of creating an environment conducive to rest.",
          "I am proud of taking care of myself.",
          "I am capable of renewing my spirit through reading and learning.",
          "I am surrounded by people who support me in my rest.",
          "I choose to focus on love and gratitude.",
          "I am capable of rejuvenating through sleep.",
          "I am grateful for every moment of solitude.",
          "I am capable of creating a balanced life between rest and activity.",
          "I am worthy of giving myself time.",
          "I am capable of releasing others' expectations.",
          "I am surrounded by calmness and inner peace.",
          "I choose to live in flow and serenity.",
          "I am capable of renewing my body through gentle exercise.",
          "I am grateful for every moment of connection with myself.",
          "I am capable of creating a sacred space for rest.",
          "I am proud of my ability to recharge.",
          "I am surrounded by unconditional love in my rest.",
          "I choose to focus on my overall well-being.",
          "I am capable of rejuvenating through creativity.",
          "I am grateful for every moment of freedom.",
          "I am capable of creating a routine that favors renewal.",
          "I am worthy of living a life filled with peace and rest.",
          "I am capable of renewing my spirit through deep meditation.",
          "I am at peace with who I am and celebrate my rest."
        ],
      ),
      Category(
        name: "Purpose and achievement",
        affirmation: [
          "I am driven by a clear sense of purpose.",
          "Every step I take brings me closer to my goals.",
          "I achieve greatness with every effort.",
          "My purpose guides me with strength and clarity.",
          "I am capable of reaching my dreams.",
          "Success flows to me naturally and easily.",
          "I am focused on what matters most to me.",
          "My achievements reflect my hard work.",
          "I live with intention and purpose every day.",
          "I am unstoppable in pursuing my goals.",
          "My purpose fuels my passion and drive.",
          "I celebrate every milestone I reach.",
          "I am aligned with my life's true calling.",
          "My efforts lead to meaningful success.",
          "I am confident in my ability to achieve.",
          "I create my future with every action.",
          "My purpose shines through all I do.",
          "I am proud of how far I've come.",
          "I move forward with determination and joy.",
          "My goals are within my reach.",
          "I am inspired by my own potential.",
          "Success is my reward for perseverance.",
          "I live a life of purpose and impact.",
          "I am motivated to achieve my best.",
          "My dreams become reality through my actions.",
          "I am a force of positive change.",
          "I trust in my path to achievement.",
          "My purpose gives me endless energy.",
          "I conquer challenges with confidence.",
          "I am destined for great accomplishments.",
          "My focus turns dreams into victories.",
          "I am building a life I'm proud of.",
          "My purpose lights the way forward.",
          "I achieve what I set my mind to.",
          "I am resilient in pursuit of my goals.",
          "My success inspires me and others.",
          "I am on a journey of meaningful growth.",
          "I take bold steps toward my purpose.",
          "My achievements are a reflection of me.",
          "I am committed to my own greatness.",
          "My purpose empowers me every day.",
          "I turn obstacles into opportunities.",
          "I am worthy of all I aspire to achieve.",
          "My determination knows no limits.",
          "I am creating a legacy of purpose.",
          "Success is my natural outcome.",
          "I am fueled by passion and action.",
          "My goals align with my highest self.",
          "I thrive in the pursuit of my purpose.",
          "I am the architect of my achievements.",
          "I am aware of my purpose and embody it every day.",
          "My existence has a deep meaning and I discover it at every moment.",
          "I am capable of creating a life that reflects my true mission.",
          "I am proud of my achievements and celebrate them.",
          "I am aligned with my values and respect them.",
          "I am a person worthy of respect and admiration.",
          "I believe in my potential and fully realize it.",
          "I am capable of overcoming all challenges to achieve my goals.",
          "I am at peace with my past and look toward the future with confidence.",
          "I am a source of inspiration for myself and others.",
          "I choose to live a life filled with purpose and meaning.",
          "I am capable of making a positive impact in the world.",
          "I am proud of my progress and continue to grow.",
          "I am in harmony with my environment and respect it.",
          "I am capable of making informed decisions for my well-being.",
          "I am grateful for every opportunity to grow.",
          "I am capable of turning my dreams into reality.",
          "I am a creative and innovative person.",
          "I am capable of overcoming my fears and pursuing my goals.",
          "I am surrounded by people who support and inspire me.",
          "I choose to live each day with intention and a clear purpose.",
          "I am capable of creating a fulfilling life filled with meaning.",
          "I am proud of my talents and use them to help others.",
          "I am at peace with who I am and fully accept myself.",
          "I am capable of making choices that help me achieve my goals.",
          "I am a resilient person and overcome obstacles with courage.",
          "I am capable of creating an environment that fosters my accomplishment.",
          "I am grateful for every lesson I learn.",
          "I am capable of turning challenges into opportunities for growth.",
          "I am surrounded by love and support in my quest for meaning.",
          "I choose to live in gratitude and recognition.",
          "I am capable of creating a life that reflects my deep values.",
          "I am proud of my past achievements and continue to progress.",
          "I am in harmony with my intuition and follow it.",
          "I am capable of taking calculated risks to achieve my goals.",
          "I am grateful for every moment of inner peace.",
          "I am capable of making a lasting impact in my community.",
          "I am an authentic person and express myself without fear.",
          "I am capable of overcoming my limits and growing.",
          "I am surrounded by people who share my values.",
          "I choose to live each day with passion and enthusiasm.",
          "I am capable of creating a life filled with joy and happiness.",
          "I am proud of my progress and continue to push myself.",
          "I am at peace with my future and am confident.",
          "I am capable of turning my ideas into concrete reality.",
          "I am a creative person and find innovative solutions.",
          "I am capable of managing my emotions with serenity.",
          "I am surrounded by people who inspire and motivate me.",
          "I choose to live each day with intention and a deep sense of purpose.",
          "I am capable of creating a fulfilling life filled with accomplishment."
        ],
      ),
      Category(
        name: "Presence and Awareness",
        affirmation: [
          "I am fully present at this moment.",
          "My mind is clear and aware right now.",
          "I embrace the beauty of the present.",
          "I am grounded in the here and now.",
          "My awareness brings me peace.",
          "My breath anchors me to the present.",
          "I let go of the past and future.",
          "I am attentive to all that surrounds me.",
          "I am calm and present in my body.",
          "I find joy in this exact moment.",
          "My awareness grows with every breath.",
          "I am here, fully and completely.",
          "I release distractions and focus now.",
          "I am in tune with the present flow.",
          "My mind rests in this moment's stillness.",
          "I am aware of life's simple gifts.",
          "I live each second with intention.",
          "My presence is my power.",
          "I observe my thoughts with clarity.",
          "I am at peace with what is.",
          "My awareness lights up my world.",
          "I am present for myself and others.",
          "I savor the richness of this moment.",
          "My focus is sharp and steady now.",
          "I am awake to life's unfolding.",
          "I let go and simply be here.",
          "My presence brings me strength.",
          "I am mindful of every step I take.",
          "I am rooted in this moment's calm.",
          "I am open to the present's lessons.",
          "I see beauty in every glance.",
          "My awareness deepens my peace.",
          "I am engaged with life right now.",
          "My mind is quiet and attentive.",
          "I am alive with present energy.",
          "I cherish the stillness of now.",
          "My awareness flows like a river.",
          "I am here with love and focus.",
          "I notice the details of this moment.",
          "My presence heals and renews me.",
          "I am in harmony with the present.",
          "I am awake to my own existence.",
          "My breath keeps me in the now.",
          "I am fully aware and fully alive.",
          "I am fully present in every moment.",
          "I cultivate awareness of my thoughts and emotions.",
          "I am at peace with the present moment."
        ],
      ),
      Category(
        name: "Love and relations",
        affirmation: ["I am surrounded by love every day.",
          "My heart is open to deep connections.",
          "I attract loving and kind people into my life.",
          "I give and receive love effortlessly.",
          "My relationships are built on trust and care.",
          "I am worthy of unconditional love.",
          "I nurture the bonds that matter to me.",
          "Love flows freely in all my interactions.",
          "I am connected to those who lift me up.",
          "My life is rich with meaningful relationships.",
          "I radiate love and draw it back to me.",
          "I am a source of warmth and connection.",
          "I cherish the love I share with others.",
          "My heart is a magnet for kindness.",
          "I am deeply loved and appreciated.",
          "I build bridges of understanding with ease.",
          "Love is the foundation of my life.",
          "I am in harmony with those around me.",
          "I attract relationships that feel safe and true.",
          "My love for myself grows every day.",
          "I connect with others in a meaningful way.",
          "I am deserving of love in all its forms.",
          "My presence brings people closer together.",
          "I am grateful for the love in my life.",
          "I communicate with love and clarity.",
          "My connections are strong and supportive.",
          "I am open to giving and receiving affection.",
          "Love surrounds me like a warm embrace.",
          "I foster peace and love in every relationship.",
          "I am a beacon of love and compassion.",
          "My heart connects me to the world.",
          "I am worthy of deep, lasting bonds.",
          "I choose relationships that honor my spirit.",
          "Love guides my words and actions.",
          "I am linked to others through kindness.",
          "My life is full of loving souls.",
          "I am at ease in the presence of love.",
          "I attract people who value me deeply.",
          "My love strengthens every connection I have.",
          "I am a vessel of love and understanding.",
          "I cherish the unity I feel with others.",
          "My heart is open to new friendships.",
          "I am loved for being my true self.",
          "I create space for love to flourish.",
          "My relationships reflect mutual respect.",
          "I am connected to a web of love.",
          "I share my love generously and freely.",
          "I am worthy of closeness and care.",
          "My bonds with others bring me joy.",
          "Love is the heartbeat of my existence.",
          "I am worthy of deep and meaningful love.",
          "I deserve to be loved for who I am.",
          "I am surrounded by love and all is well.",
          "I let my intuition guide me toward true love.",
          "With every heartbeat, I send love into the universe and it returns amplified.",
          "I am ready to give and receive unconditional love.",
          "I am a magnet for love, attracting the right person to me.",
          "I radiate confidence, charm, and love.",
          "I am lovable and deserve the love I seek.",
          "I am a loving and attentive partner, attracting the same kind of person.",
          "My self-love automatically attracts love from others.",
          "I am fully ready to love and be loved unconditionally.",
          "I attract healthy and enriching relationships.",
          "The love I give is a reflection of the love I deserve.",
          "I am at peace with my past and it opens me to new possibilities.",
          "I am a creator of my own loving reality and I create it with love.",
          "Every day, the love within me grows and manifests in my life.",
          "I am capable of building a lasting and happy relationship.",
          "I choose to love deeply and unconditionally.",
          "I am a positive and loving person.",
          "I intend to always love and support my partner unconditionally.",
          "I choose to be kind and attentive to my partner.",
          "I can set boundaries for a stronger bond.",
          "I listen to my partner and am ready to make personal changes for them.",
          "I am ready to prioritize my relationship above other priorities.",
          "I always consider my partner's opinions and emotions.",
          "I focus on protecting my healthy relationships.",
          "I communicate with my partner with respect and understanding.",
          "I am in a lasting relationship.",
          "I have the ability to keep my relationship healthy and happy.",
          "I find it easy to commit to my partner.",
          "My love is seen and the universe rewards me for it.",
          "The person I love loves me back.",
          "I feel safe in a stable relationship.",
          "The universe prepares me for a lasting relationship.",
          "I let love enter my life.",
          "I feel surrounded by love everywhere.",
          "I receive abundant love from everyone I meet.",
          "I am grateful for the love I share with others.",
          "I celebrate the love I share with others and its transformative power.",
          "I am loving and lovable in my own way.",
          "I honor the strength and vulnerability that love brings.",
          "My love is fearless, limitless, and constantly evolving.",
          "I embrace the full spectrum of love, from silent whispers to great passions.",
          "I am joyful and loved in my current relationship.",
          "I am a reliable and loyal partner.",
          "I choose to see the best in my partner.",
          "I am capable of forgiving and moving forward.",
          "I cultivate patience and understanding in my relationship.",
          "I am proud of the love we share and celebrate it every day."
        ],
      ),
      Category(
        name: "Joy and Happiness",
        affirmation: [
          "I am filled with joy in every moment.",
          "Happiness flows through me effortlessly.",
          "I choose to see the beauty in everything.",
          "My heart sings with pure delight.",
          "I radiate joy to everyone around me.",
          "Today, I embrace happiness fully.",
          "I am grateful for the joy in my life.",
          "Laughter and lightness fill my days.",
          "I find happiness in the smallest things.",
          "My spirit dances with joy every day.",
          "I am a magnet for positive energy.",
          "Happiness is my natural state.",
          "I welcome joy with open arms.",
          "My life is overflowing with delight.",
          "I shine with the light of happiness.",
          "Every step I take is filled with joy.",
          "I am surrounded by reasons to smile.",
          "My heart is alive with happiness.",
          "I choose joy over worry every time.",
          "I am bursting with cheerful energy.",
          "Happiness grows within me each day.",
          "I see the world through joyful eyes.",
          "My soul is bathed in contentment.",
          "I am free to feel pure happiness.",
          "Joy bubbles up from deep within me.",
          "I celebrate life with every breath.",
          "I am a source of joy for myself and others.",
          "Happiness follows me wherever I go.",
          "I let go of sadness and embrace joy.",
          "My days are bright with positivity.",
          "I am alive with the thrill of happiness.",
          "Joy is the heartbeat of my life.",
          "I find delight in every new day.",
          "My mind is a garden of happy thoughts.",
          "I am uplifted by the joy within me.",
          "Happiness is my gift to the world.",
          "I smile easily and feel the joy.",
          "My life is a canvas of happy moments.",
          "I am in tune with the rhythm of joy.",
          "Every day brings me new happiness.",
          "I am wrapped in a blanket of delight.",
          "My laughter lights up my world.",
          "I choose to live in a state of joy.",
          "Happiness fills my heart to the brim.",
          "I am energized by life's joyful moments.",
          "My spirit soars with happiness.",
          "I am surrounded by love and joy.",
          "I find joy in simply being alive.",
          "My happiness inspires those around me.",
          "I am a vessel of endless joy.",
          "I am at peace with my past and confident for the future.",
          "I choose to let go of what no longer serves me.",
          "I am aligned with my true mission and passion.",
          "I am capable of creating a positive impact in the lives of others.",
          "I am proud of my achievements and celebrate them.",
          "I am safe and feel protected in every situation.",
          "I choose to see the world with optimism and hope.",
          "I am capable of finding joy in every moment.",
          "I am surrounded by people who inspire and support me.",
          "I am in harmony with the universe, and it guides me toward success.",
          "I am capable of bringing positive changes into my life.",
          "I choose to live in flow and peace.",
          "I am grateful for the beauty present in every moment.",
          "I am unique and contribute to the richness of the world.",
          "I am capable of creating a life filled with joy and happiness.",
          "I am surrounded by unconditional love and support.",
          "I choose to focus on love and gratitude.",
          "I am capable of managing my emotions with calmness and serenity.",
          "I am at peace with my emotions and accept them without judgment.",
          "I am proud of my progress and continue to grow.",
          "I am capable of finding joy in the challenges I overcome.",
          "I am surrounded by infinite possibilities and explore them with enthusiasm.",
          "I choose to live each day with gratitude and enthusiasm.",
          "I am capable of creating an environment that fosters my personal growth.",
          "I am in harmony with my heart and am guided by my intuition.",
          "I am at peace with who I am and celebrate my life with joy."
        ],
      ),
      Category(
        name: "Inner Peace and Calm",
        affirmation: [
          "I am at peace with myself and the world around me.",
          "Calmness flows through me like a gentle river.",
          "I release tension and embrace serenity now.",
          "My mind is still, and my heart is tranquil.",
          "I breathe in peace and exhale stress.",
          "I am grounded in this present moment.",
          "Every breath I take fills me with calm.",
          "I let go of worry and welcome peace.",
          "My inner calm grows stronger every day.",
          "I am surrounded by a soothing energy.",
          "Peace is my natural state of being.",
          "I choose tranquility over chaos.",
          "My thoughts are quiet and at ease.",
          "I am safe, relaxed, and at peace.",
          "I flow with life's rhythm effortlessly.",
          "Serenity fills every corner of my mind.",
          "I am free from anxiety and full of calm.",
          "My heart beats in harmony with peace.",
          "I release all that no longer serves my calm.",
          "I am a beacon of stillness and grace.",
          "Each moment brings me deeper peace.",
          "I trust in the calm within me.",
          "My spirit is quiet and content.",
          "I am centered and at ease always.",
          "Peace washes over me like a warm wave.",
          "I let go of fear and rest in calm.",
          "My mind is a sanctuary of tranquility.",
          "I am in harmony with all that is.",
          "Calmness is my strength and my refuge.",
          "I welcome peace into every part of my life.",
          "I am steady, serene, and balanced.",
          "My breath anchors me in peace.",
          "I release chaos and embrace stillness.",
          "I am calm even in challenging moments.",
          "Peace radiates from within me.",
          "I am gentle with myself and find calm.",
          "My soul rests in quiet confidence.",
          "I let go of haste and savor peace.",
          "I am at one with the calm of the universe.",
          "Serenity is my gift to myself today.",
          "I breathe out tension and breathe in calm.",
          "My inner world is peaceful and bright.",
          "I choose calm over conflict every time.",
          "I am surrounded by a bubble of peace.",
          "My mind rests easily in stillness.",
          "I am relaxed, present, and at peace.",
          "Calmness guides my every step.",
          "I find peace in simply being me.",
          "My heart is light and my mind is calm.",
          "I am an ocean of peace, deep and vast.",
          "I am at peace with myself and feel free to live my life as I choose.",
          "I trust the process of life to guide me.",
          "I manage my emotions with calmness and clarity.",
          "I choose to see the positive in every situation.",
          "I am at peace with my decisions and feel free.",
          "I allow myself time for self-care without guilt.",
          "I am open to new opportunities and welcome them with calmness.",
          "I am grateful for the lessons I learn each day.",
          "I create a peaceful inner space that nourishes my soul.",
          "I release judgments from others and focus on love.",
          "I am at peace with my past and my future.",
          "I choose to live simply and appreciate the beauty of life.",
          "I remain calm and centered in every situation.",
          "I trust my personal journey and am guided.",
          "I overcome challenges with calmness and confidence.",
          "I am surrounded by love and support in my life.",
          "I choose to let go of the need to control everything.",
          "I am at peace with the inevitable changes in life.",
          "I express my emotions freely without holding back.",
          "I am grateful for the joyful moments I share with others.",
          "I create a fulfilling and peaceful life.",
          "I feel safe and protected in every situation.",
          "I focus on love and gratitude.",
          "I am in harmony with the world around me.",
          "I find inner peace in every moment.",
          "I release stress and tension from my body.",
          "I am open to new experiences with calmness and curiosity.",
          "I am grateful for every moment of silence and meditation.",
          "I choose to live in flow and peace.",
          "I manage my thoughts with calmness and clarity.",
          "I am surrounded by people who support and love me.",
          "I am at peace with my emotions and accept them without judgment.",
          "I trust the universe to guide me toward inner peace.",
          "I create a peaceful environment around me.",
          "I choose to let go of others' expectations."
        ],
      ),
      Category(
        name: "Health and Vitality",
        affirmation: [
          "My body is strong and full of energy.",
          "I radiate health and vitality every day.",
          "I nourish myself with love and care.",
          "My energy flows freely and abundantly.",
          "I am in tune with my body's needs.",
          "Every breath fills me with life and strength.",
          "I am vibrant, healthy, and alive.",
          "My body heals and thrives naturally.",
          "I choose habits that support my well-being.",
          "I am full of vitality from head to toe.",
          "My health grows stronger with each day.",
          "I move with ease and confidence.",
          "I honor my body with rest and activity.",
          "My energy is boundless and bright.",
          "I am grateful for my strong, healthy body.",
          "I feel alive and powerful every moment.",
          "My wellness is a priority I cherish.",
          "I am in perfect harmony with my health.",
          "My body is a temple of vitality.",
          "I glow with the light of good health.",
          "I am energized by the life within me.",
          "My strength supports me in all I do.",
          "I embrace a life of vigor and wellness.",
          "My body responds to care with strength.",
          "I am thriving in mind, body, and spirit.",
          "My health is a gift I nurture daily.",
          "I feel refreshed and full of life.",
          "My vitality shines through every action.",
          "I am balanced and brimming with energy.",
          "My body is resilient and powerful.",
          "I choose foods that fuel my vitality.",
          "I am alive with wellness and joy.",
          "My health empowers me to live fully.",
          "I am strong, flexible, and free.",
          "My energy lifts me higher every day.",
          "I care for myself with love and intention.",
          "My body is a source of endless strength.",
          "I am vibrant in every cell of my being.",
          "My wellness radiates from within.",
          "I move through life with vigor and grace.",
          "My health is my foundation for happiness.",
          "I am renewed with every sunrise.",
          "My vitality grows with every step I take.",
          "I am in sync with my body's rhythm.",
          "My strength carries me through each day.",
          "I am a picture of health and energy.",
          "My body supports me with love and power.",
          "I feel fantastic and full of life.",
          "My vitality is my natural state.",
          "I am healthy, whole, and unstoppable.",
          "I breathe fully and freely.",
          "I overflow with health and vitality.",
          "I am filled with healing energy.",
          "I lead a balanced and healthy life.",
          "I feel in top physical and mental shape.",
          "From now on, I choose to be in good health.",
          "I enjoy taking care of myself and others.",
          "I deserve and allow myself to rest when needed.",
          "I consume foods that respect my body.",
          "I respect and value my body.",
          "Everything in me balances perfectly.",
          "My weight and vital signs normalize with ease.",
          "I allow myself to express my emotions and meet my needs.",
          "I am fully and joyfully myself.",
          "I relax and bring calmness into my life.",
          "I am flexible and become more gentle each day.",
          "Every day, in every way, I get better and better.",
          "I feel safe everywhere and at all times.",
          "I forgive myself and others, and offer peace.",
          "I now see the wonderful in everything.",
          "I change my perspective on my past, I am free.",
          "The energy of Life expresses itself joyfully through me.",
          "I can cultivate the best vitality.",
          "I send support and love to my body.",
          "My body can regenerate easily and naturally.",
          "I thank my body for all that works well.",
          "The more positivity I bring to my body, the better it can cultivate health.",
          "I deserve to be in good health and enjoy life.",
          "I love living vitality and overall well-being.",
          "I release anything that stands between me and perfect health.",
          "Good lifestyle habits help me cultivate the best form.",
          "Every part of my body has the power to improve.",
          "Every cell in my body can regenerate positively.",
          "My body is my best friend.",
          "I deserve to be in good health.",
          "I listen to my body's signals.",
          "I take time to care for my body.",
          "It's up to me to decide what a healthy body is.",
          "My mental and physical health are priorities.",
          "My illness does not define me.",
          "Priority to calmness and rest.",
          "I challenge myself physically.",
          "I celebrate small successes.",
          "I have enough courage to face my fears.",
          "Obstacles are my opportunities for growth.",
          "I will succeed in achieving my health goals.",
          "I am exactly where I need to be for my health.",
          "Each of my actions brings me closer to a healthier life.",
          "I succeed in everything I undertake for my health.",
          "Today, I give my best to my health."
        ],
      ),
      Category(
        name: "Confidence and Self-Worth",
        affirmation: [
          "I am confident in who I am.",
          "My worth shines brightly every day.",
          "I fully believe in my abilities.",
          "I am enough, just as I am.",
          "I stand tall in my own power.",
          "My confidence grows stronger each moment.",
          "I am worthy of all good things.",
          "I trust myself to make great choices.",
          "I am proud of all I have achieved.",
          "My value is infinite and unshakable.",
          "I radiate self-assurance effortlessly.",
          "I am deserving love and respect.",
          "I embrace my unique strengths.",
          "I am bold, capable, and strong.",
          "My self-worth is a gift I cherish.",
          "I am comfortable in my own skin.",
          "I honor the person I am becoming.",
          "I am worthy of my own praise.",
          "My confidence inspires those around me.",
          "I trust in my limitless potential.",
          "I am valuable beyond measure.",
          "I face every challenge with courage.",
          "My inner strength guides me forward.",
          "I celebrate who I am every day.",
          "I am confident in my unique journey.",
          "I deserve to take up space.",
          "I am a masterpiece of my own making.",
          "My self-belief is unbreakable.",
          "I am worthy of success and joy.",
          "I shine with unshakable confidence.",
          "I am enough, now and always.",
          "I trust myself to rise above doubt.",
          "My worth is not defined by others.",
          "I am powerful in my authenticity.",
          "I embrace my flaws and my brilliance.",
          "I am confident in every step.",
          "I am a gift to the world as I am.",
          "My self-worth grows with every breath.",
          "I am bold in pursuing my dreams.",
          "I respect and value myself deeply.",
          "I am worthy of all I desire.",
          "My confidence is my superpower.",
          "I am at peace with who I am.",
          "I trust my voice and my vision.",
          "I am deserving of every opportunity.",
          "I carry myself with pride and grace.",
          "My worth radiates from within me.",
          "I am confident, whole, and complete.",
          "I have confidence in myself and my abilities.",
          "I am capable of overcoming all challenges.",
          "I love and accept myself as I am.",
          "I am competent and talented.",
          "I trust my intuition.",
          "I am confident in the decisions I make.",
          "I value myself at my true worth.",
          "I am proud of my progress and achievements.",
          "I am in control of my thoughts and emotions.",
          "I am worthy of love and respect.",
          "I choose to focus on my strengths.",
          "I am unique and that makes me special.",
          "I fully accept myself with my imperfections.",
          "I am capable of creating a life that reflects who I am.",
          "I deserve success and happiness.",
          "I am at peace with who I am.",
          "I am courageous in the face of the unknown.",
          "I am exactly where I need to be.",
          "I am a trustworthy person.",
          "I am the master of my life.",
          "I deserve to take care of myself.",
          "I am proud of my perseverance.",
          "I choose to love myself more each day.",
          "I am capable of learning anything I want.",
          "I am superior to negative thoughts and actions.",
          "I see obstacles as opportunities for growth.",
          "I am confident in my choices.",
          "I am talented and intelligent.",
          "I express myself openly and honestly with confidence.",
          "I am comfortable with who I am.",
          "I do my best in every situation.",
          "I am proud of the path I have taken.",
          "I am in harmony with my values.",
          "I respect my inner nature.",
          "I am capable of achieving anything I want.",
          "I am worthy of being respected and appreciated.",
          "I choose to cultivate positive thoughts.",
          "I am at peace with my past.",
          "I confidently exceed my limits.",
          "I am a creative and unique person.",
          "I believe in my ability to overcome obstacles.",
          "I deserve to celebrate my successes.",
          "I allow myself to take risks.",
          "I am stronger than my fears.",
          "I am surrounded by supportive people.",
          "I choose to live with gratitude and confidence.",
          "I am courageous enough to speak my mind.",
          "I allow myself to be authentic.",
          "My potential is extraordinary.",
          "I am capable of creating positive changes in my life."
        ],
      ),
      Category(
        name: "Abundance and Gratitude",
        affirmation: [
          "I am grateful for the abundance in my life.",
          "My world is overflowing with goodness.",
          "I attract prosperity with every breath.",
          "I am thankful for all I have today.",
          "Abundance flows to me effortlessly.",
          "I am surrounded by limitless blessings.",
          "My heart is always full of gratitude.",
          "I see abundance in every moment.",
          "I am thankful for life's rich gifts.",
          "Prosperity is my natural state.",
          "I appreciate all that comes my way.",
          "My life is abundant in love and joy.",
          "I am open to receiving endless blessings.",
          "Gratitude fills me with peace.",
          "I am rich in spirit and in life.",
          "I thank the universe for its generosity.",
          "Abundance surrounds me every day.",
          "I am grateful for both big and small wins.",
          "My life is a treasure of abundance.",
          "I welcome prosperity with open arms.",
          "I am thankful for the beauty around me.",
          "My gratitude attracts more to cherish.",
          "I live in a state of abundant joy.",
          "I am blessed beyond measure.",
          "My heart overflows with appreciation.",
          "Abundance is mine to claim now.",
          "I give thanks for every new day.",
          "My life is full of endless possibilities.",
          "I am grateful for my strength and growth.",
          "Prosperity flows through all I do.",
          "I appreciate the richness of my journey.",
          "My gratitude creates more abundance.",
          "I thank life for its constant support.",
          "My world is abundant with opportunity.",
          "I am grateful for my unique gifts.",
          "Abundance comes to me in many forms.",
          "My thankful heart draws in more good.",
          "I live with a sense of plentiful peace.",
          "I am rich in all that truly matters.",
          "I give thanks for the present moment.",
          "My life is a garden of abundance.",
          "I am open to all the universe offers.",
          "Gratitude is the key to my wealth.",
          "I am prosperous in mind and spirit.",
          "I appreciate the love that fills my life.",
          "My abundance grows with every step.",
          "I am thankful for all I am becoming.",
          "I see blessings in every corner.",
          "My gratitude opens doors to more.",
          "I am grateful for every smile I see.",
          "I am open to all forms of abundance that enter my life.",
          "I am grateful for the laughter I share with others.",
          "I am grateful for every new day that begins.",
          "I am capable of sharing my abundance with generosity.",
          "I am grateful for the moments of deep connection with others.",
          "Abundance is an integral part of my daily life.",
          "I am grateful for the talents I possess.",
          "I am surrounded by abundance in my thoughts and actions.",
          "I am grateful for every act of kindness I receive.",
          "I am capable of creating a rich and fulfilling life.",
          "I am grateful for the opportunities for personal growth.",
          "I am surrounded by abundance in my work and projects.",
          "I am grateful for every moment of freedom I experience.",
          "I am open to receiving abundance with humility.",
          "I am grateful for the wise advice I receive.",
          "I am surrounded by abundance in my dreams and aspirations.",
          "I am grateful for every moment of creativity I experience.",
          "I am capable of seeing abundance in every situation.",
          "I am grateful for the experiences that have made me stronger.",
          "I am surrounded by abundance in my positive thoughts.",
          "I am grateful for every person who believes in me.",
          "I am capable of sharing my abundance with love.",
          "I am grateful for the moments of silence and meditation.",
          "I am surrounded by abundance in my home and environment.",
          "I am grateful for every act of solidarity I see.",
          "I am capable of creating a life filled with abundance and joy.",
          "I am grateful for the lessons I learn every day.",
          "I am surrounded by abundance in my loving relationships.",
          "I am grateful for every moment of inner peace I feel."
        ],
      ),
    ];
  }

  // Helper methods for easy access
  static List<String> getCategoryNames() {
    return getAllCategories().map((category) => category.name).toList();
  }

  static Category? getCategoryByName(String name) {
    try {
      return getAllCategories().firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  static List<String> getAffirmationByCategory(String categoryName) {
    final category = getCategoryByName(categoryName);
    return category?.affirmation ?? [];
  }

  static int getTotalAffirmationCount() {
    return getAllCategories()
        .map((category) => category.affirmation.length)
        .reduce((a, b) => a + b);
  }

  static String getRandomAffirmation() {
    final allCategories = getAllCategories();
    final randomCategory = (allCategories..shuffle()).first;
    final randomTip = (randomCategory.affirmation..shuffle()).first;
    return randomTip;
  }
}