
import 'AffirmationData.dart';

class AffirmationDataFR {
  static List<Category> getAllCategories() {
    return [
      Category(
        name: "Force et résilience",
        affirmation: [

        ],
      ),
      Category(
        name: "Rest and Renewal",
        affirmation: [
          'Estoy rodeado de abundancia y riqueza en todos los aspectos de mi vida.',
          'Estoy agradecido por cada momento de felicidad que vivo.',
          'La abundancia me rodea y me sostiene cada día.',
          'Soy capaz de recibir y compartir la abundancia con alegría.',
          'Estoy agradecido por las personas amorosas en mi vida.',
          'Cultivo la gratitud por todo lo que poseo.',
          'La abundancia es una parte natural de mi existencia.',
          'Estoy agradecido por mi salud y bienestar.',
          'Elijo ver la abundancia en todos los lugares a donde voy.',
          'Estoy agradecido por las oportunidades que se me presentan.',
          'Estoy abierto a recibir la abundancia en todas sus formas.',
          'Estoy agradecido por la belleza de la naturaleza.',
          'Estoy rodeado de personas que me ayudan a crecer.',
          'Estoy agradecido por cada lección que recibo.',
          'La abundancia es una energía que fluye libremente en mi vida.',
          'Estoy agradecido por los momentos de paz que experimento.',
          'Soy capaz de crear abundancia a través de mis pensamientos positivos.',
          'Estoy agradecido por las experiencias enriquecedoras que vivo.',
          'Estoy rodeado de abundancia espiritual y material.',
          'Estoy agradecido por cada sonrisa que veo.',
          'Estoy abierto a todas las formas de abundancia que entran en mi vida.',
          'Estoy agradecido por las risas que comparto con los demás.',
          'Estoy rodeado de abundancia en mis relaciones.',
          'Estoy agradecido por cada nuevo día que comienza.',
          'Soy capaz de compartir mi abundancia con generosidad.',
          'Estoy agradecido por los momentos de conexión profunda con los demás.',
          'La abundancia es una parte integral de mi vida diaria.',
          'Estoy agradecido por los talentos que poseo.',
          'Estoy rodeado de abundancia en mis pensamientos y acciones.',
          'Estoy agradecido por cada acto de bondad que recibo.',
          'Soy capaz de crear una vida rica y plena.',
          'Estoy agradecido por las oportunidades de crecimiento personal.',
          'Estoy rodeado de abundancia en mi trabajo y proyectos.',
          'Estoy agradecido por cada instante de libertad que experimento.',
          'Estoy abierto a recibir la abundancia con humildad.',
          'Estoy agradecido por los consejos sabios que recibo.',
          'Estoy rodeado de abundancia en mis sueños y aspiraciones.',
          'Estoy agradecido por cada momento de creatividad que vivo.',
          'Estoy agradecido por las experiencias que me han hecho más fuerte.',
          'Estoy rodeado de abundancia y pensamientos positivos.',
          'Estoy agradecido por cada persona que cree en mí.',
          'Soy capaz de compartir mi abundancia con amor.',
          'Estoy agradecido por los momentos de silencio y meditación.',
          'Estoy rodeado de abundancia en mi hogar y entorno.',
          'Estoy agradecido por cada acto de solidaridad que veo.',
          'Soy capaz de crear una vida llena de abundancia y alegría.',
          'Estoy agradecido por las lecciones que aprendo cada día.',
          'Estoy rodeado de abundancia en mis relaciones amorosas.',
          'Estoy agradecido por cada momento de paz interior que siento.',
        ]

      ),
      Category(
        name: "Raison d'être et accomplissement",
        affirmation: [
          'Je suis conscient de ma raison d\'être et je l\'incarne chaque jour.',
          'Mon existence a un sens profond et je le découvre à chaque instant.',
          'Je suis capable de créer une vie qui reflète ma véritable mission.',
          'Je suis fier de mes réalisations et je les célèbre.',
          'Je suis aligné avec mes valeurs et je les respecte.',
          'Je suis une personne digne de respect et d\'admiration.',
          'Je crois en mon potentiel et je le réalise pleinement.',
          'Je suis capable de surmonter tous les défis pour atteindre mes objectifs.',
          'Je suis en paix avec mon passé et je regarde vers l\'avenir avec confiance.',
          'Je suis une source d\'inspiration pour moi-même et pour les autres.',
          'Je choisis de vivre une vie remplie de sens et de but.',
          'Je suis capable de créer un impact positif dans le monde.',
          'Je suis fier de mes progrès et je continue à grandir.',
          'Je suis en harmonie avec mon environnement et je le respecte.',
          'Je suis capable de prendre des décisions éclairées pour mon bien-être.',
          'Je suis reconnaissant pour chaque opportunité de grandir.',
          'Je suis capable de transformer mes rêves en réalité.',
          'Je suis une personne créative et innovante.',
          'Je suis capable de surmonter mes peurs et de poursuivre mes objectifs.',
          'Je suis entouré de personnes qui me soutiennent et m\'inspirent.',
          'Je choisis de vivre chaque jour avec intention et avec un but clair.',
          'Je suis capable de créer une vie épanouissante et remplie de sens.',
          'Je suis fier de mes talents et je les utilise pour aider les autres.',
          'Je suis en paix avec qui je suis et je m\'accepte pleinement.',
          'Je suis capable de faire des choix qui m\'aident à atteindre mes objectifs.',
          'Je suis une personne résiliente et je surmonte les obstacles avec courage.',
          'Je suis capable de créer un environnement qui favorise mon accomplissement.',
          'Je suis reconnaissant pour chaque leçon que j\'apprends.',
          'Je suis capable de transformer mes défis en opportunités de croissance.',
          'Je suis entouré d\'amour et de soutien dans ma quête de sens.',
          'Je choisis de vivre dans la gratitude et la reconnaissance.',
          'Je suis capable de créer une vie qui reflète mes valeurs profondes.',
          'Je suis fier de mes réalisations passées et je continue à progresser.',
          'Je suis en harmonie avec mon intuition et je la suis.',
          'Je suis capable de prendre des risques calculés pour atteindre mes objectifs.',
          'Je suis reconnaissant pour chaque moment de paix intérieure.',
          'Je suis capable de créer un impact durable dans ma communauté.',
          'Je suis une personne authentique et je m\'exprime sans crainte.',
          'Je suis capable de surmonter mes limites et de grandir.',
          'Je suis entouré de personnes qui partagent mes valeurs.',
          'Je choisis de vivre chaque jour avec passion et enthousiasme.',
          'Je suis capable de créer une vie remplie de joie et de bonheur.',
          'Je suis fier de mes progrès et je continue à me dépasser.',
          'Je suis en paix avec mon avenir et je suis confiant.',
          'Je suis capable de transformer mes idées en réalité concrète.',
          'Je suis une personne créative et je trouve des solutions innovantes.',
          'Je suis capable de gérer mes émotions avec sérénité.',
          'Je suis entouré de personnes qui m\'inspirent et me motivent.',
          'Je choisis de vivre chaque jour avec intention et avec un sens profond.',
          'Je suis capable de créer une vie épanouissante et remplie d\'accomplissement.',
        ]

      ),
      Category(
        name: "Présence et conscience",
        affirmation: [
          'Je suis pleinement présent dans chaque instant.',
          'Je cultive la conscience de mes pensées et de mes émotions.',
          'Je suis en paix avec le moment présent.',
          'Je choisis de vivre en pleine conscience.',
          'Je suis capable de me concentrer sur mon souffle.',
          'Je suis connecté à mon corps et à mes sensations.',
          'Je suis en harmonie avec mon environnement.',
          'Je suis reconnaissant pour chaque moment de vie.',
          'Je suis capable de lâcher prise sur le passé et le futur.',
          'Je suis pleinement engagé dans l\'instant présent.',
          'Je cultive la bienveillance envers moi-même.',
          'Je suis capable de gérer mes pensées avec sérénité.',
          'Je suis en paix avec mes émotions et je les accueille sans jugement.',
          'Je choisis de voir la beauté dans chaque moment.',
          'Je suis capable de créer un espace de calme intérieur.',
          'Je suis connecté à mon intuition et je la suis.',
          'Je suis en sécurité dans le présent.',
          'Je suis capable de transformer mes pensées négatives en positives.',
          'Je cultive la gratitude pour chaque instant de vie.',
          'Je suis pleinement conscient de mes choix.',
          'Je choisis de vivre avec intention et conscience.',
          'Je suis capable de créer un environnement paisible autour de moi.',
          'Je suis en harmonie avec mon rythme naturel.',
          'Je suis reconnaissant pour chaque leçon que j\'apprends.',
          'Je suis capable de me libérer des distractions.',
          'Je suis pleinement présent dans mes relations.',
          'Je cultive la compassion envers moi-même et les autres.',
          'Je suis capable de gérer mes émotions avec calme.',
          'Je suis en paix avec mon passé et mon avenir.',
          'Je suis capable de créer une vie épanouissante.',
          'Je choisis de voir le positif dans chaque situation.',
          'Je suis connecté à mon corps et à ses besoins.',
          'Je suis en sécurité dans mon environnement.',
          'Je suis capable de transformer mes défis en opportunités.',
          'Je cultive la patience et la compréhension.',
          'Je suis pleinement conscient de mes pensées et de mes actions.',
          'Je choisis de vivre dans la simplicité et la paix.',
          'Je suis capable de créer un espace de détente intérieure.',
          'Je suis en harmonie avec la nature.',
          'Je suis reconnaissant pour chaque moment de silence.',
          'Je suis capable de me concentrer sur le présent.',
          'Je cultive la bienveillance envers les autres.',
          'Je suis en paix avec mes limites.',
          'Je suis capable de transformer mes peurs en courage.',
          'Je choisis de voir la beauté dans chaque personne.',
          'Je suis connecté à mon cœur et à ses désirs.',
          'Je suis en sécurité dans mes relations.',
          'Je suis capable de créer une vie remplie de sens.',
          'Je cultive la gratitude pour chaque instant de connexion avec les autres.',
          'Je suis pleinement présent dans chaque expérience de vie.',
        ]

      ),
      Category(
        name: "Amour et relations",
        affirmation: [
          'Je suis digne d\'un amour profond et significatif.',
          'Je mérite d\'être aimé pour qui je suis.',
          'Je laisse mon intuition me guider vers le véritable amour.',
          'Avec chaque battement du cœur, j\'envoie de l\'amour dans l\'univers et il me revient amplifié.',
          'Je suis prêt à donner et à recevoir de l\'amour inconditionnellement.',
          'Je suis un aimant d’amour, attirant les bonnes personnes vers moi.',
          'Je rayonne de confiance, de charme et d\'amour.',
          'Je suis aimable et mérite l\'amour que je cherche.',
          'Je suis un partenaire aimant et attentionné, attirant le même type de personne.',
          'Mon amour-propre attire l\'amour des autres.',
          'Je suis entièrement prêt à aimer et à être aimé(e) inconditionnellement.',
          'J\'attire des relations saines et enrichissantes.',
          'L\'amour que je donne est un reflet de l\'amour que je mérite.',
          'Je suis en paix avec mon passé et cela m\'ouvre à de nouvelles possibilités.',
          'Je suis le créateur de ma propre réalité amoureuse et je la crée avec passion.',
          'Chaque jour, l\'amour en moi grandit et se manifeste dans ma vie.',
          'Je suis capable de construire une relation durable et heureuse.',
          'Je choisis d\'aimer profondément et sans condition.',
          'Je suis une personne positive et aimante.',
          'Je prévois de toujours aimer et soutenir mon partenaire de manière inconditionnelle.',
          'Je choisis d\'être gentil et attentionné envers mon conjoint.',
          'Je peux dessiner des limites pour un lien plus fort.',
          'J\'écoute mon partenaire et je suis prêt à apporter des changements personnels pour lui.',
          'Je suis prêt à placer ma relation au-dessus des autres priorités.',
          'Je prends toujours en compte les opinions et les émotions de mon partenaire.',
          'Je me concentre sur la protection de mes relations saines.',
          'Je communique toujours avec mon partenaire avec respect et compréhension.',
          'Je suis dans une relation durable.',
          'J\'ai la capacité de garder ma relation saine et heureuse.',
          'Je trouve facile de m\'engager envers mon partenaire.',
          'Mon amour est visible et l\'univers m\'en récompensera.',
          'La personne que j\'aime m\'aime aussi en retour.',
          'Je me sens en sécurité dans une relation stable.',
          'L\'univers me prépare à une relation durable.',
          'Je laisse l\'amour entrer dans ma vie.',
          'Je me sens entouré d\'amour partout.',
          'Je reçois de l\'amour en abondance de tous ceux que je rencontre.',
          'Je suis reconnaissant pour l\'amour qu’on me partage.',
          'Je célèbre l\'amour que je partage avec les autres et son pouvoir de transformation.',
          'Je suis aimant et aimable à ma façon.',
          'J\'honore la force et la vulnérabilité que l\'amour apporte.',
          'Mon amour est sans peur, sans limite et en constante évolution.',
          'J\'embrasse tout le spectre de l\'amour, des chuchotements silencieux aux grandes passions.',
          'Je suis joyeux et aimé dans ma relation actuelle.',
          'Je suis un partenaire fiable et loyal.',
          'Je choisis de voir le meilleur en mon partenaire.',
          'Je suis capable de pardonner et de passer à autre chose.',
          'Je cultive la patience et la compréhension dans ma relation.',
          'Je suis fier de l\'amour que nous partageons et je le célèbre chaque jour.',
          ]

      ),
      Category(
        name: "Joie et bonheur",
        affirmation: [
          'Je suis rempli de joie et de bonheur au quotidien.',
          'Je choisis de voir le positif dans chaque situation.',
          'Je suis reconnaissant pour chaque moment de bonheur que je vis.',
          'Je cultive la joie dans mes pensées et mes actions.',
          'Je suis entouré d\'amour et de soutien dans ma vie.',
          'Je mérite le bonheur et je le cultive avec gratitude.',
          'Je suis capable de trouver la joie dans les petites choses.',
          'Je suis en paix avec moi-même et je me sens libre.',
          'Je choisis de vivre dans la simplicité et la beauté de la vie.',
          'Je suis fier de qui je suis et de ce que j\'accomplis.',
          'Je suis ouvert aux nouvelles expériences et aux opportunités.',
          'Je suis reconnaissant pour les leçons que j\'apprends chaque jour.',
          'Je suis entouré d\'abondance et de possibilités infinies.',
          'Je choisis de sourire même lorsque les temps sont difficiles.',
          'Je suis capable de créer ma propre réalité positive.',
          'Je suis en harmonie avec le monde qui m\'entoure.',
          'Je suis responsable de mon propre bonheur.',
          'Je fais des choix qui nourrissent et soutiennent ma santé.',
          'Je suis une source d\'inspiration pour moi-même et pour les autres.',
          'Je suis capable de prendre des décisions éclairées pour mon bien-être.',
          'Je suis reconnaissant pour chaque instant de silence et de méditation.',
          'Je choisis de vivre dans la gratitude et la joie.',
          'Je suis entouré d\'amour et de positivité.',
          'Je suis capable de surmonter tous les défis qui se présentent à moi.',
          'Je suis en paix avec mon passé et confiant pour l\'avenir.',
          'Je choisis de laisser aller ce qui ne me sert plus.',
          'Je suis aligné avec ma véritable mission et passion.',
          'Je suis capable de créer un impact positif dans la vie des autres.',
          'Je suis fier de mes réalisations et je les célèbre.',
          'Je suis en sécurité et je me sens protégé dans chaque situation.',
          'Je choisis de voir le monde avec optimisme et espoir.',
          'Je suis capable de trouver la joie dans chaque moment.',
          'Je suis entouré de personnes qui m\'inspirent et me soutiennent.',
          'Je suis en harmonie avec l\'univers, et il me guide vers la réussite.',
          'Je suis capable d\'apporter des changements positifs dans ma vie.',
          'Je choisis de vivre dans la fluidité et la paix.',
          'Je suis reconnaissant pour la beauté présente dans chaque moment.',
          'Je suis unique et je contribue à la richesse du monde.',
          'Je suis capable de créer une vie remplie de joie et de bonheur.',
          'Je suis entouré d\'amour inconditionnel et de soutien.',
          'Je choisis de me concentrer sur l\'amour et la gratitude.',
          'Je suis capable de gérer mes émotions avec calme et sérénité.',
          'Je suis en paix avec mes émotions et je les accueille sans jugement.',
          'Je suis fier de mes progrès et je continue à grandir.',
          'Je suis capable de trouver la joie dans les défis que je surmonte.',
          'Je suis entouré de possibilités infinies et je les explore avec enthousiasme.',
          'Je choisis de vivre chaque jour avec gratitude et enthousiasme.',
          'Je suis capable de créer un environnement qui favorise ma croissance personnelle.',
          'Je suis en harmonie avec mon cœur et je suis guidé par mon intuition.',
          'Je suis en paix avec qui je suis et je célèbre ma vie avec joie.',
        ]

      ),
      Category(
        name: "Paix intérieure et calme",
        affirmation:[
          'Je suis en paix avec moi-même et avec le monde qui m\'entoure.',
          'Mon esprit est calme, paisible et centré.',
          'Je choisis de laisser aller les choses que je ne peux pas contrôler.',
          'Je suis ancré dans le présent et je trouve la paix intérieure.',
          'Je fais confiance à mon intuition pour me guider vers la sérénité.',
          'Je suis capable de créer le calme en moi à chaque instant.',
          'Je relâche mes muscles tranquillement et je me sens détendu.',
          'Je choisis de vivre dans l\'amour et la compassion.',
          'Je suis reconnaissant pour chaque moment de paix que je vis.',
          'Je lâche prise sur les regrets du passé et je me permets d\'avancer.',
          'Je me libère des pensées négatives et je cultive la paix intérieure.',
          'Je suis en harmonie avec moi-même et avec la nature.',
          'Je me concentre sur le présent et j\'abandonne le passé.',
          'Je suis entouré de calme et de sérénité dans mon environnement.',
          'Je fais confiance au processus de la vie pour me guider.',
          'Je suis capable de gérer mes émotions avec calme et sérénité.',
          'Je choisis de voir le positif dans chaque situation.',
          'Je suis en paix avec mes décisions et je me sens libre.',
          'Je me permets de prendre du temps pour moi sans culpabilité.',
          'Je suis ouvert aux nouvelles opportunités et je les accueille avec calme.',
          'Je suis reconnaissant pour les leçons que j\'apprends chaque jour.',
          'Je suis capable de créer un espace intérieur de paix et de sérénité.',
          'Je me libère des jugements des autres et je me concentre sur l\'amour.',
          'Je suis en paix avec mon passé et mon avenir.',
          'Je choisis de vivre dans la simplicité et la beauté de la vie.',
          'Je suis calme et centré dans chaque situation.',
          'Je fais confiance à mon voyage personnel et je suis guidé.',
          'Je suis capable de surmonter les défis avec calme et confiance.',
          'Je suis entouré d\'amour et de soutien dans ma vie.',
          'Je choisis de lâcher prise sur le besoin de tout contrôler.',
          'Je suis en paix avec les changements inévitables de la vie.',
          'Je me permets d\'exprimer mes émotions sans les retenir.',
          'Je suis reconnaissant pour les moments de joie que je partage avec les autres.',
          'Je suis capable de créer une vie épanouie et paisible.',
          'Je suis en sécurité et je me sens protégé dans chaque situation.',
          'Je choisis de me concentrer sur l\'amour et la gratitude.',
          'Je suis en harmonie avec le monde qui m\'entoure.',
          'Je suis capable de trouver la paix intérieure à chaque instant.',
          'Je me libère des tensions et des préoccupations.',
          'Je suis ouvert à de nouvelles expériences avec calme et curiosité.',
          'Je suis reconnaissant pour chaque instant de silence et de méditation.',
          'Je choisis de vivre dans la fluidité et la paix.',
          'Je suis capable de gérer mes pensées avec calme et clarté.',
          'Je suis entouré de personnes qui me soutiennent et m\'aiment.',
          'Je suis en paix avec mes émotions et je les accueille sans jugement.',
          'Je fais confiance à l\'univers pour me guider vers la paix intérieure.',
          'Je suis capable de créer un environnement paisible autour de moi.',
          'Je choisis de lâcher prise sur les attentes des autres.',
          'Je suis en paix avec moi-même et je me sens libre de vivre ma vie comme je l\'entends.',
        ]

      ),
      Category(
        name: "Santé et vitalité",
        affirmation: [
          'Je respire pleinement et librement.',
          'Je déborde de santé et de vitalité.',
          'Je suis rempli(e) d\'énergie de guérison.',
          'Je mène une vie saine et équilibrée.',
          'Je me sens en pleine forme physique et mentale.',
          'Désormais, je choisis d\'être en bonne santé.',
          'Je prends plaisir à prendre soin de moi et des autres.',
          'Je mérite et je m\'autorise à me reposer quand j\'en ai besoin.',
          'Je consomme des aliments qui respectent mon corps.',
          'Je respecte et je valorise mon corps.',
          'Tout en moi s\'équilibre à la perfection.',
          'Mon poids et mes constantes se normalisent avec fluidité.',
          'Je m\'autorise à exprimer mes émotions et à satisfaire mes besoins.',
          'Je suis pleinement et joyeusement moi-même.',
          'Je me détends et j\'installe le calme en moi.',
          'Je suis flexible et je m\'adoucisse chaque jour.',
          'Tous les jours, à tous points de vue, je vais de mieux en mieux.',
          'Je me sens en sécurité partout et tout le temps.',
          'Je me pardonne et je pardonne aux autres, et je nous offre la paix.',
          'Je vois désormais le merveilleux en toute chose.',
          'Je change mon regard sur mon passé, je me libère.',
          'L\'énergie de Vie s\'exprime joyeusement à travers moi.',
          'Je peux cultiver la meilleure vitalité.',
          'J\'envoie du soutien et de l\'amour à mon corps.',
          'Mon corps peut se régénérer facilement et naturellement.',
          'Je remercie mon corps pour tout ce qui fonctionne bien.',
          'Plus j\'apporte du positif à mon corps, plus il me récompense.',
          'Je mérite d\'être en bonne santé et de profiter de la vie.',
          'J\'aime vivre la vitalité et le bien-être global.',
          'Je me libère de tout ce qui se tient entre moi et une santé parfaite.',
          'Une bonne hygiène de vie m\'aide à cultiver une meilleure forme.',
          'Chaque partie de mon corps a le pouvoir d\'aller mieux.',
          'Chaque cellule de mon corps peut se régénérer positivement.',
          'Mon corps est mon meilleur ami.',
          'Je mérite d\'être en bonne santé.',
          'J\'écoute les signaux de mon corps.',
          'Je prends du temps pour prendre soin de mon corps.',
          'C\'est à moi de décider ce qu\'est un corps sain.',
          'Ma santé mentale et physique sont prioritaires.',
          'Priorité au calme et au repos.',
          'Je me mets au défi physiquement.',
          'Je célèbre les petits succès.',
          'J\'ai assez de courage pour affronter mes peurs.',
          'Les obstacles sont mes opportunités pour progresser.',
          'Je vais réussir à atteindre mes objectifs de santé.',
          'Je suis exactement là où je dois être pour ma santé.',
          'Chacune de mes actions me rapproche d\'une vie plus saine.',
          'J\'ai du succès dans tout ce que j\'entreprends pour ma santé.',
          'Aujourd\'hui, je donne le meilleur de moi-même pour ma santé.',
        ]

      ),
      Category(
        name: "Confiance et estime de soi",
        affirmation: [
          'J\'ai confiance en moi et en mes capacités.',
          'Je suis capable de surmonter tous les défis.',
          'Je m\'aime et je m\'accepte tel que je suis.',
          'Je suis compétent et talentueux.',
          'Je fais confiance à mon intuition.',
          'Je suis confiant dans les décisions que je prends.',
          'Je m\'estime à ma juste valeur.',
          'Je suis fier de mes progrès et de mes réalisations.',
          'Je suis en contrôle de mes pensées et de mes émotions.',
          'Je suis digne d\'amour et de respect.',
          'Je choisis de me concentrer sur mes forces.',
          'Je suis unique et cela me rend spécial.',
          'Je m\'accepte pleinement avec mes imperfections.',
          'Je suis capable de créer une vie qui me ressemble.',
          'Je mérite le succès et le bonheur.',
          'Je suis en paix avec qui je suis.',
          'Je suis courageux face à l\'inconnu.',
          'Je suis exactement là où je dois être.',
          'Je suis une personne digne de confiance.',
          'Je suis maître de ma vie.',
          'Je mérite de prendre soin de moi.',
          'Je suis fier de ma persévérance.',
          'Je choisis de m\'aimer chaque jour davantage.',
          'Je suis capable d\'apprendre tout ce que je veux.',
          'Je suis supérieur aux pensées et aux actions négatives.',
          'Je vois les obstacles comme des opportunités de grandir.',
          'Je suis confiant dans mes choix.',
          'Je suis talentueux et intelligent.',
          'Je m\'exprime ouvertement et honnêtement avec confiance.',
          'Je suis à l\'aise avec qui je suis.',
          'Je fais de mon mieux en toute circonstance.',
          'Je suis fier du chemin parcouru.',
          'Je suis en harmonie avec mes valeurs.',
          'Je respecte ma nature profonde.',
          'Je suis capable de réaliser tout ce que je veux.',
          'Je suis digne d\'être respecté et apprécié.',
          'Je choisis de cultiver des pensées positives.',
          'Je suis en paix avec mon passé.',
          'Je dépasse mes limites avec confiance.',
          'Je suis une personne créative et unique.',
          'Je crois en ma capacité à surmonter les obstacles.',
          'Je mérite de célébrer mes réussites.',
          'Je m\'autorise à prendre des risques.',
          'Je suis plus fort que mes peurs.',
          'Je suis entouré de personnes qui me soutiennent.',
          'Je choisis de vivre avec gratitude et confiance.',
          'Je suis courageux pour dire ce que je pense.',
          'Je m\'autorise à être authentique.',
          'Mon potentiel est extraordinaire.',
          'Je suis capable de créer un changement positif dans ma vie.',
        ]

      ),
      Category(
        name: "Abondance et gratitude",
        affirmation: [
          'Je suis entouré d\'abondance et de richesse dans tous les aspects de ma vie.',
          'Je suis reconnaissant pour chaque moment de bonheur que je vis.',
          'L\'abondance m\'entoure et me soutient chaque jour.',
          'Je suis capable de recevoir et de partager l\'abondance avec joie.',
          'Je suis reconnaissant pour les personnes aimantes dans ma vie.',
          'Je cultive la gratitude pour tout ce que je possède.',
          'L\'abondance est une partie naturelle de mon existence.',
          'Je suis reconnaissant pour ma santé et mon bien-être.',
          'Je choisis de voir l\'abondance partout où je vais.',
          'Je suis reconnaissant pour les opportunités qui s\'offrent à moi.',
          'Je suis ouvert à recevoir l\'abondance sous toutes ses formes.',
          'Je suis reconnaissant pour la beauté de la nature.',
          'Je suis entouré de personnes qui m\'aident à grandir.',
          'Je suis reconnaissant pour chaque leçon que je reçois.',
          'L\'abondance est une énergie qui circule librement dans ma vie.',
          'Je suis reconnaissant pour les moments de paix que je connais.',
          'Je suis capable de créer l\'abondance par mes pensées positives.',
          'Je suis reconnaissant pour les expériences enrichissantes que je vis.',
          'Je suis entouré d\'abondance spirituelle et matérielle.',
          'Je suis reconnaissant pour chaque sourire que je vois.',
          'Je suis ouvert à toutes les formes d\'abondance qui entrent dans ma vie.',
          'Je suis reconnaissant pour les rires que je partage avec les autres.',
          'Je suis entouré d\'abondance dans mes relations.',
          'Je suis reconnaissant pour chaque nouveau jour qui commence.',
          'Je suis capable de partager mon abondance avec générosité.',
          'Je suis reconnaissant pour les moments de connexion profonde avec les autres.',
          'L\'abondance est une partie intégrante de mon quotidien.',
          'Je suis reconnaissant pour les talents que je possède.',
          'Je suis entouré d\'abondance dans mes pensées et mes actions.',
          'Je suis reconnaissant pour chaque geste de gentillesse que je reçois.',
          'Je suis capable de créer une vie riche et épanouissante.',
          'Je suis reconnaissant pour les opportunités de croissance personnelle.',
          'Je suis entouré d\'abondance dans mon travail et mes projets.',
          'Je suis reconnaissant pour chaque instant de liberté que je connais.',
          'Je suis ouvert à recevoir l\'abondance avec humilité.',
          'Je suis reconnaissant pour les conseils sages que je reçois.',
          'Je suis entouré d\'abondance dans mes rêves et mes aspirations.',
          'Je suis reconnaissant pour chaque moment de créativité que je vis.',
          'Je suis reconnaissant pour les expériences qui m\'ont rendu plus fort.',
          'Je suis entouré d\'abondance et de pensées positives.',
          'Je suis reconnaissant pour chaque personne qui croit en moi.',
          'Je suis capable de partager mon abondance avec amour.',
          'Je suis reconnaissant pour les moments de silence et de méditation.',
          'Je suis entouré d\'abondance dans ma maison et mon environnement.',
          'Je suis reconnaissant pour chaque geste de solidarité que je vois.',
          'Je suis capable de créer une vie remplie d\'abondance et de joie.',
          'Je suis reconnaissant pour les leçons que j\'apprends chaque jour.',
          'Je suis entouré d\'abondance dans mes relations amoureuses.',
          'Je suis reconnaissant pour chaque moment de paix intérieure que je ressens.',
        ]

      ),
    ];
  }

  // Helper methods for easy access
  static List<String> getCategoryNames() {
    return getAllCategories().map((category) => category.name).toList();
  }

  static Category? getCategoryByName(String name) {
    try {
      return getAllCategories().firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  static List<String> getAffirmationByCategory(String categoryName) {
    final category = getCategoryByName(categoryName);
    return category?.affirmation ?? [];
  }

  static int getTotalAffirmationCount() {
    return getAllCategories()
        .map((category) => category.affirmation.length)
        .reduce((a, b) => a + b);
  }

  static String getRandomAffirmation() {
    final allCategories = getAllCategories();
    final randomCategory = (allCategories..shuffle()).first;
    final randomTip = (randomCategory.affirmation..shuffle()).first;
    return randomTip;
  }
}