import 'AffirmationData.dart';

class AffirmationDataES {
  static List<Category> getAllCategories() {
    return [
      Category(
        name: "Fuerza y resiliencia",
        affirmation: [
          "Soy un pilar de fuerza, inquebrantable frente a los vientos del cambio.",
          "El coraje me atraviesa con cada respiración.",
          "Con cada desafío, me vuelvo más fuerte y resiliente.",
          "Elijo actuar con valentía, incluso cuando el miedo me susurra al oído.",
          "Mi corazón es un reservorio de coraje, y hoy bebo de sus profundidades.",
          "Soy capaz de navegar a través de la tormenta.",
          "Soy más fuerte que mis desafíos.",
          "Soy capaz de superar todos los obstáculos.",
          "Tengo la fuerza interior necesaria para enfrentar cualquier cosa.",
          "Encuentro soluciones fácilmente a mis problemas.",
          "Soy capaz de crecer y aprender de mis dificultades.",
          "Soy digno de felicidad y éxito.",
          "Creo la vida que deseo.",
          "Realizo mis sueños, sin importar los obstáculos.",
          "Encuentro paz interior incluso en los momentos difíciles.",
          "Enfrento mis miedos y los supero.",
          "Encuentro belleza en las pequeñas cosas, incluso en los momentos difíciles.",
          "Encuentro alegría cada día.",
          "Me cuido en los períodos difíciles.",
          "Mantengo la calma y el centro en el caos.",
          "Me perdono y me doy una segunda oportunidad.",
          "Soy capaz de levantarme, sin importar cuántas veces caiga.",
          "Enfrento la incertidumbre con valentía.",
          "Me mantengo fiel a mí mismo, incluso en los momentos difíciles.",
          "Me mantengo enfocado en mis objetivos, sin importar las circunstancias.",
          "Mantengo el optimismo, incluso cuando las cosas parecen imposibles.",
          "Soy paciente y creo en mí.",
          "Soy determinado y valiente.",
          "Soy fuerte y resiliente.",
          "Soy capaz de mantenerme positivo y creer en un futuro mejor.",
          "Estoy agradecido, incluso en los períodos difíciles.",
          "Estoy abierto y acepto el cambio.",
          "Enfrento mis miedos con valentía, sin importar lo que ocurra a mi alrededor.",
          "Confío en mí, creo en mis capacidades.",
          "Soy capaz de dar amor, incluso en los momentos difíciles.",
          "Poseo la concentración y claridad necesarias para enfrentar cualquier situación.",
          "Cada desafío que enfrento agudiza mi mente y fortalece mi determinación.",
          "Mis pensamientos son poderosos, constructivos y alineados con mis objetivos.",
          "Confío en mi intuición y en mi inteligencia para guiarme hacia las decisiones correctas.",
          "Cada día que pasa, mi fuerza mental se fortalece.",
          "Confío en mi intuición y en mi sabiduría interior para guiarme en cada decisión.",
          "Creo en mis capacidades y reconozco la fuerza que reside en mí.",
          "Cada desafío que enfrento es una oportunidad para profundizar mi confianza en mí mismo.",
          "Honro mis sentimientos y confío en el camino que estoy recorriendo.",
          "Cada día que pasa fortalezco mi confianza en mí mismo.",
          "Soy resiliente y estoy listo para enfrentar todo lo que se presente.",
          "Soy dueño de mi destino y creo un futuro lleno de éxitos.",
          "A través de la perseverancia, alcanzaré alturas insospechadas.",
          "Mi actitud positiva abre el camino hacia el éxito y el crecimiento personal.",
          "Mi camino está iluminado por la confianza; camino con seguridad hacia el éxito.",

        ],
      ),
      Category(
        name: "Descanso y renovación",
        affirmation: [
          'Me permito descansar sin culpa.',
          'Soy capaz de regenerarme mediante el descanso.',
          'Elijo cuidar de mi cuerpo y de mi mente.',
          'Merezco pausas regulares para recargar energías.',
          'El descanso es esencial para mi salud y bienestar.',
          'Me libero de las presiones y encuentro paz interior.',
          'Soy capaz de crear un espacio de descanso en mi vida diaria.',
          'Me permito desacelerar y disfrutar cada instante.',
          'Estoy en paz con mi necesidad de descanso.',
          'Me siento revitalizado(a) después de cada periodo de descanso.',
          'Elijo priorizar mi bienestar emocional.',
          'Soy capaz de recargarme mediante la meditación y la relajación.',
          'Estoy rodeado(a) de calma y serenidad.',
          'Estoy agradecido(a) por cada momento de silencio.',
          'Soy capaz de renovar mi energía a través del descanso.',
          'Me siento ligero(a) y libre después de cada pausa.',
          'Estoy en armonía con mi ritmo natural.',
          'Elijo concentrarme en el presente.',
          'Soy capaz de crear una rutina que favorezca el descanso.',
          'Soy digno(a) de cuidarme.',
          'Soy capaz de liberarme de las tensiones físicas y mentales.',
          'Estoy rodeado(a) de amor y apoyo durante mi descanso.',
          'Estoy agradecido(a) por cada instante de relajación.',
          'Soy capaz de recargarme a través de la naturaleza.',
          'Elijo vivir en la simplicidad y la paz.',
          'Estoy en paz con mi pasado y mi futuro.',
          'Soy capaz de crear un ambiente propicio para el descanso.',
          'Estoy orgulloso(a) de cuidar de mí mismo(a).',
          'Soy capaz de renovar mi mente mediante la lectura y el aprendizaje.',
          'Estoy rodeado(a) de personas que me apoyan en mi descanso.',
          'Elijo concentrarme en el amor y la gratitud.',
          'Soy capaz de regenerarme mediante el sueño.',
          'Soy capaz de crear una vida equilibrada entre descanso y actividad.',
          'Soy digno(a) de darme tiempo para mí.',
          'Soy capaz de liberarme de las expectativas de los demás.',
          'Estoy rodeado(a) de calma y paz interior.',
          'Elijo vivir en la fluidez y la serenidad.',
          'Soy capaz de renovar mi cuerpo mediante ejercicio suave.',
          'Estoy agradecido(a) por cada instante de conexión conmigo mismo(a).',
          'Soy capaz de crear un espacio sagrado para el descanso.',
          'Estoy orgulloso(a) de mi capacidad para recargarme.',
          'Estoy rodeado(a) de amor incondicional durante mi descanso.',
          'Elijo concentrarme en mi bienestar integral.',
          'Soy capaz de regenerarme mediante la creatividad.',
          'Estoy agradecido(a) por cada momento de libertad.',
          'Soy capaz de crear una rutina que favorezca la renovación.',
          'Soy digno(a) de vivir una vida llena de paz y descanso.',
          'Soy capaz de renovar mi mente mediante la meditación profunda.',
          'Estoy en paz conmigo mismo(a) y celebro mi descanso.',
        ],
      ),
      Category(
          name: "Propósito y logros",
          affirmation: [
            'Soy consciente de mi razón de ser y la encarno cada día.',
            'Mi existencia tiene un sentido profundo y lo descubro en cada instante.',
            'Soy capaz de crear una vida que refleje mi verdadera misión.',
            'Estoy orgulloso de mis logros y los celebro.',
            'Estoy alineado con mis valores y los respeto.',
            'Soy una persona digna de respeto y admiración.',
            'Creo en mi potencial y lo realizo plenamente.',
            'Soy capaz de superar todos los desafíos para alcanzar mis objetivos.',
            'Estoy en paz con mi pasado y miro hacia el futuro con confianza.',
            'Soy una fuente de inspiración para mí mismo y para los demás.',
            'Elijo vivir una vida llena de sentido y propósito.',
            'Soy capaz de crear un impacto positivo en el mundo.',
            'Estoy orgulloso de mis progresos y continúo creciendo.',
            'Estoy en armonía con mi entorno y lo respeto.',
            'Soy capaz de tomar decisiones acertadas para mi bienestar.',
            'Estoy agradecido por cada oportunidad de crecer.',
            'Soy capaz de transformar mis sueños en realidad.',
            'Soy una persona creativa e innovadora.',
            'Soy capaz de superar mis miedos y perseguir mis objetivos.',
            'Estoy rodeado de personas que me apoyan e inspiran.',
            'Elijo vivir cada día con intención y con un propósito claro.',
            'Soy capaz de crear una vida plena y llena de sentido.',
            'Estoy orgulloso de mis talentos y los utilizo para ayudar a los demás.',
            'Estoy en paz conmigo mismo y me acepto plenamente.',
            'Soy capaz de tomar decisiones que me ayudan a alcanzar mis objetivos.',
            'Soy una persona resiliente y supero los obstáculos con valentía.',
            'Soy capaz de crear un ambiente que favorece mi realización.',
            'Estoy agradecido por cada lección que aprendo.',
            'Soy capaz de transformar mis desafíos en oportunidades de crecimiento.',
            'Estoy rodeado de amor y apoyo en mi búsqueda de sentido.',
            'Elijo vivir en la gratitud y el reconocimiento.',
            'Soy capaz de crear una vida que refleje mis valores profundos.',
            'Estoy orgulloso de mis logros pasados y continúo progresando.',
            'Estoy en armonía con mi intuición y la sigo.',
            'Soy capaz de tomar riesgos calculados para alcanzar mis objetivos.',
            'Estoy agradecido por cada momento de paz interior.',
            'Soy capaz de crear un impacto duradero en mi comunidad.',
            'Soy una persona auténtica y me expreso sin miedo.',
            'Soy capaz de superar mis límites y crecer.',
            'Estoy rodeado de personas que comparten mis valores.',
            'Elijo vivir cada día con pasión y entusiasmo.',
            'Soy capaz de crear una vida llena de alegría y felicidad.',
            'Estoy orgulloso de mis progresos y continúo superándome.',
            'Estoy en paz con mi futuro y confío en él.',
            'Soy capaz de transformar mis ideas en realidad concreta.',
            'Soy una persona creativa y encuentro soluciones innovadoras.',
            'Soy capaz de manejar mis emociones con serenidad.',
            'Estoy rodeado de personas que me inspiran y motivan.',
            'Elijo vivir cada día con intención y con un sentido profundo.',
            'Soy capaz de crear una vida plena y llena de realización.',
          ]

      ),
      Category(
          name: "Presencia y consciencia",
          affirmation: [
            'Estoy plenamente presente en cada instante.',
            'Cultivo la conciencia de mis pensamientos y emociones.',
            'Estoy en paz con el momento presente.',
            'Elijo vivir con plena conciencia.',
            'Soy capaz de concentrarme en mi respiración.',
            'Estoy conectado con mi cuerpo y mis sensaciones.',
            'Estoy en armonía con mi entorno.',
            'Estoy agradecido por cada momento de vida.',
            'Soy capaz de soltar el pasado y el futuro.',
            'Estoy plenamente comprometido con el momento presente.',
            'Cultivo la benevolencia hacia mí mismo.',
            'Soy capaz de manejar mis pensamientos con serenidad.',
            'Estoy en paz con mis emociones y las recibo sin juzgarlas.',
            'Elijo ver la belleza en cada momento.',
            'Soy capaz de crear un espacio de calma interior.',
            'Estoy conectado con mi intuición y la sigo.',
            'Estoy seguro en el presente.',
            'Soy capaz de transformar mis pensamientos negativos en positivos.',
            'Cultivo la gratitud por cada instante de vida.',
            'Estoy plenamente consciente de mis elecciones.',
            'Elijo vivir con intención y conciencia.',
            'Soy capaz de crear un ambiente pacífico a mi alrededor.',
            'Estoy en armonía con mi ritmo natural.',
            'Estoy agradecido por cada lección que aprendo.',
            'Soy capaz de liberarme de las distracciones.',
            'Estoy plenamente presente en mis relaciones.',
            'Cultivo la compasión hacia mí mismo y hacia los demás.',
            'Soy capaz de manejar mis emociones con calma.',
            'Estoy en paz con mi pasado y mi futuro.',
            'Soy capaz de crear una vida plena.',
            'Elijo ver lo positivo en cada situación.',
            'Estoy conectado con mi cuerpo y sus necesidades.',
            'Estoy seguro en mi entorno.',
            'Soy capaz de transformar mis desafíos en oportunidades.',
            'Cultivo la paciencia y la comprensión.',
            'Estoy plenamente consciente de mis pensamientos y acciones.',
            'Elijo vivir en la simplicidad y la paz.',
            'Soy capaz de crear un espacio de relajación interior.',
            'Estoy en armonía con la naturaleza.',
            'Estoy agradecido por cada momento de silencio.',
            'Soy capaz de concentrarme en el presente.',
            'Cultivo la benevolencia hacia los demás.',
            'Estoy en paz con mis límites.',
            'Soy capaz de transformar mis miedos en valor.',
            'Elijo ver la belleza en cada persona.',
            'Estoy conectado con mi corazón y sus deseos.',
            'Estoy seguro en mis relaciones.',
            'Soy capaz de crear una vida llena de sentido.',
            'Cultivo la gratitud por cada instante de conexión con los demás.',
            'Estoy plenamente presente en cada experiencia de vida.',
          ]

      ),
      Category(
          name: "Amor y relación",
          affirmation: [
            'Soy digno de un amor profundo y significativo.',
            'Merezco ser amado por quien soy.',
            'Dejo que mi intuición me guíe hacia el verdadero amor.',
            'Con cada latido del corazón, envío amor al universo y este me regresa amplificado.',
            'Estoy listo para dar y recibir amor incondicionalmente.',
            'Soy un imán de amor, atrayendo a las personas correctas hacia mí.',
            'Irradio confianza, encanto y amor.',
            'Soy amable y merezco el amor que busco.',
            'Soy un compañero amoroso y atento, atrayendo al mismo tipo de persona.',
            'Mi amor propio atrae el amor de los demás.',
            'Estoy completamente listo para amar y ser amado(a) incondicionalmente.',
            'Atraigo relaciones sanas y enriquecedoras.',
            'El amor que doy es un reflejo del amor que merezco.',
            'Estoy en paz con mi pasado y eso me abre a nuevas posibilidades.',
            'Soy el creador de mi propia realidad amorosa y la creo con pasión.',
            'Cada día, el amor en mí crece y se manifiesta en mi vida.',
            'Soy capaz de construir una relación duradera y feliz.',
            'Elijo amar profundamente y sin condiciones.',
            'Soy una persona positiva y amorosa.',
            'Planeo amar y apoyar a mi pareja siempre de manera incondicional.',
            'Elijo ser amable y atento con mi cónyuge.',
            'Puedo establecer límites para fortalecer el vínculo.',
            'Escucho a mi pareja y estoy dispuesto a hacer cambios personales por él/ella.',
            'Estoy listo para poner mi relación por encima de otras prioridades.',
            'Siempre tomo en cuenta las opiniones y emociones de mi pareja.',
            'Me concentro en proteger mis relaciones sanas.',
            'Siempre me comunico con mi pareja con respeto y comprensión.',
            'Estoy en una relación duradera.',
            'Tengo la capacidad de mantener mi relación sana y feliz.',
            'Me resulta fácil comprometerme con mi pareja.',
            'Mi amor es visible y el universo me recompensará por ello.',
            'La persona que amo también me ama de vuelta.',
            'Me siento seguro en una relación estable.',
            'El universo me prepara para una relación duradera.',
            'Dejo que el amor entre en mi vida.',
            'Me siento rodeado de amor en todas partes.',
            'Recibo amor en abundancia de todos los que encuentro.',
            'Estoy agradecido por el amor que me comparten.',
            'Celebro el amor que comparto con los demás y su poder transformador.',
            'Soy amoroso y amable a mi manera.',
            'Honro la fuerza y la vulnerabilidad que el amor trae.',
            'Mi amor es sin miedo, sin límites y está en constante evolución.',
            'Abrazo todo el espectro del amor, desde susurros silenciosos hasta grandes pasiones.',
            'Soy feliz y amado en mi relación actual.',
            'Soy un compañero confiable y leal.',
            'Elijo ver lo mejor en mi pareja.',
            'Soy capaz de perdonar y seguir adelante.',
            'Cultivo la paciencia y la comprensión en mi relación.',
            'Estoy orgulloso del amor que compartimos y lo celebro cada día.',
          ]

      ),
      Category(
          name: "Alegría y felicidad",
          affirmation: [
            'Estoy lleno de alegría y felicidad a diario.',
            'Elijo ver lo positivo en cada situación.',
            'Estoy agradecido por cada momento de felicidad que vivo.',
            'Cultivo la alegría en mis pensamientos y acciones.',
            'Estoy rodeado de amor y apoyo en mi vida.',
            'Merezco la felicidad y la cultivo con gratitud.',
            'Soy capaz de encontrar alegría en las pequeñas cosas.',
            'Estoy en paz conmigo mismo y me siento libre.',
            'Elijo vivir en la simplicidad y la belleza de la vida.',
            'Estoy orgulloso de quién soy y de lo que logro.',
            'Estoy abierto a nuevas experiencias y oportunidades.',
            'Estoy agradecido por las lecciones que aprendo cada día.',
            'Estoy rodeado de abundancia y posibilidades infinitas.',
            'Elijo sonreír incluso cuando los tiempos son difíciles.',
            'Soy capaz de crear mi propia realidad positiva.',
            'Estoy en armonía con el mundo que me rodea.',
            'Soy responsable de mi propia felicidad.',
            'Tomo decisiones que nutren y apoyan mi salud.',
            'Soy una fuente de inspiración para mí mismo y para los demás.',
            'Soy capaz de tomar decisiones informadas para mi bienestar.',
            'Estoy agradecido por cada instante de silencio y meditación.',
            'Elijo vivir en la gratitud y la alegría.',
            'Estoy rodeado de amor y positividad.',
            'Soy capaz de superar todos los desafíos que se presentan.',
            'Estoy en paz con mi pasado y confiado en el futuro.',
            'Elijo dejar ir lo que ya no me sirve.',
            'Estoy alineado con mi verdadera misión y pasión.',
            'Soy capaz de crear un impacto positivo en la vida de los demás.',
            'Estoy orgulloso de mis logros y los celebro.',
            'Estoy seguro y me siento protegido en cada situación.',
            'Elijo ver el mundo con optimismo y esperanza.',
            'Soy capaz de encontrar alegría en cada momento.',
            'Estoy rodeado de personas que me inspiran y apoyan.',
            'Estoy en armonía con el universo, y él me guía hacia el éxito.',
            'Soy capaz de hacer cambios positivos en mi vida.',
            'Elijo vivir en la fluidez y la paz.',
            'Estoy agradecido por la belleza presente en cada momento.',
            'Soy único y contribuyo a la riqueza del mundo.',
            'Soy capaz de crear una vida llena de alegría y felicidad.',
            'Estoy rodeado de amor incondicional y apoyo.',
            'Elijo concentrarme en el amor y la gratitud.',
            'Soy capaz de manejar mis emociones con calma y serenidad.',
            'Estoy en paz con mis emociones y las recibo sin juzgarlas.',
            'Estoy orgulloso de mis progresos y sigo creciendo.',
            'Soy capaz de encontrar alegría en los desafíos que supero.',
            'Estoy rodeado de posibilidades infinitas y las exploro con entusiasmo.',
            'Elijo vivir cada día con gratitud y entusiasmo.',
            'Soy capaz de crear un ambiente que favorece mi crecimiento personal.',
            'Estoy en armonía con mi corazón y guiado por mi intuición.',
            'Estoy en paz con quien soy y celebro mi vida con alegría.',
          ]

      ),
      Category(
          name: "Paz y calma interior",
          affirmation: [
            'Estoy en paz conmigo mismo y con el mundo que me rodea.',
            'Mi mente está calmada, tranquila y centrada.',
            'Elijo dejar ir las cosas que no puedo controlar.',
            'Estoy anclado en el presente y encuentro la paz interior.',
            'Confío en mi intuición para guiarme hacia la serenidad.',
            'Soy capaz de crear calma en mí en cada momento.',
            'Relajo mis músculos tranquilamente y me siento relajado.',
            'Elijo vivir en el amor y la compasión.',
            'Estoy agradecido por cada momento de paz que vivo.',
            'Dejo ir los arrepentimientos del pasado y me permito avanzar.',
            'Me libero de los pensamientos negativos y cultivo la paz interior.',
            'Estoy en armonía conmigo mismo y con la naturaleza.',
            'Me concentro en el presente y abandono el pasado.',
            'Estoy rodeado de calma y serenidad en mi entorno.',
            'Confío en el proceso de la vida para guiarme.',
            'Soy capaz de manejar mis emociones con calma y serenidad.',
            'Elijo ver lo positivo en cada situación.',
            'Estoy en paz con mis decisiones y me siento libre.',
            'Me permito tomar tiempo para mí sin culpa.',
            'Estoy abierto a nuevas oportunidades y las recibo con calma.',
            'Estoy agradecido por las lecciones que aprendo cada día.',
            'Soy capaz de crear un espacio interior de paz y serenidad.',
            'Me libero de los juicios de los demás y me concentro en el amor.',
            'Estoy en paz con mi pasado y mi futuro.',
            'Elijo vivir en la simplicidad y la belleza de la vida.',
            'Estoy calmado y centrado en cada situación.',
            'Confío en mi viaje personal y soy guiado.',
            'Soy capaz de superar los desafíos con calma y confianza.',
            'Estoy rodeado de amor y apoyo en mi vida.',
            'Elijo soltar la necesidad de controlar todo.',
            'Estoy en paz con los cambios inevitables de la vida.',
            'Me permito expresar mis emociones sin retenerlas.',
            'Estoy agradecido por los momentos de alegría que comparto con otros.',
            'Soy capaz de crear una vida plena y pacífica.',
            'Estoy seguro y me siento protegido en cada situación.',
            'Elijo concentrarme en el amor y la gratitud.',
            'Estoy en armonía con el mundo que me rodea.',
            'Soy capaz de encontrar la paz interior en cada instante.',
            'Me libero de tensiones y preocupaciones.',
            'Estoy abierto a nuevas experiencias con calma y curiosidad.',
            'Estoy agradecido por cada instante de silencio y meditación.',
            'Elijo vivir en la fluidez y la paz.',
            'Soy capaz de manejar mis pensamientos con calma y claridad.',
            'Estoy rodeado de personas que me apoyan y me aman.',
            'Estoy en paz con mis emociones y las recibo sin juzgarlas.',
            'Confío en el universo para guiarme hacia la paz interior.',
            'Soy capaz de crear un ambiente pacífico a mi alrededor.',
            'Elijo soltar las expectativas de los demás.',
            'Estoy en paz conmigo mismo y me siento libre para vivir mi vida como quiero.',
          ]

      ),
      Category(
          name: "Salud y vitalidad",
          affirmation: [
            'Respiro plena y libremente.',
            'Estoy rebosante de salud y vitalidad.',
            'Estoy lleno(a) de energía sanadora.',
            'Llevo una vida sana y equilibrada.',
            'Me siento en plena forma física y mental.',
            'A partir de ahora, elijo estar saludable.',
            'Disfruto cuidándome a mí mismo(a) y a los demás.',
            'Merezco y me permito descansar cuando lo necesito.',
            'Consumo alimentos que respetan mi cuerpo.',
            'Respeto y valoro mi cuerpo.',
            'Todo en mí se equilibra a la perfección.',
            'Mi peso y mis constantes se normalizan con fluidez.',
            'Me permito expresar mis emociones y satisfacer mis necesidades.',
            'Soy plenamente y alegremente yo mismo(a).',
            'Me relajo e instalo la calma en mí.',
            'Soy flexible y me suavizo cada día.',
            'Todos los días, en todos los aspectos, voy mejorando.',
            'Me siento seguro(a) en todas partes y en todo momento.',
            'Me perdono y perdono a los demás, y ofrezco paz para nosotros.',
            'Ahora veo lo maravilloso en todo.',
            'Cambio mi mirada sobre mi pasado, me libero.',
            'La energía de la vida se expresa alegremente a través de mí.',
            'Puedo cultivar la mejor vitalidad.',
            'Envió apoyo y amor a mi cuerpo.',
            'Mi cuerpo puede regenerarse fácil y naturalmente.',
            'Agradezco a mi cuerpo por todo lo que funciona bien.',
            'Cuanto más cosas positivas le doy a mi cuerpo, más me recompensa.',
            'Merezco estar saludable y disfrutar de la vida.',
            'Me encanta vivir la vitalidad y el bienestar global.',
            'Me libero de todo lo que se interpone entre mí y una salud perfecta.',
            'Una buena higiene de vida me ayuda a cultivar mejor forma.',
            'Cada parte de mi cuerpo tiene el poder de mejorar.',
            'Cada célula de mi cuerpo puede regenerarse positivamente.',
            'Mi cuerpo es mi mejor amigo.',
            'Merezco estar saludable.',
            'Escucho las señales de mi cuerpo.',
            'Tomo tiempo para cuidar de mi cuerpo.',
            'Depende de mí decidir qué es un cuerpo sano.',
            'Mi salud mental y física son prioritarias.',
            'Prioridad al descanso y a la calma.',
            'Me desafío físicamente.',
            'Celebro los pequeños éxitos.',
            'Tengo suficiente coraje para enfrentar mis miedos.',
            'Los obstáculos son mis oportunidades para progresar.',
            'Voy a lograr alcanzar mis objetivos de salud.',
            'Estoy exactamente donde debo estar para mi salud.',
            'Cada una de mis acciones me acerca a una vida más sana.',
            'Tengo éxito en todo lo que emprendo para mi salud.',
            'Hoy doy lo mejor de mí para mi salud.',
          ]

      ),
      Category(
          name: "Confianza y autoestima",
          affirmation: [
            'Confío en mí mismo y en mis capacidades.',
            'Soy capaz de superar todos los desafíos.',
            'Me amo y me acepto tal como soy.',
            'Soy competente y talentoso.',
            'Confío en mi intuición.',
            'Estoy seguro de las decisiones que tomo.',
            'Me valoro en mi justa medida.',
            'Estoy orgulloso de mis progresos y logros.',
            'Tengo control sobre mis pensamientos y emociones.',
            'Soy digno de amor y respeto.',
            'Elijo concentrarme en mis fortalezas.',
            'Soy único y eso me hace especial.',
            'Me acepto plenamente con mis imperfecciones.',
            'Soy capaz de crear una vida que refleje quién soy.',
            'Merezco el éxito y la felicidad.',
            'Estoy en paz con quien soy.',
            'Soy valiente ante lo desconocido.',
            'Estoy exactamente donde debo estar.',
            'Soy una persona digna de confianza.',
            'Soy el dueño de mi vida.',
            'Merezco cuidar de mí mismo.',
            'Estoy orgulloso de mi perseverancia.',
            'Elijo amarme cada día más.',
            'Soy capaz de aprender todo lo que deseo.',
            'Estoy por encima de los pensamientos y acciones negativas.',
            'Veo los obstáculos como oportunidades para crecer.',
            'Confío en mis elecciones.',
            'Soy talentoso e inteligente.',
            'Me expreso abierta y honestamente con confianza.',
            'Estoy cómodo con quien soy.',
            'Hago lo mejor que puedo en toda circunstancia.',
            'Estoy orgulloso del camino recorrido.',
            'Estoy en armonía con mis valores.',
            'Respeto mi naturaleza profunda.',
            'Soy capaz de lograr todo lo que deseo.',
            'Soy digno de respeto y aprecio.',
            'Elijo cultivar pensamientos positivos.',
            'Estoy en paz con mi pasado.',
            'Supero mis límites con confianza.',
            'Soy una persona creativa y única.',
            'Creo en mi capacidad para superar los obstáculos.',
            'Merezco celebrar mis éxitos.',
            'Me permito tomar riesgos.',
            'Soy más fuerte que mis miedos.',
            'Estoy rodeado de personas que me apoyan.',
            'Elijo vivir con gratitud y confianza.',
            'Soy valiente para decir lo que pienso.',
            'Me permito ser auténtico.',
            'Mi potencial es extraordinario.',
            'Soy capaz de crear un cambio positivo en mi vida.',
          ]

      ),
      Category(
          name: "Abundancia y gratitud",
          affirmation: [
            'Estoy rodeado de abundancia y riqueza en todos los aspectos de mi vida.',
            'Estoy agradecido por cada momento de felicidad que vivo.',
            'La abundancia me rodea y me sostiene cada día.',
            'Soy capaz de recibir y compartir la abundancia con alegría.',
            'Estoy agradecido por las personas amorosas en mi vida.',
            'Cultivo la gratitud por todo lo que poseo.',
            'La abundancia es una parte natural de mi existencia.',
            'Estoy agradecido por mi salud y bienestar.',
            'Elijo ver la abundancia en todos los lugares a donde voy.',
            'Estoy agradecido por las oportunidades que se me presentan.',
            'Estoy abierto a recibir la abundancia en todas sus formas.',
            'Estoy agradecido por la belleza de la naturaleza.',
            'Estoy rodeado de personas que me ayudan a crecer.',
            'Estoy agradecido por cada lección que recibo.',
            'La abundancia es una energía que fluye libremente en mi vida.',
            'Estoy agradecido por los momentos de paz que experimento.',
            'Soy capaz de crear abundancia a través de mis pensamientos positivos.',
            'Estoy agradecido por las experiencias enriquecedoras que vivo.',
            'Estoy rodeado de abundancia espiritual y material.',
            'Estoy agradecido por cada sonrisa que veo.',
            'Estoy abierto a todas las formas de abundancia que entran en mi vida.',
            'Estoy agradecido por las risas que comparto con los demás.',
            'Estoy rodeado de abundancia en mis relaciones.',
            'Estoy agradecido por cada nuevo día que comienza.',
            'Soy capaz de compartir mi abundancia con generosidad.',
            'Estoy agradecido por los momentos de conexión profunda con los demás.',
            'La abundancia es una parte integral de mi vida diaria.',
            'Estoy agradecido por los talentos que poseo.',
            'Estoy rodeado de abundancia en mis pensamientos y acciones.',
            'Estoy agradecido por cada acto de bondad que recibo.',
            'Soy capaz de crear una vida rica y plena.',
            'Estoy agradecido por las oportunidades de crecimiento personal.',
            'Estoy rodeado de abundancia en mi trabajo y proyectos.',
            'Estoy agradecido por cada instante de libertad que experimento.',
            'Estoy abierto a recibir la abundancia con humildad.',
            'Estoy agradecido por los consejos sabios que recibo.',
            'Estoy rodeado de abundancia en mis sueños y aspiraciones.',
            'Estoy agradecido por cada momento de creatividad que vivo.',
            'Estoy agradecido por las experiencias que me han hecho más fuerte.',
            'Estoy rodeado de abundancia y pensamientos positivos.',
            'Estoy agradecido por cada persona que cree en mí.',
            'Soy capaz de compartir mi abundancia con amor.',
            'Estoy agradecido por los momentos de silencio y meditación.',
            'Estoy rodeado de abundancia en mi hogar y entorno.',
            'Estoy agradecido por cada acto de solidaridad que veo.',
            'Soy capaz de crear una vida llena de abundancia y alegría.',
            'Estoy agradecido por las lecciones que aprendo cada día.',
            'Estoy rodeado de abundancia en mis relaciones amorosas.',
            'Estoy agradecido por cada momento de paz interior que siento.',
          ]

      ),
    ];


  }




  // Helper methods for easy access
  static List<String> getCategoryNames() {
    return getAllCategories().map((category) => category.name).toList();
  }

  static Category? getCategoryByName(String name) {
    try {
      return getAllCategories().firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  static List<String> getAffirmationByCategory(String categoryName) {
    final category = getCategoryByName(categoryName);
    return category?.affirmation ?? [];
  }

  static int getTotalAffirmationCount() {
    return getAllCategories()
        .map((category) => category.affirmation.length)
        .reduce((a, b) => a + b);
  }

  static String getRandomAffirmation() {
    final allCategories = getAllCategories();
    final randomCategory = (allCategories..shuffle()).first;
    final randomTip = (randomCategory.affirmation..shuffle()).first;
    return randomTip;
  }
}