

import 'AffirmationData.dart';

class AffirmationDataDE {
  static List<Category> getAllCategories() {
    return [
      Category(
        name: "Stärke und Widerstandsfähigkeit",
        affirmation: [
          'Ich bin stärker als jede Herausforderung, der ich mich stelle.',
          'Meine Widerstandsfähigkeit hilft mir, schwierige Zeiten zu überwinden.',
          'Ich überwinde Hindernisse mit Leichtigkeit.',
          'Meine innere Stärke ist unerschütterlich.',
          'Ich bin dazu geschaffen, zu bestehen und zu gedeihen.',
          'Ich werde mit jedem Schritt stärker.',
          'Mein Mut leuchtet in jedem Moment durch.',
          'Ich erhole mich von allen Herausforderungen, die das Leben mit sich bringt.',
          'Ich bin eine Kämpferin der Widerstandsfähigkeit und der Hoffnung.',
          'Meine Stärke kommt aus meinem Inneren.',
          'Ich begegne Herausforderungen mit furchtloser Anmut.',
          'Ich bin stark, fähig und stabil.',
          'Mein Geist ist beständig und mutig.',
          'Rückschläge überwinde ich mit Zuversicht.',
          'Ich bin in unerschütterlicher Stärke verwurzelt.',
          'Meine Kraft wächst mit jeder Herausforderung.',
          'Ich stehe aufrecht, trotz des Sturms.',
          'Ich bin beständig in Geist und Herz.',
          'Meine Stärke ist mein Schild und mein Licht.',
          'Ich passe mich an und meistere jede Herausforderung.',
          'Ich bin eine Säule von unübertroffenem Mut.',
          'Meine Unverwüstlichkeit hebt mich jeden Tag höher.',
          'Ich stelle mich dem Leben mit unnachgiebiger Stärke.',
          'Ich bin stärker, als ich es mir je hätte vorstellen können.',
          'Mein Geist beugt sich, aber er bricht nie.',
          'Nach jedem Sturz stehe ich stärker auf.',
          'Ich werde von meiner Widerstandsfähigkeit und Entschlossenheit angetrieben.',
          'Meine Stärke befähigt mich, weiterzumachen.',
          'Ich werde im Angesicht der Höhen und Tiefen des Lebens nicht wanken.',
          'Meine Unverwüstlichkeit ist meine Superkraft.',
          'Ich stehe fest in meiner Stärke.',
          'Ich überwinde mit Anmut und Kraft.',
          'Ich bin eine Kraft des unnachgiebigen Willens.',
          'Meine Stärke leuchtet durch Widrigkeiten hindurch.',
          'Ich bin so gebaut, dass ich jeden Sturm überstehen kann.',
          'Ich wachse durch jede Herausforderung, der ich mich stelle.',
          'Meine Unverwüstlichkeit ist mein sicherer Anker.',
          'Ich bin mutig, stark und unaufhaltsam.',
          'Mein inneres Feuer treibt meine Ausdauer an.',
          'Ich begegne der Welt mit furchtloser Stärke.',
          'Ich werde durch meine Widerstandsfähigkeit erneuert.',
          'Meine Stärke liegt in meiner Fähigkeit, aufzustehen.',
          'Ich bin ein Fels der Stärke und Gelassenheit.',
          'Ich besiege Zweifel mit meinem widerstandsfähigen Herzen.',
          'Meine Widerstandsfähigkeit ist der Grundstein für meine strahlende Zukunft.',
          'Ich bin stark genug für alles.',
          'Mein Mut definiert, wer ich bin.',
          'Ich blühe in den schwierigsten Momenten des Lebens auf.',
          'Meine Stärke ist grenzenlos und authentisch.',
          'Ich bin eine Säule der Stärke, unerschütterlich im Angesicht der Veränderung.',
          'Mit jedem Atemzug fließt Mut in mir.',
          'Mit jeder Herausforderung werde ich stärker und widerstandsfähiger.',
          'Ich entscheide mich, mutig zu handeln, auch wenn mir die Angst ins Ohr flüstert.',
          'Mein Herz ist ein Reservoir des Mutes, und heute schöpfe ich aus seinen Tiefen.',
          'Ich bin in der Lage, durch den Sturm zu gehen.',
          'Ich bin stärker als meine Herausforderungen.',
          'Ich bin in der Lage, alle Hindernisse zu überwinden.',
          'Ich habe die innere Stärke, um alles zu bewältigen.',
          'Ich kann leicht Lösungen für meine Probleme finden.',
          'Ich bin in der Lage zu wachsen und aus meinen Schwierigkeiten zu lernen.',
          'Ich bin des Glücks und des Erfolgs würdig.',
          'Ich schaffe mir das Leben, das ich mir wünsche.',
          'Ich erreiche meine Träume trotz Hindernissen.',
          'Ich finde auch in schwierigen Zeiten inneren Frieden.',
          'Ich stelle mich meinen Ängsten und überwinde sie.',
          'Ich finde Schönheit in den kleinen Dingen, auch in schwierigen Zeiten.',
          'Ich finde Freude an jedem Tag.',
          'Ich kümmere mich in schwierigen Zeiten um mich selbst.',
          'Ich bleibe inmitten des Chaos ruhig und konzentriert.',
          'Ich vergebe mir selbst und gebe mir eine zweite Chance.',
          'Ich bin in der Lage, wieder aufzustehen, egal wie oft ich falle.',
          'Ich begegne Unsicherheiten mit Mut.',
          'Ich bleibe mir selbst treu, auch in schwierigen Zeiten.',
          'Ich bleibe auf meine Ziele fokussiert, egal unter welchen Umständen.',
          'Ich bleibe optimistisch, auch wenn die Dinge unmöglich erscheinen.',
          'Ich bin geduldig und glaube an mich selbst.',
          'Ich bin entschlossen und mutig.',
          'Ich bin stark und widerstandsfähig.',
          'Ich bin in der Lage, positiv zu bleiben und an eine bessere Zukunft zu glauben.',
          'Ich bin dankbar, auch in schwierigen Zeiten.',
          'Ich bin offen und akzeptiere Veränderungen.',
          'Ich stelle mich mutig meinen Ängsten, unabhängig davon, was um mich herum vorgeht.',
          'Ich bin zuversichtlich, ich glaube an meine Fähigkeiten.',
          'Ich bin fähig, Liebe zu geben, auch in schwierigen Zeiten.',
          'Ich habe die nötige Konzentration und Klarheit für jede Situation.',
          'Jede Herausforderung, der ich mich stelle, schärft meinen Verstand und stärkt meine Entschlossenheit.',
          'Meine Gedanken sind kraftvoll, konstruktiv und auf meine Ziele ausgerichtet.',
          'Ich vertraue meiner Intuition und meiner Vernunft, die mich zu den richtigen Entscheidungen führen.',
          'Jeder Tag, der vergeht, stärkt meine geistige Kraft.',
          'Ich vertraue darauf, dass meine Intuition und meine innere Weisheit mich bei jeder Entscheidung leiten.',
          'Ich glaube an meine Fähigkeiten und erkenne die Stärke in mir.',
          'Jede Herausforderung, der ich mich stelle, ist eine Gelegenheit, mein Vertrauen zu vertiefen.',
          'Ich respektiere meine Gefühle und vertraue dem Weg, auf dem ich mich befinde.',
          'Jeder Tag, der vergeht, stärkt mein Selbstvertrauen.',
          'Ich bin widerstandsfähig und bereit, mich allem zu stellen, was auf mich zukommt.',
          'Ich bin Herr meines Schicksals und gestalte eine Zukunft voller Erfolg.',
          'Durch Beharrlichkeit werde ich ungeahnte Höhen erreichen.',
          'Meine positive Einstellung öffnet mir den Weg zu Erfolg und Erfüllung.',
          'Mein Weg ist mit Zuversicht erleuchtet, ich gehe mit Standhaftigkeit auf den Erfolg zu.'
        ]

      ),
      Category(
        name: "Rast und Erneuerung",
        affirmation: [
          'Ich erlaube mir, tief und vollständig zu ruhen.',
          'Mein Körper wird mit jedem Atemzug erneuert.',
          'Ich bin ruhig, wenn ich raste.',
          'Der Schlaf kommt leicht und natürlich zu mir.',
          'Ich lasse den Tag los und genieße die friedliche Rast.',
          'Mein Geist entspannt sich mit Leichtigkeit.',
          'Ich werde durch die Kraft der Ruhe neu belebt.',
          'Jeder Moment der Ruhe heilt mich.',
          'Ich gebe mich dem friedlichen, erneuernden Schlaf hin.',
          'Meine Energie wird wieder aufgefüllt, wenn ich raste.',
          'Ich verdiene Zeit zur Erholung und Entspannung.',
          'Mein Körper weiß, wie er sich erholen kann.',
          'Mit ruhigem Herzen sinke ich in die Rast.',
          'Der Schlaf umhüllt mich mit einer warmen Umarmung.',
          'Ich lasse los und vertraue auf die Erneuerung.',
          'Meine Rast ist tief und erholsam.',
          'Ich wache erfrischt und voller Leben auf.',
          'Ich achte mein Bedürfnis nach Rast.',
          'Mein Geist wird mit jeder Pause erneuert.',
          'Ich lasse Spannungen los und nehme den Frieden an.',
          'Meine Ruhe ist ein Geschenk an mich selbst.',
          'Ich lasse den Stress los und tauche in die Ruhe ein.',
          'Ich bin heute entspannt und ruhig.',
          'Ich wache auf und fühle mich ganz und ausgeruht.',
          'Mein Geist findet in den ruhigen Momenten Frieden.',
          'Der Schlaf gibt mir jede Nacht neue Kraft.',
          'Ich bin im Frieden mit der Entschleunigung.',
          'Mein Urlaub bringt mir Klarheit und Gelassenheit.',
          'Ich erlaube mir, mich völlig zu entspannen.',
          'Mit jedem ruhigen Atemzug kommt meine Energie zurück.',
          'Rast ist mein Weg zur inneren Erneuerung.',
          'Ich lasse den Tag los und raste leicht aus.',
          'Mein Körper heilt, wenn ich mich tief entspanne.',
          'In der Stille der Nacht bin ich erholt.',
          'Das Rasten füllt mich mit sanfter Kraft.',
          'Ich sinke in einen friedlichen, heilenden Schlaf.',
          'Meine Erneuerung beginnt mit jeder Ruhe.',
          'Ich erlaube mir, ohne Schuldgefühle zu ruhen.',
          'Ich bin in der Lage, mich durch Rast zu erholen.',
          'Ich entscheide mich, für meinen Körper und meinen Geist zu sorgen.',
          'Ich bin es wert, regelmäßig Pausen zur Erholung einzulegen.',
          'Rast ist wichtig für meine Gesundheit und mein Wohlbefinden.',
          'Ich lasse Druck ab und finde inneren Frieden.',
          'Ich bin in der Lage, in meinem täglichen Leben Raum für Entspannung zu schaffen.',
          'Ich erlaube mir, langsamer zu werden und jeden Moment zu schätzen.',
          'Ich bin in Frieden mit meinem Bedürfnis nach Rast.',
          'Ich fühle mich nach jeder Ruhephase erneuert.',
          'Ich entscheide mich, meinem emotionalen Wohlbefinden Vorrang einzuräumen.',
          'Ich bin in der Lage, mich durch Meditation und Entspannung zu erholen.',
          'Ich bin von Ruhe und Gelassenheit umgeben.',
          'Ich bin dankbar für jeden Moment der Stille.',
          'Ich kann meine Energie durch Rast wiederherstellen.',
          'Ich fühle mich nach jeder Pause leicht und frei.',
          'Ich bin im Einklang mit meinem natürlichen Rhythmus.',
          'Ich konzentriere mich auf die Gegenwart.',
          'Ich bin in der Lage, eine Routine zu schaffen, die der Erholung förderlich ist.',
          'Ich bin der Selbstfürsorge würdig.',
          'Ich bin in der Lage, körperliche und geistige Spannungen abzubauen.',
          'Ich bin in meiner Entspannung von Liebe und Unterstützung umgeben.',
          'Ich bin dankbar für jeden Moment der Entspannung.',
          'Ich bin in der Lage, mich durch die Natur zu erholen.',
          'Я выбираю жить в простоте и мире.',
          'Ich bin im Frieden mit meiner Vergangenheit und Zukunft.',
          'Ich bin in der Lage, eine Umgebung zu schaffen, die der Entspannung förderlich ist.',
          'Ich bin stolz darauf, für mich selbst zu sorgen.',
          'Ich bin in der Lage, meinen Geist durch Lesen und Lernen zu erneuern.',
          'Ich bin von Menschen umgeben, die mich bei meiner Entspannung unterstützen.',
          'Ich konzentriere mich auf Liebe und Dankbarkeit.',
          'Ich bin in der Lage, mich durch Schlaf zu erholen.',
          'Ich bin dankbar für jeden Moment der Einsamkeit.',
          'Ich bin in der Lage, ein ausgewogenes Leben zwischen Ruhe und Aktivität zu gestalten.',
          'Ich bin es wert, mir Zeit zu schenken.',
          'Ich bin in der Lage, mich von den Erwartungen anderer zu befreien.',
          'Ich bin von Ruhe und innerem Frieden umgeben.',
          'Ich entscheide mich für ein Leben im Fluss und in Gelassenheit.',
          'Ich bin in der Lage, meinen Körper durch sanfte Übungen zu erneuern.',
          'Ich bin dankbar für jeden Moment der Verbindung mit mir selbst.',
          'Ich bin in der Lage, einen heiligen Raum für Rast zu schaffen.',
          'Ich bin stolz auf meine Fähigkeit, mich selbst wiederherzustellen.',
          'In meiner Rast bin ich von bedingungsloser Liebe umgeben.',
          'Ich entscheide mich, mich auf mein allgemeines Wohlbefinden zu konzentrieren.',
          'Ich bin in der Lage, mich durch Kreativität zu erholen.',
          'Ich bin dankbar für jeden Moment der Freiheit.',
          'Ich bin in der Lage, Routinen zu schaffen, die die Erneuerung fördern.',
          'Ich bin eines Lebens in Frieden und Rast würdig.',
          'Ich bin in der Lage, meinen Geist durch tiefe Meditation zu erneuern.',
          'Ich bin im Frieden mit dem, was ich bin, und feiere meine Rast.'
        ]

      ),
      Category(
        name: "Zielstrebigkeit und Errungenschaften",
        affirmation: [
          'Mich treibt ein klares Zielbewusstsein an.',
          'Jeder Schritt, den ich mache, bringt mich meinen Zielen näher.',
          'Ich erreiche mit jeder Anstrengung Großartiges.',
          'Mein Ziel leitet mich mit Kraft und Klarheit.',
          'Ich bin fähig, meine Träume zu verwirklichen.',
          'Erfolg ist für mich natürlich und leicht zu erreichen.',
          'Ich konzentriere mich auf das, was für mich am wichtigsten ist.',
          'Meine Errungenschaften spiegeln meine harte Arbeit wider.',
          'Ich lebe jeden Tag mit Absicht und Ziel.',
          'Bei der Verfolgung meiner Ziele bin ich unaufhaltsam.',
          'Mein Ziel treibt meine Leidenschaft und meinen Antrieb an.',
          'Ich feiere jeden erreichten Meilenstein.',
          'Ich bin im Einklang mit der wahren Berufung meines Lebens.',
          'Meine Bemühungen führen zu sinnvollem Erfolg.',
          'Ich habe Vertrauen in meine Fähigkeit, etwas zu erreichen.',
          'Ich gestalte meine Zukunft mit jeder Handlung.',
          'In allem, was ich tue, schimmert meine Bestimmung durch.',
          'Ich bin stolz darauf, wie weit ich gekommen bin.',
          'Ich gehe mit Entschlossenheit und Freude voran.',
          'Meine Ziele sind für mich erreichbar.',
          'Ich bin von meinem eigenen Potenzial inspiriert.',
          'Erfolg ist meine Belohnung für meine Beharrlichkeit.',
          'Ich lebe ein Leben voller Sinn und Wirkung.',
          'Ich bin motiviert, mein Bestes zu geben.',
          'Meine Träume werden durch mein Handeln Wirklichkeit.',
          'Ich bin eine Kraft für positive Veränderungen.',
          'Ich vertraue meinem Weg zum Erfolg.',
          'Mein Ziel gibt mir unendlich viel Energie.',
          'Ich bewältige Herausforderungen mit Zuversicht.',
          'Ich bin für große Errungenschaften bestimmt.',
          'Mein Fokus verwandelt Träume in Siege.',
          'Ich baue mir ein Leben auf, auf das ich stolz bin.',
          'Meine Bestimmung leuchtet mir den Weg nach vorn.',
          'Ich erreiche, was ich mir vornehme.',
          'Ich bin nachhaltig in meinen Zielen.',
          'Mein Erfolg inspiriert mich und andere.',
          'Ich befinde mich auf einer Reise des sinnvollen Wachstums.',
          'Ich gehe mutige Schritte in Richtung meiner Ziele.',
          'Meine Errungenschaften sind ein Spiegelbild meiner selbst.',
          'Ich engagiere mich für meine Größe.',
          'Mein Ziel inspiriert mich jeden Tag.',
          'Ich verwandle Hindernisse in Chancen.',
          'Ich bin all dessen würdig, was ich zu erreichen versuche.',
          'Meine Entschlossenheit kennt keine Grenzen.',
          'Ich schaffe ein Vermächtnis, das voller Bedeutung ist.',
          'Erfolg ist mein natürliches Ergebnis.',
          'Ich werde von Leidenschaft und Tatkraft angetrieben.',
          'Meine Ziele stehen im Einklang mit meinem höheren "Ich".',
          'Ich blühe auf in der Verfolgung meiner Ziele.',
          'Ich bin der Architekt meiner Errungenschaften.',
          'Ich erkenne meine Bestimmung und verkörpere sie jeden Tag.',
          'Meine Existenz hat einen tiefen Sinn und ich entdecke ihn in jedem Augenblick.',
          'Ich bin in der Lage, ein Leben zu gestalten, das meine wahre Mission widerspiegelt.',
          'Ich bin stolz auf meine Errungenschaften und feiere sie.',
          'Ich bin im Einklang mit meinen Werten und halte sie in Ehren.',
          'Ich bin ein Mensch, der Respekt und Bewunderung verdient.',
          'Ich glaube an mein Potenzial und schöpfe es voll aus.',
          'Ich bin in der Lage, alle Herausforderungen zu überwinden, um meine Ziele zu erreichen.',
          'Ich bin mit meiner Vergangenheit im Reinen und blicke mit Zuversicht in die Zukunft.',
          'Ich bin eine Quelle der Inspiration für mich und andere.',
          'Ich möchte ein Leben voller Sinn und Zweck leben.',
          'Ich bin in der Lage, einen positiven Einfluss auf die Welt zu nehmen.',
          'Ich bin stolz auf meine Fortschritte und wachse weiter.',
          'Ich bin in Harmonie mit meiner Umwelt und respektiere sie.',
          'Ich bin in der Lage, fundierte Entscheidungen für mein Wohlergehen zu treffen.',
          'Ich bin dankbar für jede Gelegenheit, zu wachsen.',
          'Ich bin fähig, meine Träume in die Realität umzusetzen.',
          'Ich bin ein kreativer und innovativer Mensch.',
          'Ich bin in der Lage, meine Ängste zu überwinden und meine Ziele zu verfolgen.',
          'Ich bin von Menschen umgeben, die mich unterstützen und inspirieren.',
          'Ich entscheide mich dafür, jeden Tag mit Absicht und einem klaren Ziel zu leben.',
          'Ich bin in der Lage, ein erfülltes, sinnerfülltes Leben zu führen.',
          'Ich bin stolz auf meine Talente und nutze sie, um anderen zu helfen.',
          'Ich bin in Frieden mit mir selbst und akzeptiere mich voll und ganz.',
          'Ich bin in der Lage, Entscheidungen zu treffen, die mir helfen, meine Ziele zu erreichen.',
          'Ich bin ein belastbarer Mensch und überwinde Hindernisse mit Mut.',
          'Ich bin in der Lage, ein Umfeld zu schaffen, das meinen Leistungen förderlich ist.',
          'Ich bin dankbar für jede Lektion, die ich lerne.',
          'Ich bin in der Lage, Herausforderungen in Gelegenheiten zum Wachstum zu verwandeln.',
          'Ich bin von Liebe und Unterstützung bei meiner Suche nach Sinn umgeben.',
          'Ich entscheide mich für ein Leben in Dankbarkeit und Wertschätzung.',
          'Ich bin in der Lage, ein Leben zu gestalten, das meine tiefsten Werte widerspiegelt.',
          'Ich bin stolz auf meine bisherigen Leistungen und mache weiter Fortschritte.',
          'Ich bin im Einklang mit meiner Intuition und folge ihr.',
          'Ich bin in der Lage, kalkulierte Risiken einzugehen, um meine Ziele zu erreichen.',
          'Ich bin dankbar für jeden Moment des inneren Friedens.',
          'Ich bin in der Lage, einen nachhaltigen Einfluss auf meine Gemeinschaft auszuüben.',
          'Ich bin ein aufrichtiger Mensch und drücke mich ohne Angst aus.',
          'Ich bin in der Lage, an meine Grenzen zu gehen und zu wachsen.',
          'Ich bin von Menschen umgeben, die meine Werte teilen.',
          'Ich entscheide mich dafür, jeden Tag mit Leidenschaft und Begeisterung zu leben.',
          'Ich bin in der Lage, ein Leben voller Freude und Glück zu gestalten.',
          'Ich bin stolz auf meine Fortschritte und treibe mich selbst weiter an.',
          'Ich bin mit meiner Zukunft im Reinen und habe Vertrauen in sie.',
          'Ich bin in der Lage, meine Ideen in die Realität umzusetzen.',
          'Ich bin kreativ und finde innovative Lösungen.',
          'Ich bin in der Lage, meine Emotionen mit Gelassenheit zu steuern.',
          'Ich bin von Menschen umgeben, die mich inspirieren und motivieren.',
          'Ich entscheide mich dafür, jeden Tag mit Absicht und einem tiefen Sinn für Ziele zu leben.',
          'Ich bin in der Lage, ein erfülltes und erfolgreiches Leben zu führen.'
        ]

      ),
      Category(
        name: "Anwesenheit und Bewusstheit",
        affirmation: [
          'Ich bin in diesem Moment völlig anwesend.',
          'Mein Geist ist in diesem Moment klar und bewusst.',
          'Ich nehme die Schönheit der Gegenwart an.',
          'Ich bin im Hier und Jetzt verwurzelt.',
          'Mein Bewusstsein bringt mir Frieden.',
          'Mein Atem hält mich in der Gegenwart.',
          'Ich lasse die Vergangenheit und die Zukunft los.',
          'Ich bin achtsam gegenüber allem, was mich umgibt.',
          'Ich bin ruhig und präsent in meinem Körper.',
          'Ich finde Freude in diesem Augenblick.',
          'Mein Bewusstsein wächst mit jedem Atemzug.',
          'Ich bin hier, voll und ganz.',
          'Ich lasse Ablenkungen los und konzentriere mich auf das Jetzt.',
          'Ich bin auf den Fluss der Gegenwart eingestimmt.',
          'Mein Geist ruht in der Stille des Augenblicks.',
          'Ich bin mir der einfachen Geschenke des Lebens bewusst.',
          'Ich lebe jede Sekunde mit Absicht.',
          'Meine Präsenz ist meine Stärke.',
          'Ich beobachte meine Gedanken mit Klarheit.',
          'Ich bin in Frieden mit dem, was ist.',
          'Mein Bewusstsein erhellt meine Welt.',
          'Ich bin präsent für mich und andere.',
          'Ich genieße den Reichtum des Augenblicks.',
          'Meine Aufmerksamkeit ist jetzt scharf und beständig.',
          'Ich bin für die Entfaltung des Lebens sensibilisiert.',
          'Ich lasse los und bin einfach da.',
          'Meine Gegenwart ermächtigt mich.',
          'Ich gehe bewusst jeden Schritt.',
          'Ich bin in der Stille des Augenblicks verwurzelt.',
          'Ich bin offen für die Lektionen der Gegenwart.',
          'Ich sehe die Schönheit in jedem Blick.',
          'Mein Bewusstsein vertieft meinen Frieden.',
          'Ich lasse mich auf das Leben in diesem Augenblick ein.',
          'Mein Geist ist ruhig und achtsam.',
          'Ich lebe die Energie der Gegenwart.',
          'Ich schätze die Stille des Jetzt.',
          'Mein Bewusstsein fließt wie ein Fluss.',
          'Ich bin hier mit Liebe und Konzentration.',
          'Ich nehme die Details dieses Augenblicks wahr.',
          'Meine Gegenwart heilt und erneuert mich.',
          'Ich bin in Harmonie mit der Gegenwart.',
          'Ich bin zu meiner Existenz erwacht.',
          'Mein Atem hält mich im Jetzt.',
          'Ich bin voll bewusst und voll lebendig.',
          'Ich bin in jedem Moment voll präsent.',
          'Ich entwickle ein Bewusstsein für meine Gedanken und Gefühle.',
          'Ich bin im Frieden mit dem gegenwärtigen Moment.',
          'Ich entscheide mich für ein Leben im Bewusstsein.',
          'Ich bin mit meinem Körper und seinen Empfindungen verbunden.',
          'Ich bin in Harmonie mit meiner Umwelt.',
          'Ich bin dankbar für jeden Augenblick des Lebens.',
          'Ich bin in der Lage, die Vergangenheit und die Zukunft loszulassen.',
          'Ich bin voll und ganz auf den gegenwärtigen Moment konzentriert.',
          'Ich entwickle Freundlichkeit mir selbst gegenüber.',
          'Ich bin in der Lage, meine Gedanken mit Ruhe zu steuern.',
          'Ich bin in Frieden mit meinen Gefühlen und akzeptiere sie ohne Bewertung.',
          'Ich entscheide mich, die Schönheit in jedem Moment zu sehen.',
          'Ich bin in der Lage, einen Raum des inneren Friedens zu schaffen.',
          'Ich bin mit meiner Intuition verbunden und folge ihr.',
          'Ich bin sicher in der Gegenwart.',
          'Ich bin in der Lage, negative Gedanken in positive Gedanken zu verwandeln.',
          'Ich entwickle Dankbarkeit für jeden Augenblick des Lebens.',
          'Ich bin mir meiner Entscheidungen voll bewusst.',
          'Ich entscheide mich dafür, mit Absicht und Bewusstsein zu leben.',
          'Ich bin in der Lage, eine friedliche Umgebung um mich herum zu schaffen.',
          'Ich bin im Einklang mit meinem natürlichen Rhythmus.',
          'Ich bin dankbar für jede Lektion, die ich lerne.',
          'Ich bin in der Lage, Ablenkungen loszulassen.',
          'Ich bin in meinen Beziehungen voll präsent.',
          'Ich entwickle Mitgefühl für mich und andere.',
          'Ich bin in der Lage, meine Emotionen mit Gelassenheit zu steuern.',
          'Ich bin im Frieden mit meiner Vergangenheit und Zukunft.',
          'Ich bin in der Lage, ein erfülltes Leben zu gestalten.',
          'Ich entscheide mich, in jeder Situation das Positive zu sehen.',
          'Ich bin mit meinem Körper und seinen Bedürfnissen verbunden.',
          'Ich fühle mich in meiner Umgebung sicher.',
          'Ich bin in der Lage, Herausforderungen in Chancen zu verwandeln.',
          'Ich entwickle Geduld und Verständnis.',
          'Ich bin mir meiner Gedanken und Handlungen voll bewusst.',
          'Ich entscheide mich für ein Leben in Einfachheit und Frieden.',
          'Ich bin in der Lage, einen Raum der inneren Entspannung zu schaffen.',
          'Ich bin im Einklang mit der Natur.',
          'Ich bin dankbar für jeden Moment der Stille.',
          'Ich bin in der Lage, mich auf die Gegenwart zu konzentrieren.',
          'Ich entwickle Freundlichkeit gegenüber anderen.',
          'Ich bin im Frieden mit meinen Grenzen.',
          'Ich bin in der Lage, meine Ängste in Mut zu verwandeln.',
          'Ich entscheide mich, die Schönheit in jedem Menschen zu sehen.',
          'Ich bin mit meinem Herzen und seinen Sehnsüchten verbunden.',
          'Ich bin sicher in meinen Beziehungen.',
          'Ich bin in der Lage, ein Leben voller Sinn zu gestalten.',
          'Ich entwickle Dankbarkeit für jeden Moment der Verbindung mit anderen.',
          'Ich bin in jeder Erfahrung des Lebens voll präsent.'
        ]

      ),
      Category(
        name: "Liebe und Beziehungen",
        affirmation: [
          'Ich bin jeden Tag von Liebe umgeben.',
          'Mein Herz ist offen für tiefe Verbindungen.',
          'Ich ziehe liebevolle und freundliche Menschen in mein Leben.',
          'Ich gebe und empfange leicht Liebe.',
          'Meine Beziehungen sind auf Vertrauen und Fürsorge aufgebaut.',
          'Ich bin der bedingungslosen Liebe würdig.',
          'Ich pflege die Beziehungen, die mir wichtig sind.',
          'Liebe fließt frei in all meinen Interaktionen.',
          'Ich bin mit denen verbunden, die mich inspirieren.',
          'Mein Leben ist reich an bedeutungsvollen Beziehungen.',
          'Ich strahle Liebe aus und ziehe sie zu mir an.',
          'Ich bin eine Quelle der Wärme und Verbindung.',
          'Я ценю любовь, которую разделяю с другими.',
          'Mein Herz ist ein Magnet für Freundlichkeit.',
          'Ich werde zutiefst geliebt und wertgeschätzt.',
          'Ich baue leicht Brücken des Verständnisses.',
          'Die Liebe ist das Fundament meines Lebens.',
          'Ich bin in Harmonie mit den Menschen um mich herum.',
          'Ich ziehe Beziehungen an, die sicher und echt sind.',
          'Meine Selbstliebe wächst jeden Tag.',
          'Ich verbinde mich mit anderen auf sinnvolle Weise.',
          'Ich bin der Liebe in all ihren Formen würdig.',
          'Meine Anwesenheit bringt die Menschen näher zusammen.',
          'Ich bin dankbar für die Liebe in meinem Leben.',
          'Ich kommuniziere mit Liebe und Klarheit.',
          'Meine Beziehungen sind stark und unterstützend.',
          'Ich bin offen dafür, Zuneigung zu geben und zu empfangen.',
          'Die Liebe umgibt mich wie eine warme Umarmung.',
          'Ich fördere Frieden und Liebe in jeder Beziehung.',
          'Ich bin ein Leuchtfeuer der Liebe und des Mitgefühls.',
          'Mein Herz verbindet mich mit der Welt.',
          'Ich bin es wert, tiefe und dauerhafte Beziehungen zu haben.',
          'Ich wähle Beziehungen, die meinen Geist ehren.',
          'Liebe leitet meine Worte und Handlungen.',
          'Ich bin mit anderen durch Freundlichkeit verbunden.',
          'Mein Leben ist voll von liebenden Seelen.',
          'In der Gegenwart der Liebe fühle ich mich in Frieden.',
          'Ich ziehe Menschen an, die mich zutiefst schätzen.',
          'Meine Liebe stärkt jede Verbindung, die ich eingehe.',
          'Ich bin ein Gefäß der Liebe und des Verständnisses.',
          'Ich schätze die Einheit, die ich mit anderen fühle.',
          'Mein Herz ist offen für neue Freundschaften.',
          'Ich werde dafür geliebt, wie ich bin.',
          'Ich schaffe Raum für die Liebe, damit sie sich entfalten kann.',
          'Meine Beziehungen spiegeln gegenseitigen Respekt wider.',
          'Ich bin mit einem Netzwerk der Liebe verbunden.',
          'Ich teile meine Liebe großzügig und frei.',
          'Ich bin der Nähe und Fürsorge würdig.',
          'Meine Verbindungen mit anderen bringen mir Freude.',
          'Die Liebe ist der Rhythmus meiner Existenz.',
          'Ich bin einer tiefen und bedeutungsvollen Liebe würdig.',
          'Ich verdiene es, für das geliebt zu werden, was ich bin.',
          'Ich bin von Liebe umgeben und alles ist gut.',
          'Ich lasse mich von meiner Intuition zur wahren Liebe führen.',
          'Mit jedem Herzschlag sende ich Liebe in das Universum hinaus und sie kommt verstärkt zurück.',
          'Ich bin bereit, bedingungslose Liebe zu geben und zu empfangen.',
          'Ich bin ein Magnet für die Liebe und ziehe die richtige Person zu mir.',
          'Ich strahle Vertrauen, Charme und Liebe aus.',
          'Ich bin der Liebe würdig und verdiene die Liebe, die ich suche.',
          'Ich bin ein liebevoller und aufmerksamer Partner, der den richtigen Menschen anzieht.',
          'Meine Liebe zu mir selbst zieht automatisch die Liebe von anderen an.',
          'Ich bin bereit, bedingungslos zu lieben und geliebt zu werden.',
          'Ich ziehe gesunde und bereichernde Beziehungen an.',
          'Die Liebe, die ich gebe, ist ein Spiegelbild der Liebe, die ich verdiene.',
          'Ich bin im Frieden mit meiner Vergangenheit und das öffnet mich für neue Möglichkeiten.',
          'Ich bin der Schöpfer meiner liebevollen Realität, und ich erschaffe sie mit Liebe.',
          'Jeden Tag wächst die Liebe in mir und manifestiert sich in meinem Leben.',
          'Ich bin fähig, dauerhafte und glückliche Beziehungen aufzubauen.',
          'Ich entscheide mich für eine tiefe und bedingungslose Liebe.',
          'Ich bin ein positiver und liebevoller Mensch.',
          'Ich beabsichtige, meinen Partner immer bedingungslos zu lieben und zu unterstützen.',
          'Ich entscheide mich, freundlich und rücksichtsvoll zu meinem Partner zu sein.',
          'Ich kann Grenzen für eine stärkere Bindung setzen.',
          'Ich höre auf meinen Partner und bin bereit, mich für ihn zu verändern.',
          'Ich bin bereit, meine Beziehung über andere Prioritäten zu stellen.',
          'Ich berücksichtige immer die Meinung und die Gefühle meines Partners.',
          'Ich konzentriere mich darauf, meine gesunde Beziehung zu schützen.',
          'Ich kommuniziere mit meinem Partner mit Respekt und Verständnis.',
          'Ich bin in einer starken Beziehung.',
          'Ich habe die Fähigkeit, meine Beziehung gesund und glücklich zu halten.',
          'Es fällt mir leicht, mich an meinen Partner zu binden.',
          'Meine Liebe ist sichtbar und das Universum belohnt mich dafür.',
          'Die Person, die ich liebe, liebt mich auch.',
          'Ich fühle mich sicher in einer stabilen Beziehung.',
          'Das Universum bereitet mich auf eine dauerhafte Beziehung vor.',
          'Ich erlaube der Liebe, in mein Leben einzutreten.',
          'Ich fühle mich überall von Liebe umgeben.',
          'Ich erhalte von jedem, dem ich begegne, Liebe im Überfluss.',
          'Ich bin dankbar für die Liebe, die ich mit anderen teile.',
          'Ich feiere die Liebe, die ich mit anderen teile, und ihre transformierende Kraft.',
          'Ich bin auf meine eigene Art und Weise liebevoll und der Liebe würdig.',
          'Ich ehre die Stärke und Verletzlichkeit, die die Liebe mit sich bringt.',
          'Meine Liebe ist furchtlos, grenzenlos und entwickelt sich ständig weiter.',
          'Ich umarme das gesamte Spektrum der Liebe, vom leisen Flüstern bis zur großen Leidenschaft.',
          'In meiner jetzigen Beziehung bin ich glücklich und geliebt.',
          'Ich bin ein zuverlässiger und treuer Partner.',
          'Ich entscheide mich dafür, das Beste in meinem Partner zu sehen.',
          'Ich bin in der Lage zu verzeihen und vorwärts zu gehen.',
          'Ich entwickle Geduld und Verständnis in meiner Beziehung.',
          'Ich bin stolz auf die Liebe, die wir teilen, und feiere sie jeden Tag.'
        ]

      ),
      Category(
        name: "Freude und Glück",
        affirmation: [
          'Ich bin in jedem Augenblick von Freude erfüllt.',
          'Das Glück fließt mühelos durch mich hindurch.',
          'Ich entscheide mich dafür, die Schönheit in allem zu sehen.',
          'Mein Herz singt vor lauter Freude.',
          'Ich strahle Freude auf alle um mich herum aus.',
          'Ich nehme das Glück heute voll und ganz an.',
          'Ich bin dankbar für die Freude in meinem Leben.',
          'Lachen und Leichtigkeit erfüllen meine Tage.',
          'Ich finde das Glück in den kleinsten Dingen.',
          'Mein Geist tanzt jeden Tag vor Freude.',
          'Ich bin ein Magnet für positive Energie.',
          'Fröhlichkeit ist mein natürlicher Zustand.',
          'Ich empfange Freude mit offenen Armen.',
          'Mein Leben quillt über vor Freude.',
          'Ich strahle mit dem Licht des Glücks.',
          'Jeder meiner Schritte ist mit Freude erfüllt.',
          'Ich bin umgeben von Gründen zum Lächeln.',
          'Mein Herz ist lebendig vor Glück.',
          'Ich wähle jedes Mal die Freude vor der Angst.',
          'Ich bin überfüllt mit fröhlicher Energie.',
          'Das Glück wächst jeden Tag in mir.',
          'Ich sehe die Welt mit den Augen der Freude.',
          'Meine Seele ist gebadet in Zufriedenheit.',
          'Ich bin frei, reines Glück zu fühlen.',
          'Die Freude sprudelt tief aus mir heraus.',
          'Ich feiere das Leben mit jedem Atemzug.',
          'Ich bin eine Quelle der Freude für mich und andere.',
          'Das Glück folgt mir, wohin ich auch gehe.',
          'Ich lasse die Traurigkeit los und nehme die Freude an.',
          'Meine Tage sind von Positivität geprägt.',
          'Ich lebe in der Aufregung des Glücks.',
          'Freude ist der Rhythmus meines Herzens.',
          'Ich finde Freude an jedem neuen Tag.',
          'Mein Geist ist ein Garten der glücklichen Gedanken.',
          'Die Freude in mir hebt mich empor.',
          'Glück ist mein Geschenk an die Welt.',
          'Ich lächle leicht und fühle Freude.',
          'Mein Leben ist eine Leinwand aus glücklichen Momenten.',
          'Ich bin im Einklang mit dem Rhythmus der Freude.',
          'Jeder Tag bringt mir neues Glück.',
          'Ich bin eingewickelt in eine Decke der Freude.',
          'Mein Lachen erhellt meine Welt.',
          'Ich habe mich entschieden, in einem Zustand der Freude zu leben.',
          'Das Glück füllt mein Herz bis zum Rande.',
          'Die freudigen Momente des Lebens geben mir Energie.',
          'Mein Geist schwebt vor Glück.',
          'Ich bin von Liebe und Freude umgeben.',
          'Ich finde Freude daran, einfach am Leben zu sein.',
          'Mein Glück inspiriert die Menschen um mich herum.',
          'Ich bin ein Gefäß der unendlichen Freude.',
          'Ich bin in Frieden mit meiner Vergangenheit und zuversichtlich für meine Zukunft.',
          'Ich entscheide mich dafür, loszulassen, was mir nicht mehr dient.',
          'Ich bin im Einklang mit meiner wahren Mission und Leidenschaft.',
          'Ich bin in der Lage, einen positiven Einfluss auf das Leben anderer zu nehmen.',
          'Ich bin stolz auf meine Errungenschaften und feiere sie.',
          'Ich bin sicher und fühle mich in jeder Situation geborgen.',
          'Ich betrachte die Welt mit Optimismus und Hoffnung.',
          'Ich bin in der Lage, in jedem Moment Freude zu finden.',
          'Ich bin von Menschen umgeben, die mich inspirieren und unterstützen.',
          'Ich bin im Einklang mit dem Universum und es führt mich zum Erfolg.',
          'Ich bin in der Lage, positive Veränderungen in mein Leben zu bringen.',
          'Ich entscheide mich für ein Leben in Fluss und Frieden.',
          'Ich bin dankbar für die Schönheit, die in jedem Augenblick vorhanden ist.',
          'Ich bin einzigartig und trage zum Reichtum der Welt bei.',
          'Ich bin in der Lage, ein Leben voller Freude und Glück zu gestalten.',
          'Ich bin von bedingungsloser Liebe und Unterstützung umgeben.',
          'Ich beschließe, mich auf Liebe und Dankbarkeit zu konzentrieren.',
          'Ich bin in der Lage, meine Gefühle mit Ruhe und Gelassenheit zu steuern.',
          'Ich bin in Frieden mit meinen Gefühlen und akzeptiere sie ohne Bewertung.',
          'Ich bin stolz auf meine Fortschritte und wachse weiter.',
          'Ich bin in der Lage, Freude an der Bewältigung von Herausforderungen zu finden.',
          'Ich bin von unendlichen Möglichkeiten umgeben und erkunde sie mit Begeisterung.',
          'Ich entscheide mich dafür, jeden Tag mit Dankbarkeit und Begeisterung zu leben.',
          'Ich bin in der Lage, ein Umfeld zu schaffen, das meinem persönlichen Wachstum förderlich ist.',
          'Ich bin im Einklang mit meinem Herzen und lasse mich von meiner Intuition leiten.',
          'Ich bin in Frieden mit dem, was ich bin, und feiere mein Leben mit Freude.'
        ]

      ),
      Category(
        name: "Innerer Frieden und Gelassenhei",
        affirmation: [
          'Ich bin im Frieden mit mir selbst und der Welt um mich herum.',
          'Gelassenheit fließt durch mich wie ein sanfter Fluss.',
          'Ich lasse die Anspannung los und umarme die Gelassenheit in diesem Moment.',
          'Mein Geist ist ruhig und mein Herz ist friedlich.',
          'Ich atme Frieden ein und atme Stress aus.',
          'Ich bin im gegenwärtigen Moment verwurzelt.',
          'Jeder Atemzug erfüllt mich mit Ruhe.',
          'Ich lasse die Sorgen los und heiße den Frieden willkommen.',
          'Meine innere Ruhe wird jeden Tag stärker.',
          'Eine beruhigende Energie umgibt mich.',
          'Frieden ist mein natürlicher Seinszustand.',
          'Ich ziehe die Ruhe dem Chaos vor.',
          'Meine Gedanken sind ruhig und ausgeglichen.',
          'Ich bin sicher, entspannt und ruhig.',
          'Ich schwebe mühelos im Rhythmus des Lebens.',
          'Gelassenheit füllt jeden Winkel meines Geistes.',
          'Ich bin frei von Ängsten und voller Gelassenheit.',
          'Mein Herz schlägt in Harmonie mit der Welt.',
          'Ich lasse alles los, was meiner Gelassenheit nicht mehr dient.',
          'Ich bin ein Leuchtfeuer der Stille und Anmut.',
          'Jeder Augenblick bringt mir einen tieferen Frieden.',
          'Ich vertraue auf die Ruhe in mir.',
          'Mein Geist ist ruhig und zufrieden.',
          'Ich bin immer ausgeglichen und ruhig.',
          'Der Frieden umspült mich wie eine warme Welle.',
          'Ich lasse die Angst los und ruhe in der Gelassenheit.',
          'Mein Geist ist ein Zufluchtsort der Gelassenheit.',
          'Ich bin in Harmonie mit allen Dingen.',
          'Ruhe ist meine Stärke und meine Zuflucht.',
          'Ich heiße den Frieden in jedem Bereich meines Lebens willkommen.',
          'Ich bin beständig, gelassen und ausgeglichen.',
          'Mein Atem hält mich in Frieden.',
          'Ich lasse das Chaos los und lasse mich auf die Stille ein.',
          'Ich bin auch in herausfordernden Momenten ruhig.',
          'Frieden strahlt aus meinem Inneren.',
          'Ich bin freundlich zu mir selbst und finde Stille.',
          'Meine Seele ruht in stiller Zuversicht.',
          'Ich lasse die Hektik los und genieße den Frieden.',
          'Ich bin eins mit dem Frieden des Universums.',
          'Gelassenheit ist mein Geschenk an mich selbst heute.',
          'Ich atme die Anspannung aus und atme die Gelassenheit ein.',
          'Mein innerer Frieden ist ruhig und klar.',
          'Ich wähle jedes Mal Gelassenheit statt Konflikt.',
          'Eine Blase des Friedens umgibt mich.',
          'Mein Geist ruht leicht in der Stille.',
          'Ich bin entspannt, präsent und ruhig.',
          'Gelassenheit leitet jeden meiner Schritte.',
          'Ich finde Frieden darin, einfach ich selbst zu sein.',
          'Mein Herz ist leicht und mein Geist ist ruhig.',
          'Ich bin ein Ozean des Friedens, tief und weit.',
          'Ich bin in Frieden mit mir selbst und frei, so zu leben, wie ich es will.',
          'Ich vertraue dem Prozess des Lebens, der mich führt.',
          'Ich steuere meine Gefühle mit Ruhe und Klarheit.',
          'Ich entscheide mich, in jeder Situation das Positive zu sehen.',
          'Ich bin in Frieden mit meinen Entscheidungen und fühle mich frei.',
          'Ich gönne mir Zeit für Selbstfürsorge ohne Schuldgefühle.',
          'Ich bin offen für neue Möglichkeiten und heiße sie mit ruhigem Gewissen willkommen.',
          'Ich bin dankbar für die Lektionen, die ich jeden Tag lerne.',
          'Ich schaffe einen friedlichen inneren Raum, der meine Seele nährt.',
          'Ich lasse die Urteile anderer los und konzentriere mich auf die Liebe.',
          'Ich bin in Frieden mit meiner Vergangenheit und Zukunft.',
          'Ich entscheide mich für ein einfaches Leben und schätze die Schönheit des Lebens.',
          'Ich bleibe in jeder Situation ruhig und konzentriert.',
          'Ich vertraue meinem persönlichen Weg und fühle mich geführt.',
          'Ich bewältige Herausforderungen mit Gelassenheit und Zuversicht.',
          'Ich bin in meinem Leben von Liebe und Unterstützung umgeben.',
          'Ich entscheide mich, das Bedürfnis, alles zu kontrollieren, loszulassen.',
          'Ich bin in Frieden mit den unvermeidlichen Veränderungen in meinem Leben.',
          'Ich drücke meine Gefühle frei aus, ohne mich zurückzuhalten.',
          'Ich bin dankbar für die freudigen Momente, die ich mit anderen teile.',
          'Ich gestalte ein erfülltes und friedliches Leben.',
          'Ich fühle mich in jeder Situation sicher und geborgen.',
          'Ich konzentriere mich auf Liebe und Dankbarkeit.',
          'Ich bin in Harmonie mit der Welt um mich herum.',
          'Ich finde inneren Frieden in jedem Moment.',
          'Ich lasse Stress und Anspannung aus meinem Körper los.',
          'Ich bin offen für neue Erfahrungen mit Gelassenheit und Neugierde.',
          'Ich bin dankbar für jeden Moment der Stille und Meditation.',
          'Ich entscheide mich für ein Leben in Fluss und Frieden.',
          'Ich lenke meine Gedanken mit Ruhe und Klarheit.',
          'Ich bin von Menschen umgeben, die mich unterstützen und lieben.',
          'Ich bin in Frieden mit meinen Gefühlen und akzeptiere sie ohne Bewertung.',
          'Ich vertraue dem Universum, dass es mich zum inneren Frieden führt.',
          'Ich schaffe eine friedliche Umgebung um mich herum.',
          'Ich entscheide mich, die Erwartungen der anderen loszulassen.'
        ]

      ),
      Category(
        name: "Gesundheit und Vitalität",
        affirmation: [
          'Mein Körper ist stark und voller Energie.',
          'Ich strahle jeden Tag Gesundheit und Vitalität aus.',
          'Ich nähre mich mit Liebe und Sorgfalt.',
          'Meine Energie fließt frei und im Überfluss.',
          'Ich bin im Einklang mit den Bedürfnissen meines Körpers.',
          'Jeder Atemzug erfüllt mich mit Leben und Kraft.',
          'Ich bin pulsierend, gesund und lebendig.',
          'Mein Körper heilt und gedeiht natürlich.',
          'Ich wähle Gewohnheiten, die mein Wohlbefinden fördern.',
          'Ich bin von Kopf bis Fuß voller Vitalität.',
          'Meine Gesundheit wird jeden Tag stärker.',
          'Ich bewege mich mit Leichtigkeit und Vertrauen.',
          'Ich respektiere meinen Körper mit Ruhe und Aktivität.',
          'Meine Energie ist grenzenlos und lebendig.',
          'Ich bin dankbar für meinen starken, gesunden Körper.',
          'Ich fühle mich in jedem Moment lebendig und kraftvoll.',
          'Mein Wohlbefinden ist eine Priorität, die ich schätze.',
          'Ich befinde mich in perfekter Harmonie mit meiner Gesundheit.',
          'Mein Körper ist ein Tempel der Vitalität.',
          'Ich strahle im Licht der Gesundheit.',
          'Ich bin erfüllt von der Energie des Lebens in mir.',
          'Meine Kraft stärkt mich in allem, was ich tue.',
          'Ich genieße ein Leben voller Energie und Wohlbefinden.',
          'Mein Körper antwortet auf Pflege mit Stärke.',
          'Ich blühe in Körper, Geist und Seele auf.',
          'Meine Gesundheit ist ein Geschenk, das ich täglich pflege.',
          'Ich fühle mich erneuert und voller Leben.',
          'Meine Lebenskraft ist in jeder Handlung spürbar.',
          'Ich bin ausgeglichen und fülle mich mit Energie.',
          'Mein Körper ist stabil und kraftvoll.',
          'Ich wähle Lebensmittel, die meine Lebenskraft nähren.',
          'Ich lebe mit Wohlbefinden und Freude.',
          'Meine Gesundheit ermöglicht es mir, das Leben in vollen Zügen zu genießen.',
          'Ich bin stark, flexibel und frei.',
          'Ich kümmere mich mit Liebe und Absicht um mich selbst.',
          'Mein Körper ist eine Quelle der unendlichen Kraft.',
          'Ich bin hell in jeder Zelle meines Wesens.',
          'Mein Wohlbefinden strahlt von innen heraus.',
          'Ich bewege mich mit Energie und Anmut durchs Leben.',
          'Meine Gesundheit ist die Grundlage für mein Glück.',
          'Ich werde mit jedem Sonnenaufgang erneuert.',
          'Meine Vitalität wächst mit jedem Schritt.',
          'Ich bin im Einklang mit dem Rhythmus meines Körpers.',
          'Meine Kraft stärkt mich jeden Tag.',
          'Ich bin die Verkörperung von Gesundheit und Energie.',
          'Mein Körper unterstützt mich mit Liebe und Kraft.',
          'Ich fühle mich fantastisch und voller Leben.',
          'Vitalität ist mein natürlicher Zustand.',
          'Ich bin gesund, ganz und unaufhaltsam.',
          'Ich atme frei und vollständig.',
          'Ich fülle mich mit Gesundheit und Vitalität.',
          'Ich bin erfüllt von heilender Energie.',
          'Ich führe ein ausgeglichenes und gesundes Leben.',
          'Ich fühle mich in großartiger körperlicher und geistiger Verfassung.',
          'Ich entscheide mich dafür, von jetzt an gesund zu sein.',
          'Ich genieße es, für mich und andere zu sorgen.',
          'Ich verdiene und erlaube mir, mich auszuruhen, wenn es nötig ist.',
          'Ich konsumiere Lebensmittel, die meinen Körper respektieren.',
          'Ich respektiere und schätze meinen Körper.',
          'Alles an mir ist perfekt ausbalanciert.',
          'Mein Gewicht und meine Lebenszeichen normalisieren sich leicht.',
          'Ich erlaube mir, Gefühle auszudrücken und meine Bedürfnisse zu befriedigen.',
          'Ich bin voll und ganz ich selbst und habe Freude daran.',
          'Ich bin entspannt und bringe Gelassenheit in mein Leben.',
          'Ich bin flexibel und werde jeden Tag weicher.',
          'Ich werde jeden Tag besser und besser, in jeder Hinsicht.',
          'Ich fühle mich überall und zu jeder Zeit sicher.',
          'Ich vergebe mir und anderen und schenke Frieden.',
          'Ich sehe jetzt das Schöne in allem.',
          'Ich ändere die Art und Weise, wie ich auf meine Vergangenheit schaue, ich bin frei.',
          'Die Energie des Lebens drückt sich freudig durch mich aus.',
          'Ich kann eine bessere Lebenskraft kultivieren.',
          'Ich sende Unterstützung und Liebe an meinen Körper.',
          'Mein Körper kann sich leicht und natürlich erholen.',
          'Ich danke meinem Körper für alles, was gut funktioniert.',
          'Je mehr Positivität ich meinem Körper entgegenbringe, desto besser hält er sich gesund.',
          'Ich verdiene es, gesund zu sein und das Leben zu genießen.',
          'Ich liebe es, mit Vitalität und allgemeinem Wohlbefinden zu leben.',
          'Ich lasse alles los, was zwischen mir und einer perfekten Gesundheit steht.',
          'Gute Gewohnheiten helfen mir, in besserer Form zu bleiben.',
          'Jeder Teil meines Körpers ist fähig, sich zu verbessern.',
          'Jede Zelle in meinem Körper kann sich selbst reparieren.',
          'Mein Körper ist mein bester Freund.',
          'Ich verdiene es, gesund zu sein.',
          'Ich höre auf die Signale meines Körpers.',
          'Ich nehme mir die Zeit, mich um meinen Körper zu kümmern.',
          'Es liegt an mir, zu bestimmen, was ein gesunder Körper ist.',
          'Meine geistige und körperliche Gesundheit haben Priorität.',
          'Meine Krankheit definiert mich nicht.',
          'Ich lege Wert auf Ruhe und Entspannung.',
          'Ich fordere mich körperlich heraus.',
          'Ich feiere kleine Erfolge.',
          'Ich habe den Mut, dies zu tun.',
          'Hindernisse sind meine Chancen für Wachstum.',
          'Ich werde meine gesundheitlichen Ziele erreichen.',
          'Ich bin genau da, wo ich für meine Gesundheit sein muss.',
          'Jede Maßnahme, die ich ergreife, bringt mich einem gesünderen Leben näher.',
          'Ich bin erfolgreich in allem, was ich für meine Gesundheit tue.',
          'Ich gebe heute das Beste für meine Gesundheit.'
        ]

      ),
      Category(
        name: "Selbstvertrauen und Selbstwertgefühl",
        affirmation: [
          'Ich habe Vertrauen in mich selbst.',
          'Mein Wert leuchtet jeden Tag hell auf.',
          'Ich habe volles Vertrauen in meine Fähigkeiten.',
          'Ich bin ausreichend in dem, was ich bin.',
          'Ich stehe aufrecht in meiner eigenen Stärke.',
          'Mein Vertrauen wächst mit jedem Augenblick.',
          'Ich bin aller Vorteile würdig.',
          'Ich traue mir zu, gute Entscheidungen zu treffen.',
          'Ich bin stolz auf alles, was ich erreicht habe.',
          'Mein Wert ist unendlich und unerschütterlich.',
          'Ich strahle ohne Anstrengung Vertrauen aus.',
          'Ich bin der Liebe und des Respekts würdig.',
          'Ich nehme meine einzigartigen Stärken an.',
          'Ich bin mutig, fähig und stark.',
          'Mein Selbstwertgefühl ist ein Geschenk, das ich zu schätzen weiß.',
          'Ich fühle mich wohl in meiner eigenen Haut.',
          'Ich respektiere die Person, die ich werde.',
          'Ich bin meines eigenen Lobes würdig.',
          'Mein Selbstvertrauen inspiriert die Menschen um mich herum.',
          'Ich glaube an mein grenzenloses Potenzial.',
          'Mein Wert ist unschätzbar.',
          'Ich begegne jeder Herausforderung mit Mut.',
          'Meine innere Stärke treibt mich voran.',
          'Ich feiere mich jeden Tag selbst.',
          'Ich bin von meinem einzigartigen Weg überzeugt.',
          'Ich verdiene es, meinen Platz einzunehmen.',
          'Ich bin ein Meisterwerk, das ich selbst geschaffen habe.',
          'Mein Glaube an mich selbst ist unerschütterlich.',
          'Ich bin es wert, Erfolg und Freude zu haben.',
          'Ich strahle mit unerschütterlichem Vertrauen.',
          'Ich bin jetzt und immer genug.',
          'Ich traue mir zu, mich über Zweifel hinwegzusetzen.',
          'Mein Wert wird nicht von anderen definiert.',
          'Ich bin stark in meiner Authentizität.',
          'Ich akzeptiere meine Schwächen und meinen Glanz.',
          'Ich bin zuversichtlich bei jedem Schritt, den ich mache.',
          'Ich bin ein Geschenk für die Welt, so wie ich bin.',
          'Mein Selbstwertgefühl wächst mit jedem Atemzug, den ich mache.',
          'Ich folge mutig meinen Träumen.',
          'Ich respektiere und schätze mich zutiefst.',
          'Ich bin all dessen würdig, was ich mir wünsche.',
          'Mein Selbstvertrauen ist meine Superkraft.',
          'Ich bin mit mir selbst im Reinen.',
          'Ich vertraue meiner Stimme und meiner Vision.',
          'Ich bin jeder Gelegenheit würdig.',
          'Ich trage mich mit Stolz und Anmut.',
          'Mein Wert kommt aus mir selbst.',
          'Ich bin zuversichtlich, ganz und vollständig.',
          'Ich habe Vertrauen in mich und meine Fähigkeiten.',
          'Ich bin in der Lage, alle Herausforderungen zu meistern.',
          'Ich liebe und akzeptiere mich so, wie ich bin.',
          'Ich bin kompetent und begabt.',
          'Ich vertraue meiner Intuition.',
          'Ich bin zuversichtlich in meinen Entscheidungen.',
          'Ich schätze mich selbst für bare Münze.',
          'Ich bin stolz auf meine Fortschritte und Leistungen.',
          'Ich habe die Kontrolle über meine Gedanken und Gefühle.',
          'Ich bin der Liebe und des Respekts würdig.',
          'Ich entscheide mich, mich auf meine Stärken zu konzentrieren.',
          'Ich bin einzigartig und das macht mich besonders.',
          'Ich akzeptiere mich voll und ganz mit meinen Unvollkommenheiten.',
          'Ich bin fähig, mir ein Leben zu schaffen, das mich widerspiegelt, wie ich bin.',
          'Ich verdiene Erfolg und Glück.',
          'Ich bin mit mir selbst im Reinen.',
          'Ich bin mutig im Angesicht des Unbekannten.',
          'Ich bin genau da, wo ich sein muss.',
          'Ich bin ein vertrauenswürdiger Mensch.',
          'Ich bin Herr über mein Leben.',
          'Ich verdiene es, für mich selbst zu sorgen.',
          'Ich bin stolz auf mein Durchhaltevermögen.',
          'Ich beschließe, mich jeden Tag mehr zu lieben.',
          'Ich bin in der Lage, alles zu lernen, was ich lernen will.',
          'Ich stehe über negativen Gedanken und Handlungen.',
          'Ich sehe Hindernisse als Chancen für Wachstum.',
          'Ich bin zuversichtlich, was meine Entscheidungen betrifft.',
          'Ich bin begabt und intelligent.',
          'Ich drücke mich offen, ehrlich und selbstbewusst aus.',
          'Ich fühle mich wohl mit mir selbst.',
          'Ich gebe in jeder Situation mein Bestes.',
          'Ich bin stolz auf den Weg, den ich zurückgelegt habe.',
          'Ich bin im Einklang mit meinen Werten.',
          'Ich respektiere meine innere Natur.',
          'Ich bin fähig, alles zu erreichen, was ich erreichen will.',
          'Ich bin es wert, respektiert und gewürdigt zu werden.',
          'Ich entscheide mich, positive Gedanken zu kultivieren.',
          'Ich bin im Frieden mit meiner Vergangenheit.',
          'Ich überschreite selbstbewusst meine Grenzen.',
          'Ich bin ein kreatives und einzigartiges Individuum.',
          'Ich glaube an meine Fähigkeit, Hindernisse zu überwinden.',
          'Ich verdiene es, meine Erfolge zu feiern.',
          'Ich erlaube mir, Risiken einzugehen.',
          'Ich bin stärker als meine Ängste.',
          'Ich bin von Menschen umgeben, die mich unterstützen.',
          'Ich entscheide mich, mit Dankbarkeit und Zuversicht zu leben.',
          'Ich bin mutig genug, meine Meinung zu sagen.',
          'Ich erlaube mir, authentisch zu sein.',
          'Mein Potenzial ist außergewöhnlich.',
          'Ich bin fähig, positive Veränderungen in meinem Leben zu bewirken.'
        ]

      ),
      Category(
        name: "Fülle und Dankbarkeit",
        affirmation: [
          'Ich bin dankbar für die Fülle in meinem Leben.',
          'Meine Welt quillt über vor Gutem.',
          'Mit jedem Atemzug ziehe ich Wohlstand an.',
          'Ich bin dankbar für alles, was ich heute habe.',
          'Die Fülle kommt mühelos zu mir.',
          'Ich bin von grenzenlosen Segnungen umgeben.',
          'Mein Herz ist immer voll von Dankbarkeit.',
          'Ich sehe die Fülle in jedem Augenblick.',
          'Ich bin dankbar für die reichhaltigen Geschenke des Lebens.',
          'Wohlstand ist mein natürlicher Zustand.',
          'Ich schätze alles, was zu mir kommt.',
          'Mein Leben ist reich an Liebe und Freude.',
          'Ich bin offen dafür, unendlich viel Segen zu empfangen.',
          'Dankbarkeit erfüllt mich mit Frieden.',
          'Ich bin reich an Geist und Leben.',
          'Ich danke dem Universum für seinen Reichtum.',
          'Fülle umgibt mich jeden Tag.',
          'Ich bin dankbar für die großen und kleinen Siege.',
          'Mein Leben ist eine Schatzkammer des Überflusses.',
          'Ich heiße den Wohlstand mit offenen Armen willkommen.',
          'Ich bin dankbar für die Schönheit um mich herum.',
          'Meine Dankbarkeit zieht noch mehr Dinge an, die es wert sind, geschätzt zu werden.',
          'Ich lebe in einem Zustand der Freude im Überfluss.',
          'Ich bin über alle Maßen gesegnet.',
          'Mein Herz quillt über vor Dankbarkeit.',
          'Die Fülle gehört jetzt zu mir.',
          'Ich bin dankbar für jeden neuen Tag.',
          'Mein Leben ist gefüllt mit unendlichen Möglichkeiten.',
          'Ich bin dankbar für meine Stärke und mein Wachstum.',
          'Wohlstand fließt durch alles, was ich tue.',
          'Ich schätze den Reichtum auf meinem Weg.',
          'Meine Dankbarkeit schafft noch mehr Reichtum.',
          'Ich danke dem Leben für seine ständige Unterstützung.',
          'Meine Welt ist reich an Möglichkeiten.',
          'Ich bin dankbar für meine einzigartigen Gaben.',
          'Der Reichtum kommt in vielen Formen zu mir.',
          'Mein dankbares Herz zieht mehr Gutes an.',
          'Ich lebe mit einem Gefühl von Frieden im Überfluss.',
          'Ich bin reich an allem, was wirklich wichtig ist.',
          'Ich bin dankbar für den gegenwärtigen Moment.',
          'Mein Leben ist ein Garten des Überflusses.',
          'Ich bin offen für alles, was das Universum zu bieten hat.',
          'Dankbarkeit ist der Schlüssel zu meinem Reichtum.',
          'Ich blühe in Geist und Seele auf.',
          'Ich schätze die Liebe, die mein Leben füllt.',
          'Mein Reichtum wächst mit jedem Schritt.',
          'Ich bin dankbar für alles, was ich geworden bin.',
          'Ich sehe den Segen in jeder Ecke.',
          'Meine Dankbarkeit öffnet die Türen zu mehr.',
          'Ich bin dankbar für jedes Lächeln, das ich sehe.',
          'Ich bin offen für alle Formen des Reichtums, die in mein Leben treten.',
          'Ich bin dankbar für das Lachen, das ich mit anderen teile.',
          'Ich bin dankbar für jeden neuen Tag, der beginnt.',
          'Ich bin fähig, meine Fülle mit Großzügigkeit zu teilen.',
          'Ich bin dankbar für Momente tiefer Verbundenheit mit anderen.',
          'Fülle ist ein integraler Bestandteil meines täglichen Lebens.',
          'Ich bin dankbar für die Talente, die ich besitze.',
          'Ich bin umgeben von Fülle in meinen Gedanken und Handlungen.',
          'Ich bin dankbar für jeden Akt der Freundlichkeit, den ich erhalte.',
          'Ich bin fähig, ein reiches und erfülltes Leben zu gestalten.',
          'Ich bin dankbar für die Möglichkeiten zur persönlichen Weiterentwicklung.',
          'Ich bin bei meiner Arbeit und meinen Projekten von Überfluss umgeben.',
          'Ich bin dankbar für jeden Moment der Freiheit, den ich erlebe.',
          'Ich bin offen dafür, Fülle mit Demut anzunehmen.',
          'Ich bin dankbar für den klugen Rat, den ich erhalte.',
          'Ich bin umgeben von Fülle in meinen Träumen und Bestrebungen.',
          'Ich bin dankbar für jeden Moment der Kreativität, den ich erlebe.',
          'Ich bin in der Lage, in jeder Situation Fülle zu sehen.',
          'Ich bin dankbar für die Erfahrungen, die mich stärker gemacht haben.',
          'Ich bin umgeben von der Fülle meiner positiven Gedanken.',
          'Ich bin dankbar für jeden Menschen, der an mich glaubt.',
          'Ich bin in der Lage, meinen Reichtum mit Liebe zu teilen.',
          'Ich bin dankbar für Momente der Stille und Meditation.',
          'Ich bin umgeben von Fülle in meinem Zuhause und meiner Umgebung.',
          'Ich bin dankbar für jeden Akt der Solidarität, den ich sehe.',
          'Ich bin in der Lage, mir ein Leben in Fülle und Freude zu schaffen.',
          'Ich bin dankbar für die Lektionen, die ich jeden Tag lerne.',
          'Ich bin umgeben von Fülle in meinen liebevollen Beziehungen.',
          'Ich bin dankbar für jeden Moment des inneren Friedens, den ich erlebe.'
        ]

      ),
    ];
  }

  // Helper methods for easy access
  static List<String> getCategoryNames() {
    return getAllCategories().map((category) => category.name).toList();
  }

  static Category? getCategoryByName(String name) {
    try {
      return getAllCategories().firstWhere((category) => category.name == name);
    } catch (e) {
      return null;
    }
  }

  static List<String> getAffirmationByCategory(String categoryName) {
    final category = getCategoryByName(categoryName);
    return category?.affirmation ?? [];
  }

  static int getTotalAffirmationCount() {
    return getAllCategories()
        .map((category) => category.affirmation.length)
        .reduce((a, b) => a + b);
  }

  static String getRandomAffirmation() {
    final allCategories = getAllCategories();
    final randomCategory = (allCategories..shuffle()).first;
    final randomTip = (randomCategory.affirmation..shuffle()).first;
    return randomTip;
  }
}